### ISSUE TITLE
Please improve the "Quick Start" documentation page

### ISSUE THREAD

**Issue by ClaudioCorridore** [Netflix/pollyjs#105]
Please improve the [Quick Start](https://netflix.github.io/pollyjs/#/quick-start) documentation page.

I think that a step-by-step guide to write and launch a simple test scenario would greatly help adopters.

Thanks.

**Comment by offirgolan** [comment]
@ClaudioCorridore thanks for creating this issue. I had plans to do this in the next week or two plus add example (cookbook-like) pages for different environments.

Do you have specifics you're looking for?

**Comment by ClaudioCorridore** [comment]
I was not able to run the example. 
After starting the polly server using the polly cli, if I try to run the example code I got some errors. I tried to run the code with plain node js and also with the experimental es6 modules flag. 
It would be nice if users would be able to start a simple test scenario just to see the tool in action. 
I would be happy to help with the documentation but I would need a bit of guidance.

**Comment by jimmont** [comment]
it would be helpful to have:
a complete webpack dev server example recording and using all ‘/api’ calls that expands on the resolved issue 33
a similar proxy for local development that intercepts the same http ‘/api’ calls for recording/playback

**Comment by offirgolan** [comment]
@ClaudioCorridore @jimmont as a start to improve the documentation, I've added a bunch of working [examples](https://github.com/Netflix/pollyjs/tree/master/examples) to help you get started. Let me know if you have any other examples you'd think would be helpful or if the current one need to be modified in any way. 

I'll be working on improving the actual doc pages in the coming week.

**Comment by rafareyes7** [comment]
Please improve the documentation, it's really confusing. =(

**Comment by offirgolan** [comment]
Apologies for the delay on this everyone, its been a crazy few weeks! I've rewritten the Quick Start page with simpler examples as well as working CodePen embeds. I've also added an Examples page with all the current ones available in the `examples` directory. Let me know what you think — the more feedback the better 😄
