### ISSUE TITLE
Polly not passing requests through to react app server?

### ISSUE THREAD

**Issue by eric-khoury** [Netflix/pollyjs#107]
Hi,
I'm using Polly in a react app where I'm writing Selenium tests. Basically, react is running on localhost:3000 and selenium spins up a browser, which I can point to my react app to click on things, and everyone is happy. But now, I'm trying to stub out all my API requests (XHR) using Polly.
I run Polly with `polly l`, so it listens on port 3000. Now, both my react app and Polly is running on localhost:3000.

I have set up polly like this:

```
Polly.register(XHRAdapter)
Polly.register(LocalStoragePersister);

const polly = new Polly('Sign In', {
  adapters: ['xhr'],
  persister: 'local-storage'
});
const { server } = polly;

polly.configure({
  persisterOptions: {
    'local-storage': {
      key: '__pollyjs__'
    }
  }
});

polly.connectTo('xhr')

server.get('http://localhost:3000/slam-ui').passthrough()

```

The first thing I do in my test is to instruct selenium to go to http://localhost:3001/slam-ui and be passed through by Polly to actually reach my react app, but instead, this is what polly outputs:

<img width="254" alt="screen shot 2018-09-11 at 09 32 30" src="https://user-images.githubusercontent.com/1809797/45345188-dace8900-b5a5-11e8-8d63-8a678e61b784.png">

And the selenium browser only shows "Can't get "/slam-ui", so a just a 404.
I must be missing something fundamental here?

**Comment by offirgolan** [comment]
@eric-khoury is polly running within your react app or are you trying to run this in parallel with Selenium?

**Comment by eric-khoury** [comment]
@offirgolan  I'm trying to run it in parallel with selenium. Might be a bad idea?

**Comment by offirgolan** [comment]
@eric-khoury as of right now, we have no support for integration with selenium. We do however have full support for Puppeteer.

**Comment by eric-khoury** [comment]
@offirgolan Ok thx!

**Comment by offirgolan** [comment]
Np! You can check out working examples [here](https://github.com/Netflix/pollyjs/tree/master/examples) which include puppeteer and jest-puppeteer.

**Comment by offirgolan** [comment]
Im gonna go ahead and close this issue. Feel free to reopen or open a new one if something else comes up 😄
