### ISSUE TITLE
express integration?

### ISSUE THREAD

**Issue by jimmielemontgomery** [Netflix/pollyjs#109]
I cannot figure out how to use express integration for API calls that my server proxies. Where/how/what should I be doing to properly save http responses from these APIs so that once saved they are then returned from Pollyjs for all the following requests? My read through [the quickstart](https://netflix.github.io/pollyjs/#/node-server/express-integrations) hasn't led to the desired result. Here is an example of what I'm doing--and don't know where/how to make the above happen. Thanks in advance for any insight and help.. I should add I assume the middleware handles all these requests and writing to files--if that's incorrect please let me know.

```js
const PORT = process.env.PORT || 8444;
const express = require('express');
const request = require('request');

const Polly = require("@pollyjs/core");
const PollyServer = require("@pollyjs/node-server");

const app = express();
PollyServer.registerExpressAPI(app);

app
.use(express.json())
.use(function _httpHandler(req, res, next){
	console.log(`${ req.method } ${ req.url }`);
	req.__api = {}; // TODO
	try{
		// represents proxying to others...
		request({
			url: 'http://localhost' + req.url,
			headers: req.headers,
			method: req.method
		})
		.on('error', (err) => {
			next(err);
		})
		.pipe(res)
		;
	}catch(requestError){
		console.error(requestError);
	};
})
.use(function _httpErrorHandler(err, req, res, next) {
	let msg = (err.message || '').replace(/\n|\r/g, ' ').substr(0, 1000);
	let body = '';

	switch(err.code){
	case 'ENOENT':
		res.status(404);
		msg = `can't find it...`;
	break;
	case 'ECONNREFUSED':
		res.status(503);
		msg = `service unavailable ${req.url}`;
		console.warn(msg);
	break;
	default:
		res.status(500);
		console.error(err);
		// yes, stop and look
		debugger;
	};

	try{
		if(req.__api.json) body = JSON.stringify({error: msg, code: err.code, statusCode: err.statusCode});
		else body = `${msg}

stack:
${err.stack}`;

	}catch(trappedJSONError){
		body = msg;
	};
	res.end(body);
})
.listen( PORT )
;
console.log(`open http://localhost:${PORT}`);

```

**Comment by offirgolan** [comment]
@jimmielemontgomery Im not sure I completely understand what it is you're trying to do. As of right now, Polly doesnt have full node coverage as we do not have a low level node http request adapter. We do however have support for node-fetch. 

I highly recommend checking out the [examples](https://github.com/Netflix/pollyjs/tree/master/examples) directory for fully working examples. If that doesnt help you, would you mind creating some sort of reproduction that I can mess around with?

**Comment by EricZhaoCherryTomato** [comment]
Hi @offirgolan , I think I got the same question as @jimmielemontgomery here.

Basically, the question is, can I use PollyJS as a proxy server to cache the remote service response and replay it as necessary? 

The story behind this is that, I have a React app hit a third party API, which is unstable and under development. I would like to set up a Proxy server in the middle between my frontend App and third-party API. Then I can have a stable cached response for frontend work. I came across PollyJS, but most of the examples are unit test related. So is this PollyJS can use as a proxy playback server as I want? 

Thank you. 

Eric Z

**Comment by offirgolan** [comment]
@EricZhaoCherryTomato the short answer is **yes** but the only caveat is that you will have to use node-fetch (until #128 gets merged) with the fetch adapter + fs persister.

```js
app.get('/unstable', async function(req, res) {
  const polly = new Polly({ adapters: ['fetch'], persister: 'fs' });
  const response = await fetch('https://unstable.com/api/foo');

  res.json(await response.json());
  await polly.stop();
});
```

You can check out the [node-fetch example](https://github.com/Netflix/pollyjs/tree/master/examples/node-fetch) to help you get started.

**Comment by offirgolan** [comment]
This can now be achieved using the `node-http` adapter. Im gonna go ahead and close this issue. Feel free to reopen if needed.
