### ISSUE TITLE
Is it possible to record from node?

### ISSUE THREAD

**Issue by manobi** [Netflix/pollyjs#111]
I would like to record some API tests run from node.
Everytime I run my node.js api test it should update the persisted content.

Then I would like to run my frontend apps tests, but never reaching my real API, every request should return from the cached version.

How can I achieve this? Do I have write an adapter, if I’m using node-fetch which have the exact same api as the browser version?

**Comment by offirgolan** [comment]
@manobi and I have resolved this issue over twitter. A working example of node-fetch + adapter-fetch has been added in #112.
