### ISSUE TITLE
Not enough information when recording isn't found

### ISSUE THREAD

**Issue by scottc-netflix** [Netflix/pollyjs#114]
Pollyjs only tells the URL and method when a recording isn't found for a request. It's especially difficult to tell which request wasn't matched when using GraphQL, because all requests have the same method and URL. An ideal enhancement would be if it told you why it doesn't match, but just an option for more verbose logging of the missing recording would be very helpful!

**Comment by jasonmit** [comment]
> An ideal enhancement would be if it told you why it doesn't match, but just an option for more verbose logging of the missing recording would be very helpful!

Is this because the request payload is the reason for the mismatch and you would expect logging mentioning that?

**Comment by scottc-netflix** [comment]
Yeah, the body of a GraphQL request has an `operationName` field. In some cases it could be a header mismatch though.

**Comment by dustinsoftware** [comment]
@jasonmit @offirgolan would you be open to a PR that exposes an option for more verbose logging for these types of failures?

More verbose output could look something like:

```js
// packages/@pollyjs/adapter/src/index.js
async replay(pollyRequest) {
    // ...
    this.assert(
      'Recording for the following request is not found and `recordIfMissing` is `false`.\n' +
        `identifiers: ${JSON.stringify(pollyRequest.identifiers, null, 2)}\n` +
        `id: ${pollyRequest.id}\n` +
        `order: ${pollyRequest.order}`,
      false
    );
}
```

```
Error: [Polly] [adapter:node-http] Recording for the following request is not found and `recordIfMissing` is `false`.
identifiers: {
  "headers": {
    "Some-Header": "some-contents",
    ...
  },
  "method": "GET",
  "url": "//example.com/v1/users/me"
}
id: dbb7537a782efc1db94605d2be0d01d4
order: 8
```
