### ISSUE TITLE
Relative links are broken in the GitHub documentation

### ISSUE THREAD

**Issue by ReasonableDeveloper** [Netflix/pollyjs#117]
Hey, thank you for this library. I have just started using it and really like the API. 
When clicking through the documentation on GitHub I found that clicking on almost any link results in a 404 due to the markdown extension `.md` not being used in the relative paths of the links.

It is not that big of an issue since the official [docs](https://netflix.github.io/pollyjs/#/) don't have any broken links.

**Comment by offirgolan** [comment]
@ReasonableDeveloper thanks for bringing this to my attention, I'll look into it and see if adding `.md` will accommodate both the official docs and the raw github docs.

**Comment by offirgolan** [comment]
Looking more into this, even if we add `.md` to the relative paths, those specified paths are still absolute to the docs directory which is what docsify depends on and thus still wont work on github. Unfortunately, I dont think this is something we can easily solve 😞.
