### ISSUE TITLE
Do I need a special adapter to record requests done in Axios?

### ISSUE THREAD

**Issue by mottalrd** [Netflix/pollyjs#119]
Hello, thank you for your work on this!

I am playing with the googleapis JavaScript libraries and they appear to be based on Axios. https://github.com/axios/axios

I am using a xhr adapter but my request does not seem to be recorded. Is there any special configuration / adapter needed for Axios on Node.js? Or the xhr adapter should work just fine?

Thank you, looking forward to hearing back

**Comment by offirgolan** [comment]
We currently do not have support for axios on the node side. The goal is to create a generic node http request adapter so it would work with any node library. On the browser side, axios is supported since we have lower level XHR and fetch adapters that axios is built on top of.

**Comment by mottalrd** [comment]
Thank you!

**Comment by offirgolan** [comment]
@mottalrd I've created #120 to track the creation of the HTTP Request adapter. Im gonna go ahead and close this issue, feel free to reopen if necessary.
