### ISSUE TITLE
Node HTTP Request Adapter

### ISSUE THREAD

**Issue by offirgolan** [Netflix/pollyjs#120]
Create a low level Node HTTP Request adapter so we can fully support Node use cases.

**Comment by yasinuslu** [comment]
Hi @offirgolan, i would like to work on this

**Comment by offirgolan** [comment]
@yasinuslu thats awesome! PRs are always welcomed. Feel free to just go for it or open an RFC if you'd like to discuss implementation before 😄

**Comment by yasinuslu** [comment]
Thanks @offirgolan, i'll start working on it and see if i need to open an RFC or if i can just go for an implementation
