### ISSUE TITLE
Please imporve the examples

### ISSUE THREAD

**Issue by rafareyes7** [Netflix/pollyjs#122]
Hi, It would be nice if the examples contains a mini project of a server that record and replays HTTP responses.

**Comment by offirgolan** [comment]
@rafareyes7 I'm not entirely sure what you mean by this. Do you mind elaborating?

**Comment by rafareyes7** [comment]
Yes, Elaborate an example or put a piece of code in the QuickStart showing how to record and replay HTTP from a persisters.

**Comment by jasonmit** [comment]
https://github.com/Netflix/pollyjs/tree/master/examples there are many examples in the repo.

Feel free to open a PR to improve the docs where you feel they're lacking.
