### ISSUE TITLE
Typescript module declarations?

### ISSUE THREAD

**Issue by feinoujc** [Netflix/pollyjs#129]
I've built out what amounts to a complete or nearly complete module declaration for `@pollyjs/core` and some of utils. Does this project want to maintain these contributions or should it be contributed to DefinitelyTyped as a separate `@types` package?

**Comment by jasonmit** [comment]
@feinoujc I think for now should be maintained as a separate `@types` package.

Feel free to let us know once you do, we'd love to advertise it in the docs as I'm sure others will find it incredibly useful.

**Comment by feinoujc** [comment]
@jasonmit update on this:

they've been published in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30574

...BUT there is an issue (https://github.com/Microsoft/types-publisher/pull/502) in that repo with scoped packages not inferring their inter-dependencies automatically, so until that is fixed you have to install "too many" of the typings

for example, you have to install `@types/pollys__adapter` `@types/pollys__persister` and `@types/pollys__utils` when you install `@types/pollys__core`

less than ideal, really. Hopefully that gets sorted out soon.

**Comment by offirgolan** [comment]
@feinoujc this is great! Thank you for taking the time to put this together. Having to install that many packages is definitely less than ideal but it better than nothing! Hopefully they are able to resolve that issue on their end soon.
