### ISSUE TITLE
Ignore URL parameter for the comparison?

### ISSUE THREAD

**Issue by maximou4391** [Netflix/pollyjs#136]
Hello,

I was wondering is there is a way to ignore a particular parameter in the request so that when doing the comparison to see if the lib store or record the call it is replayed even is the parameter is different.

I mean in our webapp we have a parameter that depends on the session and that will also be different if we redo the exact same call let's say. 
I'm trying to use the lib to ease frontend development by abstracting our backend. We will record scenario/ flows and will replay them without a real backend in place.

Let me know if it's possible to ignore a parameter regarding the comparison.

Maxime.

**Comment by offirgolan** [comment]
@maximou4391 I'm not sure I follow what your exact needs are. Can you give me some more details or an example?

**Comment by offirgolan** [comment]
@maximou4391 would #138 solve the problem you're having?

**Comment by maximou4391** [comment]
Hello @offirgolan, indeed it might, for example:
request url **A** : https://www.mydomain.fr?param1=john&param2=456654
request url **B**: https://www.mydomain.fr?param1=john&param2=999999

I wanted to be able to replay B when only A has been recorded. I guess now with #138 I will be able to pass a function to ignore param2.

Thanks,

I will wait for it.

Regards,

Maxime.
