### ISSUE TITLE
Adapters do not work with custom context.

### ISSUE THREAD

**Issue by CGamesPlay** [Netflix/pollyjs#143]
The fetch adapter supports an option called `context`, which allows you to configure where the adapter will look for a fetch object to replace. However, this doesn't work: [updating the context object](https://github.com/Netflix/pollyjs/blob/master/packages/%40pollyjs/adapter-fetch/src/index.js#L30) doesn't do anything, because [the object is a clone](https://github.com/Netflix/pollyjs/blob/master/packages/%40pollyjs/core/src/polly.js#L162).

As a workaround, I'm currently using:
```
const polly = new Polly(recordingName, {
  // ...
  adapterOptions: {
    fetch: {
      context: fetchContext,
    }
  }
});
fetchContext.fetch = polly.config.adapterOptions.fetch.context.fetch;
```

**Comment by offirgolan** [comment]
@CGamesPlay thanks for reporting this! I was able to recreate this on my end as well. I'll work on getting this resolved 😄

**Comment by jasonmit** [comment]
@CGamesPlay what is the use-case for `fetchContext` as a plain object?

**Comment by CGamesPlay** [comment]
I wouldn't bemoan if the library were hard-coded to use the global context. I did end up needing to patch some bugs in `node-fetch` for use in my test environment, so I overrode the global `Response` and `Headers` classes, but I could just as easily do that if they were on the global object.

**Comment by jasonmit** [comment]
The reason I ask is because I believe the cloning strategy we implemented against will only clone an object if it's a pojo.  In normal circumstances, it's not and so we haven't run into this.

We will land a patch soon to resolve this.

**Comment by CGamesPlay** [comment]
Thanks for the quick turnaround, everyone!
