### ISSUE TITLE
PBFs (protobuf) failing in 3rd party lib

### ISSUE THREAD

**Issue by allthesignals** [Netflix/pollyjs#145]
I have Polly caching this request:

[https://tiles.planninglabs.nyc/fonts/Metropolis Regular,Noto Sans Regular/0-255.pbf](`https://tiles.planninglabs.nyc/fonts/Metropolis Regular,Noto Sans Regular/0-255.pbf`)

But it seems to fail:

<img width="781" alt="screen shot 2018-11-28 at 3 16 44 pm" src="https://user-images.githubusercontent.com/5004319/49179616-a8206b00-f320-11e8-915a-854827945ede.png">

I'm having trouble understanding what's being changed when being cached by Polly. Here's my invocation for Polly:

```
    const polly = new Polly('Simple Example', {
      adapters: ['fetch', 'xhr'],
      persister: 'local-storage',
      logging: true,
    });

    const { server: pollyServer } = polly;
```

Creating a passthrough for it produces the same issue. 

I noticed that the Proxy object includes an "undefined" body, but I'm not sure why. When I check the network tab, it appears to request the protobuf successfully:

<img width="812" alt="screen shot 2018-11-28 at 3 21 01 pm" src="https://user-images.githubusercontent.com/5004319/49179870-3f85be00-f321-11e8-8def-4f0d416784ca.png">

I also can't seem to find where in localstorage this is being kept. There's no entry in my browser for it.

For context, I'm using EmberCLI and Mirage, which includes Pretender (so that is probably interfering, but I can't be sure). 

Thanks for any help you're able to provide!

**Comment by offirgolan** [comment]
> I noticed that the Proxy object includes an "undefined" body, but I'm not sure why.

From your first screenshot, it looks like everything is there. You need to be looking at `response.body` not `body` as the latter is the request's posted body. 

Can you share what your test looks like, including the setupMirage/setupPolly calls?

**Comment by offirgolan** [comment]
Try the following:

```js
module('Acceptance | user can toggle between letter/legal and portrait/landscape', function(hooks) {
  setupApplicationTest(hooks);
  setupMirage(hooks);
  // Call setupPolly after mirage so that its the last to wrap fetch/xhr
  setupPolly(hooks, {
      adapters: ['fetch', 'xhr'],
      persister: 'local-storage',
      logging: true,
   });

  test('user can toggle between letter/legal and portrait/landscape', async (assert) => {
    const { server: pollyServer } = this.polly; 
    server.createList('project', 10);

    // Passthrough all paths that we want mirage to handle.
    pollyServer.get('/projects').passthrough();

    await visit('/projects/10');
    await click('.map-type-area-map');

    await mapboxGlLoaded();

    await click('.portrait-radio-button');
    const isPaperOrientationPortrait = find('.portrait');
    assert.equal(!!isPaperOrientationPortrait, true);

    await click('.letter-radio-button');
    const isPaperSizeLetter = find('.letter');
    assert.equal(!!isPaperSizeLetter, true);

    await click('.landscape-radio-button');
    const isPaperOrientationLandscape = find('.landscape');
    assert.equal(!!isPaperOrientationLandscape, true);

    await click('.tabloid-radio-button');
    const isLetterSizeTabloid = find('.tabloid');
    assert.equal(!!isLetterSizeTabloid, true);
  });
});
```

**Comment by allthesignals** [comment]
Thank you @offirgolan! I gave that a go, but it seems like `polly` is not available on `this`: `Cannot read property 'server' of undefined`. 

Here's what I've got:

```javascript
// ... same as above
import { Polly, setupQunit as setupPolly } from '@pollyjs/core';
import FetchAdapter from '@pollyjs/adapter-fetch';
import XHRAdapter from '@pollyjs/adapter-xhr';
import LocalStoragePersister from '@pollyjs/persister-local-storage';
import mapboxGlLoaded from '../helpers/mapbox-gl-loaded';

Polly.register(FetchAdapter);
Polly.register(LocalStoragePersister);
Polly.register(XHRAdapter);

module('Acceptance | user can toggle between letter/legal and portrait/landscape', function(hooks) {
  setupApplicationTest(hooks);
  setupMirage(hooks);
  setupPolly(hooks, {
    adapters: ['fetch', 'xhr'],
    persister: 'local-storage',
    logging: true,
  });

  test('user can toggle between letter/legal and portrait/landscape', async (assert) => {
    const { server: pollyServer } = this.polly;
    server.createList('project', 10);

    pollyServer.any('/projects').passthrough();

// other awaits
```

Full error:

```
TypeError: Cannot read property 'server' of undefined
    at Object._callee$ (http://localhost:7357/assets/tests.js:2846:43)
    at tryCatch (http://localhost:7357/assets/vendor.js:7241:40)
    at Generator.invoke [as _invoke] (http://localhost:7357/assets/vendor.js:7479:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:7357/assets/vendor.js:7293:21)
    at step (http://localhost:7357/assets/tests.js:2801:32)
    at http://localhost:7357/assets/tests.js:2819:16
    at new Promise (<anonymous>)
    at Object.<anonymous> (http://localhost:7357/assets/tests.js:2798:14)
    at Object.<anonymous> (http://localhost:7357/assets/tests.js:2905:21)
    at runTest (http://localhost:7357/assets/test-support.js:4298:30)
```

My ember-cli-qunit resolves to qunit version `~2.6.0`.

**Comment by offirgolan** [comment]
> it seems like polly is not available on this: Cannot read property 'server' of undefined.

It seems like something is interrupting setupPolly from setting `this.polly` on the test context. You would need to debug this more to figure out why this is happening. 

> I am still stuck with my 3rd party lib (mapbox-gl) unhappy with the Polly-intercepted (& recorded) XHR requests:

As of right now, the XHR and fetch adapters do not support binary response data. I would need some time to get that working correctly. I would instead just intercept the font call and respond with a Blob or binary string.

**Comment by offirgolan** [comment]
I've created #183 in order to better track this issue. I'm gonna go ahead and close this in favor of the other. Feel free to reopen if you have any further questions.
