### ISSUE TITLE
@pollyjs/ember and coalesceFindRequests is failing

### ISSUE THREAD

**Issue by nfc036** [Netflix/pollyjs#147]
Using ember-data's RESTAdapter with coalesceFindRequests=true multiple records are fetched using URLs like 
http://localhost:4200/modelname?ids%5B%5D=4196&ids%5B%5D=589&ids%5B%5D=644

@pollyjs/ember does not seem to handle this correctly. Only one of the "ids" is passed to the backend and persisted, i.e.
http://localhost:4200/modelname?ids%5B%5D=4196

Are there any recommendations/workarounds to use @pollyjs/ember together with coalesceFindRequests=true?

**Comment by offirgolan** [comment]
@nfc036 the coalesced url that was generated isnt exactly valid since its repeating the same query param key with different values. In your case:

```
/modelname?ids[]=1&ids[]=2&ids[]3
```

This will trip up all query param parsers and will give the same output as polly did. Instead the url should be something like the following:

```
/modelname?ids[]=1,2,3
```

**Comment by nfc036** [comment]
Hmmm. It is the way ember-data is currently handling this coalesced requests. Please see the documentation at 
https://www.emberjs.com/api/ember-data/3.5/classes/DS.RESTAdapter/properties/coalesceFindRequests?anchor=coalesceFindRequests

**Comment by offirgolan** [comment]
Ah interesting. I'll take a look to see what we can do here.

**Comment by offirgolan** [comment]
@nfc036 released with `v1.4.1`.

**Comment by nfc036** [comment]
Awesome! I can confirm that pollyjs@1.4.1 is correctly working with ember-data's coalesceFindRequests=true. Thank you for all the great work!
