### ISSUE TITLE
Uncaught (in promise) TypeError: Illegal invocation

### ISSUE THREAD

**Issue by maximou4391** [Netflix/pollyjs#153]
Hello,
We are trying to record all the calls from our Angular webapp (to replay them to be able to disconnect from our backend basically for dev purposes).
To do this we have made a static js page where we create the pollyjs instance and put it in window object (to stop it later). Then we launch and record the first call that will return a JSP (that contains the angular <app> tag), we replace the all html content by the result of the call and then the angular webapp is launched. For some reasons we have a strange error when recording the first call:
![error](https://user-images.githubusercontent.com/13694761/50682242-86e12780-100e-11e9-978b-09003bd98b74.PNG)

The problematic code in the pollyjs is here I think:
![image](https://user-images.githubusercontent.com/13694761/50682277-a11b0580-100e-11e9-8321-f424333ae38d.png)

I know it’s a bit hard to have a solution with this little context but if you have an idea a way for us to explore a potential solution that would be awesome.

Regards,

Maxime.

**Comment by jasonmit** [comment]
Nothing really comes to mind.  This is the first time I've heard of this.

Any chance you can share the bundle?

**Comment by offirgolan** [comment]
From the given stack trace, it looks like the issue is coming from within the fakeXhr send method. Can you step in there to see which line its failing on?

![screen shot 2019-01-07 at 11 57 16 am](https://user-images.githubusercontent.com/575938/50790317-7bdb0100-1273-11e9-9321-7fb1ec143c5c.png)

**Comment by maximou4391** [comment]
Hi @offirgolan, 
I put a screenshot of the line in my first comment. I will try to do a live example as soon as possible.

Regards,

Maxime.

**Comment by offirgolan** [comment]
@maximou4391 any updates on this?

**Comment by maximou4391** [comment]
Hello @offirgolan,
Sorry for the late answer, finally instead of a static JS page we put a first angular app (a different one than the main one) which create the polly instance and start the record and we don't have the error anymore. 
You can close the issue it's working quite well like this,

Thanks and have a good week.
