### ISSUE TITLE
Node HTTP Request adapter with Request js lib ECONNREFUSED Issue

### ISSUE THREAD

**Issue by timpur** [Netflix/pollyjs#156]
@yasinuslu or @offirgolan did you ever test a POST request using https://github.com/request/request, i get `Error: connect ECONNREFUSED 127.0.0.1:4000` even though polly responds with `Replayed ➞ POST http://localhost:4000/`

Not sure what logs would be more use full for you guys ?

Will post if i make any progress on this. Thanks

**Comment by offirgolan** [comment]
@timpur any chance you can create a reproduction that I can play around with?

**Comment by timpur** [comment]
Yeah I can do that :)

**Comment by offirgolan** [comment]
@timpur can you see if `v1.4.2` fixes this for you?

**Comment by rahulrana95** [comment]
This might be issue that something else running on same port

**Comment by timpur** [comment]
i still need to make a test repo, will retest this thanks.

**Comment by offirgolan** [comment]
@timpur any more info on this?

**Comment by timpur** [comment]
@offirgolan https://github.com/timpur/bug-pollyjs-node just run `npm test`

Hope you guys can solve :)

**Comment by offirgolan** [comment]
@timpur I was not able to recreate your issue with the steps taken below:

1. Clone repo
2. Bump all @pollyjs dependencies to latest
3. Run `npm test` --> `Recorded ➞ GET https://reqres.in/api/users 200 • 70ms`
4. Run `npm test` --> `Replayed ➞ GET https://reqres.in/api/users 200 • 2ms`
5. Disconnect from internet
6. Run `npm test` --> `Replayed ➞ GET https://reqres.in/api/users 200 • 2ms`

**Comment by offirgolan** [comment]
Version 2.0.0+ of the node-http adapter has a completely new implementation than its predecessor so thats where I suspect the issue is coming from. My suggestion is to upgrade all your @pollyjs packages which should solve your issue.

**Comment by timpur** [comment]
@offirgolan thanks, will confirm and get back to you :)

**Comment by timpur** [comment]
Confirmed

All works as expected :)
