### ISSUE TITLE
Replaying authorized requests?

### ISSUE THREAD

**Issue by ericclemmons** [Netflix/pollyjs#158]
Going off of the [jest-example](https://github.com/Netflix/pollyjs/blob/master/examples/jest-node-fetch/__tests__/index.test.js), I started using PollyJS in a project:

```js
setupPolly({
  adapters: ['node-http'],
  matchRequestsBy: {
    headers(headers) {
      // All headers are lower-cased by this point
      // (e.g. Authorization => authorization)
      const { authorization, ...remaining } = headers;

      return remaining;
    },
    order: false
  },
  mode: 'replay',
  persister: 'fs',
  persisterOptions: {
    fs: {
      recordingsDir: require('path').resolve(__dirname, '__recordings__')
    }
  },
  // This seems necessary to record *all* responses, even those with no cache headers.
  recordIfExpired: true
});

const username = process.env.TEST_USER
const password = process.env.TEST_PASSWORD

describe('Kitchen Sink example', () => {
    describe(`with user ${username}`, () => {
      beforeAll(async () => {
        // This is where `context` gets an OAUTH token
        await context.authenticate(username, password);
      });

      it('should match snapshot', async () => {
        console.time(`with user ${username}`);
        const payload = await graphql(schema, query, undefined, context, variables);
        console.timeEnd(`with user ${username}`);
        expect(payload).toMatchSnapshot();
      });
    });
  });
});
```

I confirmed that the above setup, records what I'd expect to a HAR file (with the exception of the OAUTH token call, for whatever reason).

But, if I remove the `context.authenticate` call, then none of the calls replay and I instead get `401` errors.

I've tried replicating this in the examples within the repo, but I can't seem to.

My best guess is that there's _some_ logic that says "the request looks different without the Authorization header than the recording" (despite configuring it to ignore it).

**Comment by offirgolan** [comment]
I believe thats because `setupPolly` create a new polly instance in a `beforeEach` hook which runs after the `beforeAll` hook you have. That means that the authentication request never gets picked up by Polly. Can you try changing your `beforeAll` to `beforeEach`?

**Comment by ericclemmons** [comment]
Great idea!  I'll give it a shot!

That would explain why I couldn't reproduce it in a sample repo...

**Comment by ericclemmons** [comment]
Yep, using `beforeEach` was the trick. Thanks!
