### ISSUE TITLE
Record outside of test context?

### ISSUE THREAD

**Issue by ericclemmons** [Netflix/pollyjs#159]
I'm looking to record/replay by request, which means **`REPLAY` outside of tests**.

But, it seems that _recording does not work outside of a test environment_!

Here's what I did: I moved the setup from `setupPolly` to `src/index.js`, and the tests run, but no recordings are created.

```diff
diff --git a/examples/jest-node-fetch/__tests__/index.test.js b/examples/jest-node-fetch/__tests__/index.test.js
index f224c49..effa6c3 100644
--- a/examples/jest-node-fetch/__tests__/index.test.js
+++ b/examples/jest-node-fetch/__tests__/index.test.js
@@ -1,26 +1,6 @@
-const path = require('path');
-
-const { Polly } = require('@pollyjs/core');
-const { setupPolly } = require('setup-polly-jest');
-const NodeHttpAdapter = require('@pollyjs/adapter-node-http');
-const FSPersister = require('@pollyjs/persister-fs');
-
-Polly.register(NodeHttpAdapter);
-Polly.register(FSPersister);
-
 const { posts, users } = require('../src');

 describe('jest-node-fetch', () => {
-  setupPolly({
-    adapters: ['node-http'],
-    persister: 'fs',
-    persisterOptions: {
-      fs: {
-        recordingsDir: path.resolve(__dirname, '../__recordings__')
-      }
-    }
-  });
-
   describe('posts', () => {
     it('should return post', async () => {
       const post = await posts('1');
diff --git a/examples/jest-node-fetch/src/index.js b/examples/jest-node-fetch/src/index.js
index e10e89e..c793f6e 100644
--- a/examples/jest-node-fetch/src/index.js
+++ b/examples/jest-node-fetch/src/index.js
@@ -1,3 +1,21 @@
+const { Polly } = require('@pollyjs/core');
+const NodeHttpAdapter = require('@pollyjs/adapter-node-http');
+const FSPersister = require('@pollyjs/persister-fs');
+const path = require('path');
+
+Polly.register(NodeHttpAdapter);
+Polly.register(FSPersister);
+
+new Polly('jest-node-fetch', {
+  adapters: ['node-http'],
+  logging: true,
+  persister: 'fs',
+  persisterOptions: {
+    fs: {
+      recordingsDir: path.resolve(__dirname, '../__recordings__')
+    }
+  }
+});
+
 module.exports = {
   posts: require('./posts'),
   users: require('./users')
```

<details>
<summary>
You can see that logging shows `Recording`, but nothing is persisted to the filesystem!
</summary>

 RUNS  __tests__/index.test.js

Test Suites: 0 of 1 total
Tests:       0 total
Snapshots:   0 total
  console.group node_modules/@pollyjs/core/dist/cjs/pollyjs-core.js:2309
      jest-node-fetch

  console.log node_modules/@pollyjs/core/dist/cjs/pollyjs-core.js:2322
      Recorded ➞ GET https://jsonplaceholder.typicode.com/posts/1 200 • 116ms PollyRequest {
      headers:
       { accept: [ '*/*' ],
         'user-agent': [ 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)' ],
         'accept-encoding': [ 'gzip,deflate' ],
         connection: [ 'close' ],
         host: 'jsonplaceholder.typicode.com' },
      didRespond: true,
      method: 'GET',
      body: [],
      recordingName: 'jest-node-fetch',
      recordingId: 'jest-node-fetch_1142061259',
      requestArguments:
       [ TransportWrapper { name: 'http', adapter: [Object], transport: [Object] },
         ClientRequest {
           domain: null,
           _events: [Object],
           _eventsCount: 2,
           _maxListeners: undefined,
           output: [],
           outputEncodings: [],
           outputCallbacks: [],
           outputSize: 0,
           writable: true,
           _last: true,
           upgrading: false,
           chunkedEncoding: false,
           shouldKeepAlive: false,
           useChunkedEncodingByDefault: false,
           sendDate: false,
           _removedConnection: false,
           _removedContLen: false,
           _removedTE: false,
           _contentLength: null,
           _hasBody: true,
           _trailer: '',
           finished: false,
           _headerSent: false,
           socket: [Object],
           connection: [Object],
           _header: null,
           _onPendingData: [Function: noopPendingOutput],
           agent: [Object],
           socketPath: undefined,
           timeout: undefined,
           method: 'GET',
           path: '/posts/1',
           _ended: false,
           res: null,
           aborted: undefined,
           timeoutCb: null,
           upgradeOrConnect: false,
           parser: [Object],
           maxHeadersCount: null,
           write: [Function],
           end: [Function],
           [Symbol(outHeadersKey)]: [Object] },
         [ [Object], undefined ] ],
      promise: Promise { <pending>, resolve: [Function], reject: [Function] },
      action: 'record',
      config:
       { mode: 'replay',
         adapters: [ 'node-http' ],
         adapterOptions: {},
         persister: 'fs',
         persisterOptions: { keepUnusedRequests: false, fs: [Object] },
         logging: true,
         recordIfMissing: true,
         recordIfExpired: false,
         recordFailedRequests: false,
         expiresIn: null,
         timing: [Function],
         matchRequestsBy:
          { method: true,
            headers: true,
            body: true,
            order: true,
            url: [Object] } },
      response:
       PollyResponse {
         headers:
          { date: 'Fri, 11 Jan 2019 01:17:36 GMT',
            'content-type': 'application/json; charset=utf-8',
            'transfer-encoding': 'chunked',
            connection: 'close',
            'set-cookie': [Array],
            'x-powered-by': 'Express',
            vary: 'Origin, Accept-Encoding',
            'access-control-allow-credentials': 'true',
            'cache-control': 'public, max-age=14400',
            pragma: 'no-cache',
            expires: 'Fri, 11 Jan 2019 05:17:36 GMT',
            'x-content-type-options': 'nosniff',
            etag: 'W/"124-yiKdLzqO5gfBrJFrcdJ8Yq0LGnU"',
            via: '1.1 vegur',
            'cf-cache-status': 'HIT',
            'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
            server: 'cloudflare',
            'cf-ray': '49738b6cdf5979cd-SEA',
            'content-encoding': 'gzip' },
         statusCode: 200,
         body: '["1f8b0800000000000003558f4b6a04410c43f7730a51eb6cb29d1be40ebd715c0a63e8fa8ccb1e2684dc3d744308012324901fe8eb02945cf4b75aae787d39a2fdd9b0d859ae282b7b4032f0214a279c93fb2e81e9e361953d3054852a61e0533923dd3066d838cace1b7ba55b9413fc3eeae7c1bda7091858b9d4a6c5d67f1d9c9a4b7a1542475fbc67f648079f93d5e27cd36c5bff87471b3b57981019c7dd53166284b4adf7b1c2b3c17928d739890de73a67031fecc680b8de2ca831cae5fb0715c693e824010000"]',
         timestamp: '2019-01-11T01:17:36.195Z' },
      identifiers:
       { headers:
          { accept: [Array],
            'user-agent': [Array],
            'accept-encoding': [Array],
            connection: [Array],
            host: 'jsonplaceholder.typicode.com' },
         method: 'GET',
         body: [],
         url: 'https://jsonplaceholder.typicode.com/posts/1' },
      id: '41b7d6ef74440e3b785f1634743f9139',
      order: 0,
      timestamp: '2019-01-11T01:17:36.079Z',
      responseTime: 116,
      [Symbol()]:
       URL {
         slashes: true,
         protocol: 'https:',
         hash: '',
         query: {},
         pathname: '/posts/1',
         auth: '',
         host: 'jsonplaceholder.typicode.com',
         port: '',
         hostname: 'jsonplaceholder.typicode.com',
         password: '',
         username: '',
         origin: 'https://jsonplaceholder.typicode.com',
         href: 'https://jsonplaceholder.typicode.com/posts/1' },
      [Symbol()]:
       Polly {
         logger:
          Logger {
            polly: [Circular],
            groupName: 'jest-node-fetch',
            _middleware: [Object] },
         server:
          Server {
            [Symbol()]: '',
            [Symbol()]: [Object],
            [Symbol()]: [],
            [Symbol()]: [Array] },
         config:
          { mode: 'replay',
            adapters: [Array],
            adapterOptions: {},
            persister: 'fs',
            persisterOptions: [Object],
            logging: true,
            recordIfMissing: true,
            recordIfExpired: false,
            recordFailedRequests: false,
            expiresIn: null,
            timing: [Function],
            matchRequestsBy: [Object] },
         container: Container { _registry: [Object] },
         adapters: Map { _c: [Object] },
         persister:
          fs {
            polly: [Circular],
            pending: [Object],
            _cache: [Object],
            api: [Object] },
         _requests: [ [Object] ],
         [Symbol()]: 'jest-node-fetch',
         [Symbol()]: 'jest-node-fetch_1142061259' },
      [Symbol()]:
       EventEmitter {
         [Symbol()]: Map { _c: [Object] },
         [Symbol()]: Set { _c: [Object] } },
      [Symbol()]:
       Route {
         params: {},
         queryParams: {},
         handlers: [],
         middleware: [ [Object] ] } }

  console.log node_modules/@pollyjs/core/dist/cjs/pollyjs-core.js:2322
      Recorded ➞ GET https://jsonplaceholder.typicode.com/users/1 200 • 80ms PollyRequest {
      headers:
       { accept: [ '*/*' ],
         'user-agent': [ 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)' ],
         'accept-encoding': [ 'gzip,deflate' ],
         connection: [ 'close' ],
         host: 'jsonplaceholder.typicode.com' },
      didRespond: true,
      method: 'GET',
      body: [],
      recordingName: 'jest-node-fetch',
      recordingId: 'jest-node-fetch_1142061259',
      requestArguments:
       [ TransportWrapper { name: 'http', adapter: [Object], transport: [Object] },
         ClientRequest {
           domain: null,
           _events: [Object],
           _eventsCount: 2,
           _maxListeners: undefined,
           output: [],
           outputEncodings: [],
           outputCallbacks: [],
           outputSize: 0,
           writable: true,
           _last: true,
           upgrading: false,
           chunkedEncoding: false,
           shouldKeepAlive: false,
           useChunkedEncodingByDefault: false,
           sendDate: false,
           _removedConnection: false,
           _removedContLen: false,
           _removedTE: false,
           _contentLength: null,
           _hasBody: true,
           _trailer: '',
           finished: false,
           _headerSent: false,
           socket: [Object],
           connection: [Object],
           _header: null,
           _onPendingData: [Function: noopPendingOutput],
           agent: [Object],
           socketPath: undefined,
           timeout: undefined,
           method: 'GET',
           path: '/users/1',
           _ended: false,
           res: null,
           aborted: undefined,
           timeoutCb: null,
           upgradeOrConnect: false,
           parser: [Object],
           maxHeadersCount: null,
           write: [Function],
           end: [Function],
           [Symbol(outHeadersKey)]: [Object] },
         [ [Object], undefined ] ],
      promise: Promise { <pending>, resolve: [Function], reject: [Function] },
      action: 'record',
      config:
       { mode: 'replay',
         adapters: [ 'node-http' ],
         adapterOptions: {},
         persister: 'fs',
         persisterOptions: { keepUnusedRequests: false, fs: [Object] },
         logging: true,
         recordIfMissing: true,
         recordIfExpired: false,
         recordFailedRequests: false,
         expiresIn: null,
         timing: [Function],
         matchRequestsBy:
          { method: true,
            headers: true,
            body: true,
            order: true,
            url: [Object] } },
      response:
       PollyResponse {
         headers:
          { date: 'Fri, 11 Jan 2019 01:17:36 GMT',
            'content-type': 'application/json; charset=utf-8',
            'transfer-encoding': 'chunked',
            connection: 'close',
            'set-cookie': [Array],
            'x-powered-by': 'Express',
            vary: 'Origin, Accept-Encoding',
            'access-control-allow-credentials': 'true',
            'cache-control': 'public, max-age=14400',
            pragma: 'no-cache',
            expires: 'Fri, 11 Jan 2019 05:17:36 GMT',
            'x-content-type-options': 'nosniff',
            etag: 'W/"1fd-+2Y3G3w049iSZtw5t1mzSnunngE"',
            via: '1.1 vegur',
            'cf-cache-status': 'HIT',
            'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
            server: 'cloudflare',
            'cf-ray': '49738b6d8c2379ed-SEA',
            'content-encoding': 'gzip' },
         statusCode: 200,
         body: '["1f8b08000000000000034590cd6e83301084ef3cc5cae71a95000172eacf2187a652d53ec1022bb06a6cb4364d9328ef5e61427ab3e6dbf5eccc250210aa153b481ee6a7c181c40ec481d018823d638f83086872c42b7e61f28b4a032a3d4b5fca34c4f484232b1dd7eabc706c5b26e7c40e2e110080709e89fcbcf136697470505dbffc35c349f960f03cfa18f27cbb8246f9d3acef8f646acb76eafa159dd5d8d8366c559baa2a655a16d90a3bb2776b00a13138cbb488d324af6e533330dd0cca244eb26a2b827c8d00ae21c4d85b130c1259148fb248b7b27c4c13f8cdb759b659821ea976b7e37ba55bea90dbd872b7d0c60e239ad37f0d6b939f76c06e2246f9cad6e03d2ffaa6ffe8195d987a9fb45752e389985a68b422e3a523fe21064313a39686ee2dd62e5c816cc83960422dbd1a08480ec8dfe4dd9cef1a5dff006748ce45fd010000"]',
         timestamp: '2019-01-11T01:17:36.295Z' },
      identifiers:
       { headers:
          { accept: [Array],
            'user-agent': [Array],
            'accept-encoding': [Array],
            connection: [Array],
            host: 'jsonplaceholder.typicode.com' },
         method: 'GET',
         body: [],
         url: 'https://jsonplaceholder.typicode.com/users/1' },
      id: '902ec6bd7d5925aefdb6e4091e660f11',
      order: 0,
      timestamp: '2019-01-11T01:17:36.215Z',
      responseTime: 80,
      [Symbol()]:
       URL {
         slashes: true,
         protocol: 'https:',
         hash: '',
         query: {},
         pathname: '/users/1',
         auth: '',
         host: 'jsonplaceholder.typicode.com',
         port: '',
         hostname: 'jsonplaceholder.typicode.com',
         password: '',
         username: '',
         origin: 'https://jsonplaceholder.typicode.com',
         href: 'https://jsonplaceholder.typicode.com/users/1' },
      [Symbol()]:
       Polly {
         logger:
          Logger {
            polly: [Circular],
            groupName: 'jest-node-fetch',
            _middleware: [Object] },
         server:
          Server {
            [Symbol()]: '',
            [Symbol()]: [Object],
            [Symbol()]: [],
            [Symbol()]: [Array] },
         config:
          { mode: 'replay',
            adapters: [Array],
            adapterOptions: {},
            persister: 'fs',
            persisterOptions: [Object],
            logging: true,
            recordIfMissing: true,
            recordIfExpired: false,
            recordFailedRequests: false,
            expiresIn: null,
            timing: [Function],
            matchRequestsBy: [Object] },
         container: Container { _registry: [Object] },
         adapters: Map { _c: [Object] },
         persister:
          fs {
            polly: [Circular],
            pending: [Object],
            _cache: [Object],
            api: [Object] },
         _requests: [ [Object], [Object] ],
         [Symbol()]: 'jest-node-fetch',
         [Symbol()]: 'jest-node-fetch_1142061259' },
      [Symbol()]:
       EventEmitter {
         [Symbol()]: Map { _c: [Object] },
         [Symbol()]: Set { _c: [Object] } },
      [Symbol()]:
 PASS  __tests__/index.test.js
  jest-node-fetch
    posts
      ✓ should return post (158ms)
    users
      ✓ should return user (89ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        3.088s
Ran all test suites related to changed files.

Watch Usage
 › Press a to run all tests.
 › Press f to run only failed tests.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press q to quit watch mode.
 › Press Enter to trigger a test run.
</details>

**Comment by offirgolan** [comment]
> You can see that logging shows `Recording`, but nothing is persisted to the filesystem!

You need to make sure you call `await polly.stop()` for it to persister the recorded requests to the fs.

**Comment by ericclemmons** [comment]
I'll give it a shot.

I'm curious why flush doesn't do that as well?

(I'll be starting it up again right after the files are persisted)

**Comment by ericclemmons** [comment]
And sure enough, the docs have a callout for this:
https://netflix.github.io/pollyjs/#/api?id=stop-1

> This method is async and will resolve once all recordings have persisted and the instance has successfully torn down.

I naively assumed that recordings were written as they came in.
