### ISSUE TITLE
Question: Is there a way to exclude headers from being recorded?

### ISSUE THREAD

**Issue by cameck** [Netflix/pollyjs#175]
I see there are a few ways to exclude specific headers from requesting matching e.g.
```js
    matchRequestsBy: {
      headers(headers) {
        delete headers['auth-token'];
        return headers;
      }
    }
    // OR
    matchRequestsBy: {
      headers: {
        exclude: ['auth-token']
      }
    }
```

I'm wondering if there is a way to tell Polly not to record excluded headers?

**Comment by offirgolan** [comment]
Are you trying to remove request or response headers? or both?

**Comment by cameck** [comment]
Both if possible

**Comment by offirgolan** [comment]
You have a few options:

- Use the `request` & `beforeResponse` events to remove the headers from the request/response before they are sent out or received
- Use the `beforePersist` event to remove it from the will-be persisted recording so that next time it's replayed, the headers will no longer be sent.

```js
const { server } = polly;

server.any().on('request', req => {
  req.setHeader('auth-token', ''); // falsey values will remove the header completely
});
```

**Comment by cameck** [comment]
`beforePersist` sounds like what I need. Thanks so much, I'm going to go play with this now.

**Comment by cameck** [comment]
Not sure if this is the best way to do it, but I got it working like so:
```js
    const { server } = polly;
    server.any().on('beforePersist', (req, recording) => {
      recording.request.headers = recording.request.headers.map(header => {
        if (header.name === 'auth-token') {
          header.value = [''];
        }
        return header;
      });
    });
```

Thanks 🙌 !

**Comment by offirgolan** [comment]
Np! Setting it to an empty string will still send the header in the next release (see #176). I would suggest removing the header from the array entirely.

```js
recording.request.headers = recording.request.headers.filter(({ name }) => name !== 'auth-token'));
```
