### ISSUE TITLE
Need info to be logged when record not found

### ISSUE THREAD

**Issue by mrednic** [Netflix/pollyjs#181]
Hello guys,
Pollyjs is throwing an error when a record is not found. In my use case it's not enough.

I am using pollyjs to record and replay requests in an application. In the application I have a general mechanism to catch all the errors and this is capturing also the errors thrown when the record is not found which is the expected behavior.
The pollyjs instance is created on a separate app used only to monitor the requests. So the problem is here, because I want to log an info message when a record is not found. For the request which are found I can listen to the 'beforeReplay' event so I can log the information. 
Would it be possible to emit also a message when a record is not found in the 'beforeReplay' event (For the moment 'beforeReplay' emits only when a recordingEntry is found)? 
Or, is there other possible solution to be able to get an information when the record is not found (other than the error which is thrown) ?

**Comment by offirgolan** [comment]
@mrednic I've been thinking a bit about this. The solution I came up with would be something like this:

```js
const { server } = polly;

server.any().on('error', (req, error) => {
  console.error(error);
  process.exit(1);
});
```

I have an implementation of it that is almost complete, just need to fully test it out 😄

**Comment by mrednic** [comment]
@offirgolan Thank you for your investigation. The solution listed above will be exactly what I need to cover the use case.
