### ISSUE TITLE
Support binary response data in XHR & Fetch adapters

### ISSUE THREAD

**Issue by offirgolan** [Netflix/pollyjs#183]
Properly support recording and responding with received binary data in the XHR and Fetch adapters.

**Comment by badsyntax** [comment]
I'm not sure this helps at all, maybe it's helpful for others, but i'm able to work with binary requests with `@pollyjs/core@^1.4.1` and `@pollyjs/adapter-fetch@1.2.0`.

**Comment by offirgolan** [comment]
@badsyntax binary requests or responses?

**Comment by badsyntax** [comment]
@offirgolan The following works with the versions i've mentioned (ignoring the `cy.fixture` part, this is part of Cypress, and it's just a helper to get contents of a fixture file):

```javascript
cy.fixture('writeApiResponse.bin').then(fixture => {
  pollyServer.post('http://127.0.0.1:3000/binary').intercept((_, res) => {
    res.setHeader('Content-Type', 'application/x-protobuf');
    res.send(fixture);
  });
});
```

With `@pollyjs/core@^2.3.0` and `@pollyjs/adapter-fetch@^2.3.1`, an error is thrown on the following line:

```javascript
pollyServer.post('http://127.0.0.1:3000/binary').intercept((_, res) => {
```

The error is: 

```javascript
Uncaught (in promise) TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
```

**Comment by offirgolan** [comment]
@badsyntax this issue is in regards to adding proper support for binary responses from a server, not the intercept method (e.g. recording an image from the server).

Would you mind creating a separate issue with your previous comment so we can properly track it? If you can also include an example of what `fixture` is, that would be super useful.

**Comment by badsyntax** [comment]
I got the impression it was related. I'll create a seperate ticket.

**Comment by badsyntax** [comment]
Hi @offirgolan After spending some time getting a proper test case together to demonstrate this, i've realised that the error I mentioned is a result of using Polly.js within Cypress. The error originates form Polly code but could be due to something Cypress is doing. I'm unable to generate the error outside of Cypress. Really sorry for highjacking this issue. Would you still find it useful for me to get a test repo together (that uses Cypress) to replicate the error?

**Comment by offirgolan** [comment]
> Would you still find it useful for me to get a test repo together (that uses Cypress) to replicate the error?

Yeah, I'm starting to work a bit more with cypress and would love a reproduction to play around in. If you can create a new issue with it that would be great!

**Comment by Armenuhi-Qocharyan** [comment]
@offirgolan Is there any dateline for adding the support?

**Comment by offirgolan** [comment]
No timeline as of right now. I'll see if I can try to tackle this in the next few weeks. PR is always welcomed 😄
