### ISSUE TITLE
passthrough localhost

### ISSUE THREAD

**Issue by ludbek** [Netflix/pollyjs#186]
Is there a way to passthrough requests to localhost?

I am not being able to catch requests to localhost.

```javascript
server.any().on('request', (req, res) => {
      // it reaches here
      throw new Error('------> here')
});

server.any('http://127.0.0.1*path').on('request', (req, res) => {
      // it never reaches here
      throw new Error('------> here')
});
```

Hence I cannot do `server.any('http://127.0.0.1*path').passthrough()`

**Comment by offirgolan** [comment]
@ludbek can you also provide the polly config that you're using?

**Comment by offirgolan** [comment]
Also, can you try the following and see if that works out for you:

```js

server.any('http://127.0.0.1/*path').on('request', (req, res) => {
      // it never reaches here
      throw new Error('------> here')
});
```

**Comment by ludbek** [comment]
It does not work.

Here is the config I am using.

```javascript
    Polly.register(NodeHttpAdapter);
    Polly.register(FSPersister);

    polly = new Polly('paypal api', {
      persister: 'fs',
      adapters: ['node-http'],
      recordFailedRequests: true,
    });

```

**Comment by offirgolan** [comment]
Ah, can you try adding the port? The way you have it setup, it will match: `http://127.0.0.1/auth/login`

```js
server.any('http://127.0.0.1:37889/*path').on('request', (req, res) => {
      // it never reaches here
      throw new Error('------> here')
});
```

**Comment by ludbek** [comment]
I am using `supertest` and I believe the port is generated randomly.

I was hopping `http://127.0.0.1*path` would match the port too.

Alternatively is there a way to tell `Polly` to record requests to specific host or api?

**Comment by offirgolan** [comment]
> I am using `supertest` and I believe the port is generated randomly.

Hmmm, looking at the codebase, you should be able to access the full url used by supertest. See [here](https://github.com/visionmedia/supertest/blob/1792d7d91e276362c48c09fee1781f246a21605b/lib/test.js#L34).


```js
const req = request(app);

// You might have to play around with the final url here to make sure it fits your needs
server.any(`${req.url}/*path`).on('request', (req, res) => {
      throw new Error('------> here')
});
```

> Alternatively is there a way to tell `Polly` to record requests to specific host or api?

Yup! You should be able to do it like this:

```js
server.any().passthrough(); // Pass-through all requests so they wont get recorded/replayed
server.any('http://example.com').passthrough(false); // Override the pass-through set for the specific host
```

**Comment by ludbek** [comment]
Works like a charm. Thanks for helping out.

**Comment by offirgolan** [comment]
No problem 😄!

**Comment by claudijo** [comment]
An alternative to:
```
server.any().passthrough(); // Pass-through all requests so they wont get recorded/replayed
server.any('http://example.com').passthrough(false); // Override the pass-through set for the specific host
```

as described by @offirgolan, if you want to only passthrough requests to 127.0.0.1 with an arbitrary port number and not having to worry about keeping track of what requests you don't want to passthrough, would be to use [`server.filter()`](https://netflix.github.io/pollyjs/#/server/route-handler?id=filter) eg:
```
 server
      .any()
      .filter(req => /^127.0.0.1:[0-9]+$/.test(req.headers.host))
      .passthrough();
