### ISSUE TITLE
Request: DefinitelyTyped Typings for @pollyjs/node-server

### ISSUE THREAD

**Issue by NikhilVerma** [Netflix/pollyjs#188]
## Description

PollyJS is missing typings for @pollyjs/node-server. Can we please have them so that any custom Node servers can be typed as well?

I've already checked https://github.com/Netflix/pollyjs/issues/129 and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30574 however they didn't include typings for the server.

Thanks! ❤️

**Comment by offirgolan** [comment]
PR submitted to DefinitelyTyped (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38597)

**Comment by jasonmit** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38597#issuecomment-535185162

Has been released and versioned, thanks  @offirgolan  :)
