### ISSUE TITLE
Jest Support?

### ISSUE THREAD

**Issue by yarivkenan** [Netflix/pollyjs#19]
Hi looks like a great project, can I use it with Jest?

**Comment by enesTufekci** [comment]
@yarivkenan Why not? Have you tried it yet?

**Comment by yarivkenan** [comment]
I'll try and get back to you.

**Comment by RemeJuan** [comment]
Jest is for unit testing, not Journey testing, which is where this would come in handy.

**Comment by webstercharly** [comment]
@RemeJuan Jest is a test runner, it is not solely limited to Unit testing, it can be used for any level of the pyramid.

I actually came here looking to see compatibility for a project which is using Jest with Puppeteer.

**Comment by klarkc** [comment]
Actuallly I am refactoring a jest suite for everything (e2e, unit, integration), I will do some try with pollyjs in replace of supertest and nock. If I can replace both, it will be a double win

**Comment by harunurhan** [comment]
@webstercharly that is exactly what I am trying to do and I bumped into #41

**Comment by webstercharly** [comment]
@harunurhan yep exactly the same as me. Couldn’t solve it so I ended up intercepting the requests, using regex on url and then returning request with my json.

Shame, would have loved to use polly and not implement my own

**Comment by harunurhan** [comment]
@webstercharly Ok, I guess I'll have to keep my custom solution too.

**Comment by offirgolan** [comment]
As of right now, Polly is a client side library (meaning it will only run in the browser) but we are working towards an isomorphic solution!

I'll be working on this in the next few weeks to hopefully find an interim solution to Jest. I'll update this thread when I make some headway.

**Comment by harunurhan** [comment]
Probably It doesn't work for jest running on puppeteer environment.

Have you tried it already @webstercharly ?

**Comment by offirgolan** [comment]
@harunurhan can you clarify as to what you mean by "jest running on puppeteer environment"? Are you talking about just running Puppeteer and testing with Jest (as documented [here](https://jestjs.io/docs/en/puppeteer)) or with something like [jest-environment-puppeteer](https://www.npmjs.com/package/jest-environment-puppeteer)?

**Comment by webstercharly** [comment]
Using Jest as a runner and Jests assertion library, with the specs initialising and executing puppeteer commands.

I have a setup using Jest environment package.

I didn’t give it a try yet, don’t need it anymore but would like to @harunurhan

**Comment by harunurhan** [comment]
@offirgolan Sorry for the confusion, my setup is similar to the first one (`jest-puppeteer`).

**Comment by offirgolan** [comment]
@harunurhan no worries at all, thanks for the clarification. 

The next release will have full support for Jest using JSDom as well as Puppeteer. I just need to finish writing up some tests before we release.

**Comment by offirgolan** [comment]
v1.0.0 has been released which includes everything needed to support Jest + JSDom or Puppeteer! Im gonna go ahead and close this issue. If any of you find more specific issues regarding Jest/JSDom/Puppeteer, please open a new issue.

**Comment by yarivkenan** [comment]
let me just put that here https://github.com/smooth-code/jest-puppeteer.
