### ISSUE TITLE
Headers are not being recorded or sent correctly

### ISSUE THREAD

**Issue by filipeamoreira** [Netflix/pollyjs#190]
## Description

When using the `fetch` adapter and the `rest` persister, headers don't seem to be persisted correctly. More specifically the persisted HAR file looks like this:
```json
"headers": [
{
  "_fromType": "array",
  "name": "0",
  "value": "Content-type"
},
{
  "_fromType": "array",
  "name": "0",
  "value": "application/json"
}
],
```

When this request is replayed, the headers are set like this:

<img width="954" alt="20190305_headers" src="https://user-images.githubusercontent.com/8424/53821407-a4c2fe00-3f65-11e9-9403-5954390494c3.png">

Therefore, both values (i.e. `Content-Type` and `application/json`) are collapsed into one.

### Config

Copy the config used to setup the Polly instance:

```js
let context = setupPolly({
    logging: true,

    // If a request's recording is not found, pass-through to
    // the server and record the response
    recordIfMissing: true,
    recordFailedRequests: true,

    // "record" mode only records requests, but doesn't replay them
    // mode: 'record',

    // Default mode, can be omitted
    mode: 'replay',

    adapters: ['fetch'],

    persister: 'rest',
    persisterOptions: {
      rest: {
        // Default host, can be omitted
        host: 'http://localhost:3000',
      }
    },
  });
```

### Dependencies

Copy the @pollyjs dependencies from `package.json`:

```json
{
    "@pollyjs/adapter-fetch": "^2.3.0",
    "@pollyjs/adapter-node-http": "^2.3.0",
    "@pollyjs/cli": "^2.1.0",
    "@pollyjs/core": "^2.3.0",
    "@pollyjs/persister-fs": "^2.1.0",
    "@pollyjs/persister-rest": "^2.1.0",
}
```

## Relevant Links

I have a minimal reproducible repo here: https://github.com/filipeamoreira/karma-nock/tree/pollyjs-integration.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js and npm/yarn. If applicable, include the browser and the corresponding version.

Run the following to get it quickly:

```
Node.js v11.7.0
darwin 18.2.0
npm 6.5.0
```

**Comment by offirgolan** [comment]
Thanks for the detailed issue as well as the reproduction @filipeamoreira. I was able to find the culprit and will publish a fix hopefully in the next few hours.

**Comment by filipeamoreira** [comment]
Thank you @offirgolan for the quick turn around on the fix.
