### ISSUE TITLE
Headless chrome always rerecords requests

### ISSUE THREAD

**Issue by kennydp** [Netflix/pollyjs#195]
## Description

I have an issue when recording requests on a browser and then running tests in another browser. My requests get replayed correctly and consistently as long as I'm in the same browser. Not sure if that is the actual issue or if I'm drawing the wrong conclusion. The use case I have is I record my requests while running tests in the browser (I need to be logged in so that makes it a little easier). I have a testing pipeline setup with headless chrome, and it always tries to record the requests again in the pipeline. Same issue when I use it locally with `ember test`. I could not find any explanation for this in the docs. I've been trying out different `matchRequestBy` configuration with little success.

### Config

Copy the config used to setup the Polly instance:

```js
new Polly(recordingName, {
    adapters: ['xhr'],
    persister: 'rest',
    persisterOptions: {
      keepUnusedRequests: true
    },
    recordIfMissing: true,
    recordIfExpired: false,
    recordFailedRequests: false,
    matchRequestsBy: {
      method: true,
      headers: false,
      body: false,
      order: true,
      url: {
        protocol: false,
        username: false,
        password: false,
        hostname: false,
        port: false,
        pathname: true,
        query: true,
        hash: false
      }
    }
  });
```

### Dependencies

Copy the @pollyjs dependencies from `package.json`:

```json
{
    "@pollyjs/adapter-xhr": "^1.2.0",
    "@pollyjs/core": "^1.2.0",
    "@pollyjs/persister-rest": "^1.2.0",
}
```

## Environment

macOS Mojave 10.14
Node: 11.12.0 
npm: 6.7.0

**Comment by jasonmit** [comment]
It seems you're on an older version, have you tried upgrading?  If so, between recordings can you share what has actually changed within the har file? (i.e., `git diff`)

**Comment by kennydp** [comment]
Seems like updating to the latest version did the trick. Thanks for pointing that out 👍
