### ISSUE TITLE
Package pollyjs for Debian repositories?

### ISSUE THREAD

**Issue by utkarsh2102** [Netflix/pollyjs#198]
Debian ships over 50k packages and is one of the widely used operating system.  
I believe, it would be wonderful to package pollyjs for Debian repositories so that it is also `apt install` away :)

**Comment by jasonmit** [comment]
I don't see the value in managing/shipping a debian package

If using Pollyjs then you probably have node installed and if you have node installed then you have npm installed and can `npm i -g @pollyjs/core`.
