### ISSUE TITLE
Custom Adapter configuration documentation suggestion

### ISSUE THREAD

**Issue by indieisaconcept** [Netflix/pollyjs#20]
Hi pollyjs team,

Thanks for sharing.

I had to dive into pollys internals to understand how best to register a custom adapter as its not immediately clear from the documentation. 

Whilst configuring the default adapters is mentioned there is no example to illustrate registering your own.

For reference something like below could be really useful under the `configuration.Adapters` section.

```
{
  adapters: [
    ['<myCustomAdapterName>', myCustomAdapter],
  ],
}
```

Cheers,

Jon

**Comment by offirgolan** [comment]
@indieisaconcept thanks for opening up this issue! I'll make sure to add that to the docs.

Out of curiosity, what are your use cases for rolling out your own adapter?

**Comment by indieisaconcept** [comment]
@offirgolan thanks. The use case I have is for supporting supporting Node. I've written an adapter which can be used to provide compatibility with its native http/https modules.

Related to this I've also just submitted another issue. https://github.com/Netflix/pollyjs/issues/21
