### ISSUE TITLE
How to record only external requests?

### ISSUE THREAD

**Issue by marat-chardymov** [Netflix/pollyjs#203]
I'm trying to use pollyjs to test express js endpoint. It works fine until record is persisted to file. After that it just skips actual app code, so that test becomes always green. I assume this is because localhost(127.0.0.1) request/response is being intercepted by polly. Is it possible to record only external requests to prevent this? 

**app.js**:
```javascript
router.get('/widgets', async (req, res) => {
  //some external remote calls
}
```
**polly_config.js**:
```js
module.exports = {
  adapters: ['node-http'],
  persister: 'fs',
  persisterOptions: {
    fs: {
      recordingsDir: `${__dirname}/http_recordings`,
    },
  },
  recordFailedRequests: true,
  recordIfMissing: false,
  matchRequestsBy: {
    headers: false,
  },
};
```
**app.spec.js**:
```js
const chai = require('chai');
const { expect } = chai;
const chaiHttp = require('chai-http');
chai.use(chaiHttp);

const { Polly } = require('@pollyjs/core');
const NodeHttpAdapter = require('@pollyjs/adapter-node-http');
const FSPersister = require('@pollyjs/persister-fs');
const pollyConfig = require('./polly_config');

Polly.register(NodeHttpAdapter);
Polly.register(FSPersister);

describe('app', () => {
  const testPort = 3001;
  before(() => {
    app.listen(testPort);
  });

  describe('GET widgets', () => {
    it('returns widgets requested', async () => {
      const polly = new Polly('get_widgets', pollyConfig);

      const response = await chai.request(`http://127.0.0.1:${testPort}`)                                           
                                 .get(`/widgets`)
      expect(response).to.have.status(200);

      await polly.stop();
    });
  });
```

**Comment by offirgolan** [comment]
@marat-chardymov I'm not entirely sure what you're trying to achieve here.

> It works fine until record is persisted to file. After that it just skips actual app code

Thats what Polly does. It records the response if it doesnt have it on disk and the 2nd time you run your test, it will use the recorded response instead of making another request (or reaching your route app code).

**Comment by marat-chardymov** [comment]
I mean no code inside express callback will be executed after polly created har file
```javascript
router.get('/widgets', async (req, res) => {
  res.sendStatus(500); //this won't be executed  
}
```
So if I change logic inside router callback and start returning say 500 code, test will remain green. In VCR gem for example I can exclude localhost requests using https://www.rubydoc.info/github/vcr/vcr/VCR%2FConfiguration:ignore_request option

**Comment by offirgolan** [comment]
You can exclude any host or path via the provided [client-side server](https://netflix.github.io/pollyjs/#/server/overview) on the polly instance. 

```js
const { server } = polly;

server.any(`http://127.0.0.1:${testPort}/*`).passthrough();

const response = /* ... */
```

**Comment by marat-chardymov** [comment]
It worked, thank you @offirgolan . But can I apply passthrough for localhost requests globally, for any Polly instance? Currently I got one Polly instance per har file(cassette):
```js
  describe.only('GET widgets', () => {
    it('returns widgets requested', async () => {
      const polly = new Polly('get_widgets', { ...pollyConfig, ...{ recordIfMissing: false } });
      // localhost request
      await polly.stop();
    });
  });

  describe('POST /widgets', () => {
    it('returns created widget', async () => {
      const polly = new Polly('create_widget', { ...pollyConfig, ...{ recordIfMissing: false } });
      // localhost request
      await polly.stop();
    });
  });

  describe('DELETE /widgets/:id', () => {
    it('returns 204', async () => {
      const polly = new Polly('delete_widget', { ...pollyConfig, ...{ recordIfMissing: false } });
      // localhost request
      await polly.stop();
    });
  });
```

**Comment by offirgolan** [comment]
If you're using mocha, I highly recommend using the [`setupMocha` test helper](https://netflix.github.io/pollyjs/#/test-frameworks/mocha).

```js
import { setupMocha as setupPolly } from '@pollyjs/core';

describe('app', function() {
  const testPort = 3001;

  before(() => {
    app.listen(testPort);
  });

  setupPolly({ ...pollyConfig });

  beforeEach(function() {
    const { server } = this.polly;

    server.any(`http://127.0.0.1:${testPort}/*`).passthrough();
  });

  describe('GET widgets', () => {
    it('returns widgets requested', async () => {
      const response = await chai.request(`http://127.0.0.1:${testPort}`).get(`/widgets`)
      expect(response).to.have.status(200);
    });
  });
});
```

**Comment by marat-chardymov** [comment]
small note: seems that `setupMocha` requires to use `async function()` definition for tests instead of arrow functions `()=>`, since **setupPolly** relies on `this` context which in undefined inside arrow function? I know its kind of unrelated to the initial issue but folders generated by `setupMocha` look strange when `describe` text contains colons:
```js
describe('GET /widgets/:id', function() {
  it('returns widget requested', async function() {
    //some test code 
  }
}
```
![image](https://user-images.githubusercontent.com/3954737/56689792-eccee900-66a9-11e9-9031-a59c8d4e88b2.png)

**Comment by offirgolan** [comment]
Correct. I'm gonna go ahead and close this issue. Feel free to reopen or create a new one if you have any more questions.
