### ISSUE TITLE
Support `context` option on the XHR Adapter

### ISSUE THREAD

**Issue by offirgolan** [Netflix/pollyjs#204]
Add support for mocking the XHR global on a given context (like we currently support with the fetch adapter).

```js
{
  adapterOptions: { 
    xhr: { context: win }
  }
}
```

**Comment by offirgolan** [comment]
Blocked by sinonjs/nise#84.

**Comment by freewind** [comment]
https://github.com/sinonjs/nise/pull/84 is merged
