### ISSUE TITLE
Allow renaming of recording.har file

### ISSUE THREAD

**Issue by ericbiewener** [Netflix/pollyjs#206]
Rather than generating a directory named with the [`recordingName`](https://netflix.github.io/pollyjs/#/api?id=recordingname) and then a `recording.har` file inside that, I'd prefer to just have the `recording.har` file named with `recordingName`, thus removing the additional directory depth.

**Comment by offirgolan** [comment]
Do you have any specific reason as to why besides personal preference?

**Comment by ericbiewener** [comment]
Nope! Obviously not a critical feature request :)

**Comment by offirgolan** [comment]
This isn't something that we plan to support out of the box but can be done fairly easily by extending the current FS Persister which is public API.
