### ISSUE TITLE
Only able to record requests made to Selenium - no network requests made in browser are recorded

### ISSUE THREAD

**Issue by jackson-sandland** [Netflix/pollyjs#209]
I'm using `Polly` with `webdriverIO, mocha, and chai`.

I'm able to record the network requests to selenium but I thought I'd be able to record all of the requests made when my test runs. 

**Here is the code:** 
```
import chai from "chai";
import { assert, expect } from "chai";
import chaiWebdriver from "chai-webdriverio";
chai.use(chaiWebdriver(browser));

import { Polly } from "@pollyjs/core";
import NodeHTTP from "@pollyjs/adapter-node-http";
import FSPersister from "@pollyjs/persister-fs";

Polly.register(NodeHTTP);
Polly.register(FSPersister);

describe("setup polly", () => {
  const baseUrl = browser.config.baseUrl;
  describe("init", () => {
    const polly = new Polly("Test", pollyConfig);
    const { server } = polly;

    beforeEach(() => {
      browser.navigateTo(baseUrl);
      server.any().on("request", (req, res) => {
        console.log("request", req)
        req.headers["X-Auth-Token"] = "test123";
      });
    })

    afterEach(() => {
      polly.stop();
    })

    it("should test", () => {
      // test here
    });

  });
});
```

**This is my polly config**:
```
module.exports = {
  adapters: ["node-http"],
  persister: "fs",
  logging: true,
  persisterOptions: {
    fs: {
      recordingsDir: "./http_recordings",
    },
  },
  recordFailedRequests: true,
  recordIfMissing: true,
  matchRequestsBy: {
    headers: false,
  },
};
```

**I can see the output in the specified directory but the only requests are to**: `http://127.0.0.1:4444/wd/hub/session/d462c68163ebc4c09526a3f924a81f0c/url`

When I inspect the browser I can see tons of network requests - but none are recorded by Polly. 

**Am I misinterpreting how Polly works - or is it possible to see all the requests that are being made when the browser is opened by webdriverIO**?

**Comment by jasonmit** [comment]
I'm not familiar with this setup but I think that there are two different contexts here: one is your test runner and the other is `browser`.  In order for this to work, you'll need some way of injecting Polly into `browser` and also be able to communicate with that instance of Polly from within your test context.

**Comment by codebu5ter** [comment]
@jackson-sandland Were you able to figure out how to make this work?
I'm also encountering a similar issue, where all the Selenium requests are being recorded, but not the browser network calls.
