### ISSUE TITLE
Custom Persister Support

### ISSUE THREAD

**Issue by indieisaconcept** [Netflix/pollyjs#21]
Hi pollyjs team,

I'd like to suggest adding support for specifying a custom persister in a similar fashion to adapters.

```
{
    persister: ['<myCustomPersisterName>', myCustomPersister],
}
```

I've managed to get this working and was wondering if you would be open to accepting a PR for this. 

It would require a minor change to `@pollyjs/core` to support registering custom persisters with the container and ideally `@pollyjs/core/src/persisters/persister` would be promoted to its own package so that it is more accessible i.e `@pollyjs/persister` similar to adapters.

```javascript
const persisterConfig = this.config.persister;
let persisterName = persisterConfig;

if(isArray(persisterConfig)) {
    const [, PersisterType] = persisterConfig;
    persisterName = persisterConfig[0];
    this._container.set(`persister:${persisterName}`, PersisterType);
}

this.persister = new (this._container.get(
  `persister:${persisterName}`
))(this);
```

The context for this suggestion is that with these minor changes its possible for `pollyjs` to support recording within Node directly meaning I can use `pollyjs` for both my client & server tests.

I've this working end-to-end and plan on polishing it further.

Cheers,

Jon

**Comment by jasonmit** [comment]
> I've managed to get this working and was wondering if you would be open to accepting a PR for this.

> It would require a minor change to @pollyjs/core to support registering custom persisters with the container and ideally @pollyjs/core/src/persisters/persister would be promoted to its own package so that it is more accessible i.e @pollyjs/persister similar to adapters.

Absolutely!  Would appreciate this contribution.
