### ISSUE TITLE
Clarification on use of Local Storage

### ISSUE THREAD

**Issue by tombh** [Netflix/pollyjs#219]
In the docs section [Using Polly In The Browser](https://netflix.github.io/pollyjs/#/quick-start?id=using-polly-in-the-browser) it suggests that Local Storage is an alternative option to using the Rest persister. The implication seems to be that a browser's local storage can replace all the functionality of the Rest persister, however my immediate reaction to that is that HARs stored in the browser cannot be committed to my repo and subsequently replayed in CI. Am I missing something here? I assume the Local Storage persister is more for working offline, not for building CI tests?

In starting to read that paragraph I knew I'd found the right option for my use case, but by the end I was left in confusion. Could there be a simple amendment to help clarify?

**Comment by jasonmit** [comment]
Correct.  The local storage is primarily for local, offline, support.

It's definitely not intended to replace the use cases of the rest or fs persisters.  If there's language throwing you off in the docs, please send a PR our way to correct it 🙏
