### ISSUE TITLE
Mock GraphQL responses

### ISSUE THREAD

**Issue by iyubinest** [Netflix/pollyjs#222]
Is there any configuration needed for mocking GraphQL responses on React Native? 
`fetch` is working well when recording, but Apollo client apparently does not work.

**Comment by offirgolan** [comment]
We use Polly to intercept and mock GraphQL from both the browser (via fetch) and node (via node-http) with no additional configuration needed. 

If the Apollo client is making its requests via `fetch`, then you might be initializing the Polly instance too late. Apollo might be keeping a reference to the original fetch method before Polly has a chance to replace it. Try moving the creation of the Polly instance before the apollo client gets initialized.

**Comment by iyubinest** [comment]
Thank you so much that did the work!

**Comment by mikey-eola** [comment]
Hi @go-cristian & @offirgolan 👋 

I was hoping you might be able to offer some insight as to how you were able to get Polly to intercept the fetch requests from the Apollo client? In tests I'm wrapping the component in apollo's `MockedProvider` and rendering it using `@testing-library/react`, but I'm unsure how to get Polly in there.

```tsx
//imports & Polly.register()
describe('<TestComponent />', () => {
  const polly = new Polly('TestComponent', {
    adapters: ['fetch'],
    persister: 'fs',
    persisterOptions: {
      fs: {
        recordingsDir: '../__recordings__'
      }
    },
    recordIfMissing: true
  })

  it('renders', async () => {
    render(
      <MockedProvider>
        <OutletDirectory />
      </MockedProvider>
    )
  })

  polly.stop()
})
```

I saw in #199 I need to pass Polly a `context` that has `fetch` as a member. If you don't mind sharing, how did you do it?

**Comment by offirgolan** [comment]
I believe the latest version of the MockedProvider from apollo no longer makes any network calls. From my memory, it just errors if it can't find a request that was defined via the `mocks` prop.
