### ISSUE TITLE
feature: Allow Polly throwing an error if recording is expired

### ISSUE THREAD

**Issue by sankaritan** [Netflix/pollyjs#226]
## Feature proposal: Allow configuring Polly to fail if recordings are expired.

We have successfully migrated a few of our projects to Polly - and it worked great so far! One feature we're currently missing is the ability to fail the test in case the recordings get out of date.

The current logic allows to either keep using expired mocks or re-record them when expired.
While this is usually satisfactory, it doesn't suit well our situation. Imagine:

1. The engineer starts working on a new feature and pushes changes to git without running tests. Ideally, this should never happen (pre-commit hook won't even let you!), but reality can differ, project from the project.
1. If recordings are out of date, they may be re-recorded on CI, but those updates would not be preserved in the source code. This can lead to a situation when recordings (contracts) slowly get out of date.

In order to be able to automatically enforce updating recordings as a hard rule before merging, I'd like to propose the following:

**A)** Introduce a new config option: `failIfExpired`, set to `false` by default. Call `this.asset("error text")` whenever recording is expired & the value of `failIfExpired` is set to `true`.

**B)** An alternative could be smth like `expiryMode` or `expiryStrategy` that would allow user to choose from multiple options:
- replay
- rerecord
- failure

Happy to make a PR if this sounds like something that would fit into Pollyjs roadmap!

**Comment by offirgolan** [comment]
Thanks for opening up this issue @sankaritan! This enhancement makes a lot of sense and should be super easy to add. A PR would be greatly appreciated 😄.

For the sake of simplicity and backwards compatibility, I say we go with option **A**.

@jasonmit thoughts?

**Comment by jasonmit** [comment]
I'm in favor but I'd prefer an event this way folks can choose how to implement it (throw, log, instrument, etc.)

**Comment by jasonmit** [comment]
@sankaritan chatted with Offir we've aligned around `expiryStrategy`.

It will simplify the config and encapsulates two config options into one and eliminates confusion (i.e., `failIfExpired` is true and `recordIfMissing` is true).

I also believe we can achieve this in a backwards compatible way if we deprecate `recordIfMissing` and our config logic is updated to use the new strategy prop.

**Comment by offirgolan** [comment]
Resolved in #227.
