### ISSUE TITLE
running polly test suite (yarn test) uses a lot of CPU 

### ISSUE THREAD

**Issue by agraves** [Netflix/pollyjs#232]
# Description

I've noticed that running `yarn test` is slow and uses a lot of CPU, making it difficult to run tests in a tight loop when TDDing. As configured, the testem suite runs a full `yarn test:clean` followed by a `yarn build test:build` for each of the submodules in the monorepo.

I've got a '17 mbp, and just running `$ yarn test` puts my load over 200 for a solid couple minutes. I also made the mistake of mashing enter a few times in the testem ui, which wound up kicking off 143 yarn processes making my machine beachball until I gave up. This load is almost entirely due to running a full build and clean before each suite run.

While fully saturating the machine's resources may make sense in e.g. a CI environment, it took us a bit of investigation to figure out how to avoid melting our machines, and we worry that it may be a bit of a deterrent to new contributors.

So, after a lot of investigation, we wound up with this workflow:

1. Comment out the `before_tests` and `on_start` entries in `testem.js`
2. Manually clean & launch the testem watcher (with logging and a single target): `yarn test:clean && yarn testem -d testem.log -l Node`
3. Then, in a second tab, we'd manually trigger the build: `yarn test:clean && ./node_modules/.bin/run-s build test:build`

At this point, we were able to modify tests and the watcher would quickly kick-off a re-run. I'm not sure exactly when it's necessary to re-run the build, but especially when TDDing existing code, we were able to run the tests in a tight loop.

We also seem to be able to just run the build command for a specific sub-module if we're modifying it.

Anyways, tl;dr decoupling the build and test run steps seems to be the difference between a really long and cpu-intensive wait and fairly instantaneous test results.

So —

1. So first, I'd like to know — do you guys encounter this problem? Or are you using a different workflow we're not aware of?
2. If we're not missing something, I'd propose that we document / set up a workflow that either depends on the developer to build as needed, or selectively watches and builds just the changed parts of the app.

I'd be happy to take a swing at either the manual or selective build workflows but thought it would be good to broach the discussion here first!

Thanks for reading 

### Config

I'm just checking out pollyjs' master and running the tests with the default config.

## Environment

OSX, yarn 1.17.3, node 10.16.0

**Comment by offirgolan** [comment]
@agraves thanks for opening up this issue! This is something i've been thinking about tackling for some time now and haven't been able to get around to it.

> So first, I'd like to know — do you guys encounter this problem? Or are you using a different workflow we're not aware of?

Yes, we encounter this problem 100% of the time as well and my workflow for testing is similar to the one you've come up with. I usually comment out parts of testem as well as modify the `mocha.opts` glob to only build the tests Im currently working on.  Not only does it make testing extremely slow, but also creates a pretty poor developer experience as you've mentioned.

> If we're not missing something, I'd propose that we document / set up a workflow that either depends on the developer to build as needed, or selectively watches and builds just the changed parts of the app.

Either of these options would be better than what we have now, thats for sure. Having a selective build would definitely be the ideal solution as it will reduce a lot of the initial overhead to get started with the project, but I'm not certain of the complexity nor the time it will take to get it working. 

If you're willing to take a swing at this, I'd leave the decision up to you. If it'll be too difficult and/or time consuming to get the selective build working, then we can start by setting up and documenting the workflow you've been using and improve on it later on.
