### ISSUE TITLE
[Question] How to run Polly Codeceptjs

### ISSUE THREAD

**Issue by vitaly87** [Netflix/pollyjs#238]
Hi all!
I am trying to run codeceptjs  (webdriverio) with polly, I am getting error with:

>   [Polly] [adapter:fetch] fetch global not found.
  
My code is:
```

const {
    Polly
} = require('@pollyjs/core');
 const FetchAdapter = require('@pollyjs/adapter-fetch')
 const XHRAdapter = require('@pollyjs/adapter-xhr')
 const RESTPersister = require('@pollyjs/persister-rest')
Polly.register(FetchAdapter);
Polly.register(XHRAdapter);
Polly.register(RESTPersister);

Before(async (I) => {
    // try {
        I.amOnPage("/");
         const polly = new Polly('Simple Example', {
             adapters: ['fetch'], // Hook into `fetch`
             persister: 'local-storage', // Read/write to/from local-storage
             logging: true // Log requests to console
         });
        await I.login();

```

I have one more question if I want to record the rest and change it like I want to change only one attribute in response how can I do it? If its not possible how I reuse the mocks ? where they will be saved ? 

thanks!

**Comment by jasonmit** [comment]
I have no experience with codeceptjs however I can tell that your issue is similar to https://github.com/Netflix/pollyjs/issues/209#issuecomment-493701496 since `fetch` is not being discovered in the context in which you are instantiating Polly.

At the highest level, you would want to instantiate Polly within the context the app is running in instead of the test runners.  If you have a handle from your test runner to the context of your browser you can leverage the this option to override that context:
https://netflix.github.io/pollyjs/#/configuration?id=adapteroptions

> I have one more question if I want to record the rest and change it like I want to change only one attribute in response how can I do it?

Here is an example of how you can achieve that.

```js
this.polly.server
  .get(''/api/persons/:id')
  .on('beforeResponse', (req, res) => {
    const body = {
      ...res.jsonBody(),
      name: 'Overridden name'
    };

    res.status(200).send(body);
  });
```

> If its not possible how I reuse the mocks ?

It is possible to reuse mocks, but it's not documented.  We'll need to update the documentation to include this. cc @offirgolan who was planning to update.

**Comment by vitaly87** [comment]
So you mean that all Polly init start stop should be from browser scope like 

  await I.executeScript(() => {
        Init Polly...
    });

That what you mean?

**Comment by jasonmit** [comment]
@vitaly87 that may likely do the trick.  I cannot say for certain since I do not know the testing framework you're using.

**Comment by vitaly87** [comment]
what I did is something like this:

`     const polly = new Polly('Simple Example', {
                  adapters: ['fetch'], // Hook into `fetch`
                  adapterOptions: {
                      fetch: {
                          context: I.returnWindow()
                      }
                  },
                  persister: 'local-storage', // Read/write to/from local-storage
                  logging: true // Log requests to console
              });`


where the return window 


```
    return  this.helpers['WebDriver'].executeScript(function () {
      return  window;
     });
```
``

the error 

```

  move target out of bounds: Blocked a frame with origin "https...." from accessing a cross-origin frame.
  (Session info: chrome)
  (Driver info: chromedriver=
```

**Comment by jasonmit** [comment]
It's hard to tell what is causing the CORs issue.  Can you share the full error msg without the stripped out URL `"https...."`?  Since you're using the local storage persister, and not the REST persister, I'm unsure what is making external requests from your application.

**Comment by vitaly87** [comment]
OK looks like what I was missing is to wait for window to be ready 
```

  var wind =await I.returnWindow();
              const polly = new Polly('Simple Example', {
                  adapters: ['fetch'], // Hook into `fetch`
                  adapterOptions: {
                      fetch: {
                          context: wind
                      }
                  },
                  persister: 'rest', // Read/write to/from local-storage
                  logging: true // Log requests to console
              });
```
 but now I am having this :


     [Polly] [adapter:fetch] fetch global not found.`

**Comment by jasonmit** [comment]
> [Polly] [adapter:fetch] fetch global not found.`

`wind.fetch` must then be undefined.

**Comment by vitaly87** [comment]
OK I did simply flow but now getting

> 
 Converting circular structure to JSON

My code looks like this

```

  async initPolly() {
    const polly = new Polly('<Recording Name>');
    return await this.helpers['WebDriver'].executeScript(async function (polly) {
  
      polly.configure({
        adapters: ['fetch'],
        adapterOptions: {
          fetch: {
            context: this
          }
        },
        persister: 'rest', // Read/write to/from local-storage
        logging: true // Log requests to console
      });
    }, polly);
  }
```

**Comment by jasonmit** [comment]
> OK I did simply flow but now getting

Can you repost, I think you left off a portion of the error msg.

**Comment by vitaly87** [comment]
do you have any working example from js code that I can run from console chrome in order to see if its working?

**Comment by vitaly87** [comment]
Finally I get it working , I download the pollyjs via cdn and did polly.server . All of this was done from excude script from chrome. You can't do it out of chrome scope .

**Comment by vitaly87** [comment]
Finally I get it working , I download the pollyjs via cdn and did polly.server . All of this was done from excude script from chrome. You can't do it out of chrome scope .
