### ISSUE TITLE
feature: recording expiration to respect timezones

### ISSUE THREAD

**Issue by sankaritan** [Netflix/pollyjs#241]
##  Description

The `startedDateTime` is a timestamp but does not include timezone information.
This could lead to potential problems with [expiration calculation](https://github.com/Netflix/pollyjs/blob/02a476716d67225195842fe7ef92fac6dc383041/packages/%40pollyjs/adapter/src/utils/is-expired.js#L7).

Example situation:

- User A records a network call in GMT -05:00
- `expiresIn` is set to e.g 3 days
- User B replays a network call in GMT +7:00, 2.5 days later

The request will expire since `startedDateTime` will be converted to the local timezone.

Another example would be running code with Polly on CI which hosts servers on a different timezone than your machine. This way you could get inconsistent results compared to localhost.

## Suggested solution

It would be good to save the timezone information into the `startedDateTime` in the har file (or any other persister format), so it can be parsed together with the timestamp & current time converted to the timezone of the recording for comparison to get consistent results regardless of the location.

**Comment by jasonmit** [comment]
@sankaritan seems like a reasonable ask & I'm happy to review any attempts to solve this.

**Comment by TheMelter** [comment]
@jasonmit @sankaritan 

Please correct me if I'm wrong, but it looks like the request timestamp - `startedDateTime` - is already being saved as UTC using `new Date().toISOString()`. Then in [is-expired.js](https://github.com/Netflix/pollyjs/blob/02a476716d67225195842fe7ef92fac6dc383041/packages/%40pollyjs/adapter/src/utils/is-expired.js#L7), this `recordedOn` timestamp with `expiresIn` is converted to local timezone and compared against local time. Happy to tackle the issue, but need more clarification.

**Comment by jasonmit** [comment]
@TheMelter if it's already stored in UTC then shouldn't be much more work.  I wrote that without verifying what the current behavior is.  Feel free to proceed 😄

**Comment by view-hyunmin** [comment]
@jasonmit since it's stored in UTC and timezone comparison is safe, the initial issue itself doesn't seem possible unless I'm missing something

**Comment by jasonmit** [comment]
@TheMelter interesting, so if stored in UTC and when read is converted to local time and the comparison is done in local time then is there a bug?  I'd love a fail test to better help me understand.

**Comment by jasonmit** [comment]
@sankaritan can you expand on this a bit more - maybe with a fail test or an explanation where the issue is?

**Comment by offirgolan** [comment]
@sankaritan following up on this issue. Do you have any more details you could provide?

**Comment by jasonmit** [comment]
Closing as it appears to have gone stale.

If it's still an issue in the future, please open a new issue instead of responding on closed issue.
