### ISSUE TITLE
[Question] Running Polly in Chrome console

### ISSUE THREAD

**Issue by AmitPLevy** [Netflix/pollyjs#247]
I am trying to run Polly in Chrome console.

I executed to following code- 

`const fetchUrls = ['https://cdn.jsdelivr.net/npm/@pollyjs/core@2.6.0/dist/umd/pollyjs-core.min.js',
        'https://cdn.jsdelivr.net/npm/@pollyjs/adapter-fetch@2.6.0/dist/umd/pollyjs-adapter-fetch.min.js',
        'https://cdn.jsdelivr.net/npm/@pollyjs/adapter-xhr@2.6.0/dist/umd/pollyjs-adapter-xhr.min.js',
        'https://cdn.jsdelivr.net/npm/@pollyjs/persister-rest@2.6.0/dist/umd/pollyjs-persister-rest.min.js'
      ]
      for (let i = 0; i < fetchUrls.length; i++) {
        let script = document.createElement('script');
        script.type = 'text/javascript';
        script.src = fetchUrls[i];
        document.getElementsByTagName('head')[0].appendChild(script);
      }

window.PollyJS = window['@pollyjs/core'];
      PollyJS.Polly.register(window['@pollyjs/persister-rest']);
      PollyJS.Polly.register(window['@pollyjs/adapter-fetch']);
      PollyJS.Polly.register(window['@pollyjs/adapter-xhr']);
      const polly = new PollyJS.Polly
      ('RecordingName', {
        adapters: ['xhr', 'fetch'],
        persister: 'rest'
      });`

But I get an error thrown every few seconds.

Is there an example for working code in the Chrome console?

Thank you.

**Comment by offirgolan** [comment]
This should work if you just replace the rest persister with the local storage one. I'm assuming you don't have a server setup to use the REST persister.

**Comment by AmitPLevy** [comment]
Thank you, now its working.
