### ISSUE TITLE
[Question] Reading the .har recording response body content

### ISSUE THREAD

**Issue by yaronassa** [Netflix/pollyjs#249]
I use pollyJS extensively, and from time to time I need to examine the previously recorded responses by themselves.
I have the persisted HAR files, and they contain everything as they should. However, the response body seems to be a hex buffer, that I cannot convert back to utf8 format.

I tried reading it as hex, base64, and piping it through zlib inflate for good measure, but I keep getting a non-utf8 unworkable content (same result when loading the HAR files to many HAR viewers).

How can the content be read?

Thanks.

**Comment by offirgolan** [comment]
If the response's body content is encoded, we store the chunks as an array of hex values. When replaying, we then convert each hex value back into a buffer and write it to a Readable Stream which will then be read by the consumer. 

Converting the array of hex strings back into buffer chunks:

https://github.com/Netflix/pollyjs/blob/5b4edf3702b3e3a1c4cbd0651de8f1e4b45bdd42/packages/%40pollyjs/adapter-node-http/src/index.js#L277-L283

Writing each chunk to the stream:

https://github.com/Netflix/pollyjs/blob/5b4edf3702b3e3a1c4cbd0651de8f1e4b45bdd42/packages/%40pollyjs/adapter-node-http/src/index.js#L212-L219

**Comment by yaronassa** [comment]
Thanks, after fiddling with it, the HAR response contented turned out to be a gzipped chunked hex array.
So with your help, I managed to get the original response by:

```javascript
import {Readable} from "stream";
import {createGunzip} from "zlib";
import {createWriteStream} from "fs";

const responseContent = ["The hex array copied from the HAR file"];

const chunks = responseContent.map(chunk => Buffer.from(chunk, 'hex'));

const contentStream = new Readable();

const zipMiddleware = createGunzip();
contentStream.pipe(zipMiddleware);

const output = createWriteStream('./output.json');
zipMiddleware.pipe(output);

chunks.forEach(chunk => contentStream.push(chunk));
contentStream.push(null);
```

Sorry it took me so long to implement your information - didn't have the time for it till now.
