### ISSUE TITLE
Import polly is failing

### ISSUE THREAD

**Issue by andrewcallahan** [Netflix/pollyjs#25]
I'm trying to use polly on Ember 3.1.4, but can't seem to get the import to work.

I installed it via `ember install @pollyjs/ember`, set the configuration, and then tried to import the module in an empty acceptance test file. However, the importing `import { setupQunit as setupPolly } from '@pollyjs/core';` is failing.

Here is the error message:
```
Source: 	
Error: Could not find module `@pollyjs/core` imported from `test-app/tests/acceptance/projects-test`
```

**Comment by andrewcallahan** [comment]
also, I've put up a fresh install ember app with polly - if you go to http://localhost:4200/tests you'll see the failure https://github.com/andrewcallahan/test-app

**Comment by jasonmit** [comment]
```js
  let app = new EmberApp(defaults, {
    pollyjs: {
      enabled: EmberApp.env() === 'test', // <-- the issue
      server: {
        apiNamespace: '/api/v1',
        recordingsDir: 'recordings'
      }
    }
  });
```

It's not necessary and EmberApp.env() is `development` when you're serving the app over port 4200.  If you truly want `EmberApp.env() === 'test'` then you need to run your tests via `ember test` and not `ember s`.

By default, @pollyjs/ember does not bundle polly when it's in production mode so providing `enabled` isn't needed.

**Comment by andrewcallahan** [comment]
@jasonmit Thank you so much for your prompt help fixing my "user error"  😂
