### ISSUE TITLE
HAR should have post-matchRequestsBy data

### ISSUE THREAD

**Issue by stephenh** [Netflix/pollyjs#251]
I'm using `matchRequestsBy` to take a token/secret out of recordings (so I can use the real-secret during record, but then use a fake-secret for checking-in + running-in-ci), i.e.:

```typescript
  matchRequestsBy: {
    body(body: string): string {
      return body.replace(/token=[a-z0-9-]+/, "token=...");
    },
  },
```

This does make the `_id` in the HAR file based on the "token=..." string (so I'm free to change the token between recording and replaying, and the hash/ID of the HAR entry still matches, so it works), but the recorded body still has the token value:

```
          "postData": {
            "mimeType": "application/x-www-form-urlencoded",
            "params": [],
            "text": "token=<token was still here>&channel=eng&text=New%20Estimator%20Lead%20-%20%3Arotating_light%3A"
          },
```

I can manually change the `token=<token was still here>` and change it to `token=...` but it'd be great if polly just saved the post-`matchRequestsBy` version. This would dramatically reduce the likelihood of our secret token being checked-in while doing re-records.

### Config

Copy the config used to setup the Polly instance:

```js
import path from "path";
import { Polly, PollyConfig } from "@pollyjs/core";

// @ts-ignore polly's typings aren't great but we don't really need them for this small init code
import { setupPolly } from "setup-polly-jest";
Polly.register(require("@pollyjs/adapter-node-http"));
Polly.register(require("@pollyjs/persister-fs"));

const config: PollyConfig = {
  adapters: ["node-http"],
  persister: "fs",
  persisterOptions: {
    fs: {
      recordingsDir: path.resolve(__dirname, "../tests/__recordings__"),
    },
  },
  matchRequestsBy: {
    body(body: string): string {
      return body.replace(/token=[a-z0-9-]+/, "token=...");
    },
  },
};

setupPolly(config);
```

**Comment by offirgolan** [comment]
You can use the [Request](https://netflix.github.io/pollyjs/#/server/events-and-middleware?id=request) event via the client-side server to modify the request before it gets sent to the server. 

If you want to send the actual token with the original request but emit it from the recording, you can use the [beforePersist](https://netflix.github.io/pollyjs/#/server/events-and-middleware?id=beforepersist) event to alter the actual recording data that will be saved.

**Comment by stephenh** [comment]
Ah okay...thanks! I got that working.

It would have been easier if `beforePersist` fired before the entry `id` was captured, b/c now I'm having to apply the "strip out tokens" logic in both the match methods (so the `_id` is calc'd right) + then again in the `beforePersist` hook:

https://gist.github.com/stephenh/1e3ec5a531fce3a53668cbef1ac81cbd

But it's not too bad.

**Comment by jasonmit** [comment]
> It would have been easier if beforePersist fired before the entry id was captured, b/c now I'm having to apply the "strip out tokens" logic in both the match methods (so the _id is calc'd right) + then again in the beforePersist hook

`beforePersist` is the very last event fired which allows users to do anything to the request/response payload - even making them unreadable to Polly (i.e., encryption).  So we cannot assume that after this hook is called that Polly would be able to do anything with either payloads.
