### ISSUE TITLE
Remove hash from recording names

### ISSUE THREAD

**Issue by stephenh** [Netflix/pollyjs#252]
It's not clear to me why a number/hash is added to the end of recording names, i.e. the har file is stored as `SuiteName-123456/test-name-123456/recording.har` instead of `SuiteName/test-name`.

Intuitively it seems like maybe this is supposed to avoid collisions, like if two different files use the same suite name & test-name, however that would require the id (the 123456 part) being some unique/stable value that was calc'd from something that wasn't the suite name / test name, i.e. maybe the file path.

However, again AFAICT the hash is actually based off the suite name/test-name:

https://github.com/Netflix/pollyjs/blob/02a476716d67225195842fe7ef92fac6dc383041/packages/%40pollyjs/core/src/utils/guid-for-recording.js#L9

So for duplicate/used-twice suite/test names, the hash is going to be deterministically the same for each of them anyway, so why include it?

(Fwiw I'm technically use `setup-polly-jest` and originally assumed it and/or Jest was responsible for injecting these numbers into the names, but I filed an issue in that project and the author pointed me to the ^ code and pointed out that it is polly itself that is introducing these hashes/numbers. (And also fwiw, if de-duplication was the intended purpose, it would actually make sense for `setup-polly-test` to be the one driving the numbers, because it would have information about the unique file-path each test suite was in.))

This is obviously just a cosmetic issue, but, dunno, if they're not doing anything, why have them?

Granted, need to keep them for backwards compatibility but an option to turn them off would be nice.

**Comment by offirgolan** [comment]
We postfix a hash of the original recording name because we strip out non alpha numeric characters as well as restrict the length of the final name used for each directory. 

This way, a recording name of AB would have a directory of AB_1234 but a recording name of A|B would have a directory of AB_5678.

**Comment by stephenh** [comment]
@offirgolan ah okay...that makes sense.

FWIW if the strip-non-alpha + chop-too-long is a no-op, i.e. there were no non-alpha chars and the length was okay, then the postfix is not necessary?

Understand this is a minor UX-if-that issue. Thanks for the response!

**Comment by jasonmit** [comment]
> FWIW if the strip-non-alpha + chop-too-long is a no-op, i.e. there were no non-alpha chars and the length was okay, then the postfix is not necessary?

Yes I believe it could conditionally work that way but might lead to a breaking change to introduce.

**Comment by stephenh** [comment]
Agreed; fine to close out as admittedly this is minor compared to the large breaking change for existing recordings.
