### ISSUE TITLE
Polly.JS doesn't encode multipart/form-data requests properly

### ISSUE THREAD

**Issue by swashcap** [Netflix/pollyjs#254]
## Description

_This is a bug report._

Polly.JS appears to not send all of a `multipart/form-data` request to servers when it captures the initial server response. Most servers return an error when they cannot parse multipart form boundaries in a request.

**Update:** Polly.JS doesn't pass multipart/form-data bodies with the right encoding. See comments below.

### Shareable Source

I created a minimal reproduction here that uses [request](http://github.com/request/request) to upload a file to a simple [express](https://github.com/expressjs/express) server: https://github.com/swashcap/pollyjs-multipart-form-data-error

### Error Message & Stack Trace

Most servers return an error when they cannot parse multipart form boundaries in a request. Polly.JS emits an error similar to:

```
PollyError: [Polly] [persister:fs] Cannot persist response for [GET] http://localhost:3001/ because the status code was 400 and `recordFailedRequests` is `false`
```

### Config

I'm using [setup-polly-jest](https://github.com/gribnoysup/setup-polly-jest) to run tests in Node.js. Here's the config:

```javascript
const AdapterNodeHTTP = require('@pollyjs/adapter-node-http')
const PersisterFS = require('@pollyjs/persister-fs')
const path = require('path')
const { Polly } = require('@pollyjs/core')
const { setupPolly } = require('setup-polly-jest')

Polly.register(AdapterNodeHTTP)
Polly.register(PersisterFS)

// ...

describe('this great test', () => {
  const context = setupPolly({
    adapters: ['node-http'],
    persister: 'fs'
  })

  // ...
})
```

(see the test here: https://github.com/swashcap/pollyjs-multipart-form-data-error/blob/master/src/upload.spec.js)

### Dependencies

```shell
$ yarn list --pattern=polly --silent
├─ @pollyjs/adapter-node-http@2.6.2
├─ @pollyjs/adapter@2.6.0
├─ @pollyjs/core@2.6.2
├─ @pollyjs/node-server@2.6.0
├─ @pollyjs/persister-fs@2.6.2
├─ @pollyjs/persister@2.6.2
├─ @pollyjs/utils@2.6.0
└─ setup-polly-jest@0.5.2
```

## Environment

```shell
$ node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v10.16.3
darwin 18.7.0
$ npm --version
6.9.0
$ yarn --version
1.17.3
```

**Comment by swashcap** [comment]
Digging into the code a bit, I found that `HttpAdapter` sends requests using the `passthroughRequest` method:

https://github.com/Netflix/pollyjs/blob/7174b25ef3e97e07d22abac1d25a0e38eb9585b1/packages/%40pollyjs/adapter-node-http/src/index.js#L154-L194

It writes to the `http.ClientRequest` using the response of `HttpAdapter#getChunksFromBody`, which has some comments that seem to not take into account a streaming `body`:

https://github.com/Netflix/pollyjs/blob/7174b25ef3e97e07d22abac1d25a0e38eb9585b1/packages/%40pollyjs/adapter-node-http/src/index.js#L268-L291

**Comment by swashcap** [comment]
Debugging this a bit more, it seems like the handler is registered with nock, which _appears_ to do the parsing?

https://github.com/Netflix/pollyjs/blob/7174b25ef3e97e07d22abac1d25a0e38eb9585b1/packages/%40pollyjs/adapter-node-http/src/index.js#L52-L90

**Comment by swashcap** [comment]
According to https://github.com/nock/nock/issues/191#issuecomment-218791862, nock passes form data in `hex` encoding. Seems…odd? But, sure enough:

```node
> Buffer.from(body, 'hex').toString().split('\n').slice(0, 5).join('\n')
< "----------------------------771413362019705825394252
Content-Disposition: form-data; name="upload"; filename="kittens.jpg"
Content-Type: image/jpeg

����JFIF``���"
```

**Comment by swashcap** [comment]
It looks like nock checks the content here:

https://github.com/nock/nock/blob/9d5cda02efac32967babc8264bb4ae61795ad88d/lib/match_body.js#L13-L19

Which just does a `Buffer.equals` check:

https://github.com/nock/nock/blob/9d5cda02efac32967babc8264bb4ae61795ad88d/lib/common.js#L49-L57

Not very well documented, huh.

**Comment by swashcap** [comment]
What do y'all think of a patch in Polly.JS that checks whether `body` is all hex right here?

https://github.com/Netflix/pollyjs/blob/7174b25ef3e97e07d22abac1d25a0e38eb9585b1/packages/%40pollyjs/adapter-node-http/src/index.js#L71-L76

That should cover the multipart/form-data case.

**Comment by jasonmit** [comment]
First off, thanks for diving into this.

> What do y'all think of a patch in Polly.JS that checks whether body is all hex right here?

Is the goal to avoid calling `JSON.stringify` on `body` if it's all hex values?

**Comment by swashcap** [comment]
> First off, thanks for diving into this.

No problem! We're enjoying Polly.JS quite a bit 🙂

> > What do y'all think of a patch in Polly.JS that checks whether body is all hex right here?
>
> Is the goal to avoid calling JSON.stringify on body if it's all hex values?

The goal would be to correct the `body`’s encoding when it's sent to the upstream server in `HttpAdapter#passthroughRequest`. Right now it's `hex`, it should be decoded to `utf8`.

This should actually be a pretty small fix; shall I open a PR?

**Comment by jasonmit** [comment]
>This should actually be a pretty small fix; shall I open a PR?

Yes please :)
