### ISSUE TITLE
[Question] Decoding gzipped content for storage?

### ISSUE THREAD

**Issue by jrnail23** [Netflix/pollyjs#256]
This question is related to something I encountered when using before migrating to polly, but I see that the persisted recordings (.har files) store gzipped content text in encoded form.

I'd really like to have my recordings be human-readable (and editable), so I'd like to find a way to decode content as it's persisted, then re-encode it when it's read.

Is there a way to do this in polly?

Here's an example I found of how to do something similar with nock (https://github.com/nock/nock/issues/1212), but I don't really see any way to get at polly's underlying nock implementation or any mechanism for extending the reading/writing of .har files.

UPDATE: it looks like my best bet may be to create a custom persister that wraps the `FSPersister`, manipulating the recorded data in `findRecording` and `saveRecording`... I'll update this issue with my findings.

**Comment by jasonmit** [comment]
[`beforePersist`](https://netflix.github.io/pollyjs/#/server/events-and-middleware?id=beforepersist) and [`beforeReplay`](https://netflix.github.io/pollyjs/#/server/events-and-middleware?id=beforereplay) should give you the hooks needed in order to achieve this.

**Comment by jrnail23** [comment]
Thanks for the guidance @jasonmit.  I didn't know about those events! 
I'll give it a try.

**Comment by jrnail23** [comment]
Yep, this worked nicely.  Thanks again, @jasonmit

**Comment by jrnail23** [comment]
@jasonmit, upon further usage, it seems that when an existing recording is updated (for example, if I had 5 requests in the recording, but my test scenario ended up recording a new, 6th request), `beforePersist` does not get triggered for my existing (previously decoded) requests, so when the recording is persisted, it's bypassing my decoding logic, and those requests are persisted in encoded, gzipped format.

It seems that `beforePersist` behaves as more of a `beforeFirstPersist`, which would be fine if you were trying to prune out sensitive info that isn't needed for subsequent requests, but maybe not so good for round-trip processing like I'm aiming for.

I'm sure that explanation is about as clear as mud, but if it does make any sense to you, do you have any advice?

**Comment by jasonmit** [comment]
@jrnail23 that seems like a bug in Polly.  Can you open a separate issue for that?

**Comment by jrnail23** [comment]
Sure, will do.
