### ISSUE TITLE
Trouble proxying http requests to localhost server using Ember

### ISSUE THREAD

**Issue by andrewcallahan** [Netflix/pollyjs#26]
I'm trying to get HTTP requests to proxy to my local api server, which is running on port 3000 on my machine.

I've configured polly as such:
```
    pollyjs: {
      enabled: EmberApp.env() !== 'production',
      server: {
        apiNamespace: 'polly',
        recordingsDir: 'recordings'
      }
    }
```

If I just start the app using `ember s` then the api calls do not get proxied over to my local server. This isn't suprising, since I haven't told the app anywhere to do so. If I start the app using `ember s -proxy=http://localhost:3000` then the ember app tries to forward the call to polly over to my local server, which obviously doesn't exist and returns a 404:

```
http://localhost:4200/polly/Acceptance-Projects-Test_1427335148%2FList-of-Projects_1960582640/c7891a5bc919b6b46c122f196338f0b2?order=0
```

Looking at the documentation, I'm unclear how to get this working. Is there some sort of configuration I need to do in the express server created by polly on the ember app? Or did I just configure polly wrong in `.ember-cli-build`?

Also I have a test app up with the code I'm using https://github.com/andrewcallahan/test-app

Thanks in advance! Really hoping to get this working!

**Comment by offirgolan** [comment]
You can specify the host and api namespace via the `persisterOptions` config. See [here](https://netflix.github.io/pollyjs/#/persisters/rest?id=options).

**Comment by andrewcallahan** [comment]
@offirgolan thanks for the quick reply. I tried doing that actually, but it didn’t work either.

It’s currently commented out in my test app but this is what I added to the .ember-cli-build file:
```
      persister: 'rest',
      persisterOptions: {
        host: 'http://localhost:3000',
        apiNamespace: 'api/v1'
      },
```

**Comment by offirgolan** [comment]
Those options don't go in ember-cli-build, they are passed in to the actual polly instance. The options in that file are specifically for the node/express server. What you're looking for is this:

```js
const Polly = new Polly('foo', {
  persisterOptions: {
    host: 'http://localhost:3000'
  }
});
```

In the case of the qunit test helpers:

```js
setupPolly(hooks, {
  persisterOptions: {
    host: 'http://localhost:3000'
  }
});
```

**Comment by andrewcallahan** [comment]
Thanks @offirgolan - but now that I've done this I'm not sure if the `persisterOptions` changes are what I actually want.

Here is what my `setupPolly` function looks like now:
```
  setupPolly(hooks, {
    persisterOptions: {
      host: 'http://localhost:3000',
      apiNamespace: '/api/v1'
    }
  });
```

When my test is run, it immediately trys to load the polly recording from my api:

```
http://localhost:3000/api/v1/Acceptance-Projects-Test_1427335148%2FList-of-Projects_1960582640/c7891a5bc919b6b46c122f196338f0b2?order=0
```

And it's getting a 404, which is understandable since I don't have anything on my api server set up with polly recordings.

What *I think* I want to do is have polly store the http recordings that come from my local api server at `localhost:3000/api/v1` in the `/recordings` folder in my ember app on the first test run, and then in subsequent test runs recognize that there is a polly recording and just read from the file instead of making a http request. Using these `persisterOptions` I can't get the recordings to be made the first time, because I think I'm telling polly that the recordings are stored on my api server instead of in Ember.

Can you help point me in the direction of how to configure polly to do what I'm proposing? Or maybe what I'm proposing is a misunderstanding of how polly works?

Thanks!

**Comment by offirgolan** [comment]
The polly API is mounted on `/polly` but your persister options are pointing it to `/api/v1`. If you havent touched the node server's `apiNamespace` property, then you dont need to pass in the `apiNamespace` option to the persisterOptions object.

**Comment by kennethlarsen** [comment]
@andrewcallahan Just curious, any chance you are using Windows? My colleague gets the exact same error on his Windows machine but it works perfectly well on my Mac.

**Comment by offirgolan** [comment]
@kennethlarsen the windows issue should've been resolved by #32.

**Comment by andrewcallahan** [comment]
@kennethlarsen I'm using Mac OS X

**Comment by Turbo87** [comment]
@andrewcallahan I'm not entirely sure you're having the same issue as I had, but https://github.com/Netflix/pollyjs/pull/36#issuecomment-399686732 might help :)

**Comment by NullVoxPopuli** [comment]
I think I'm getting the same issue, but in React + Karma + Mocha (using bigtest.js)

![image](https://user-images.githubusercontent.com/199018/42730497-9c0bed26-87c3-11e8-894b-0ec56b342fbd.png)

Here is how I'm trying to intercept a `POST` request: https://github.com/sillsdev/appbuilder-portal/pull/23/commits/cbaa8bf7bb6beb312d7c619e878304efc736c001#diff-5b9212dbfbf828931b81490987b8d4a2R39

**Comment by jasonmit** [comment]
@NullVoxPopuli sounds like a separate issue but have you tried setting `mode` to `"passthrough"` instead of `"replay"`?

**Comment by jasonmit** [comment]
@NullVoxPopuli sounds like a separate issue, can you create a new issue for tracking?

**Comment by NullVoxPopuli** [comment]
@jasonmit why is it a separate issue? I'm trying to mock all requests locally so I can run tests locally (without recording the real responses, I don't care for that)

**Comment by offirgolan** [comment]
> Is, polly supposed to set up a server that listens at that endpoint? or am I supposed to set up some small express thing that polly uses?

@NullVoxPopuli that is correct. If you are using the REST Persister (which it looks like you are), a server must be stood up to support the polly requests. You can follow the setup instructions [here](https://netflix.github.io/pollyjs/#/quick-start?id=setup-browsers-only). 

If you dont want recording/replaying, you will need to upgrade to `v1.0.0` that way you can add `mode: passthrough` to your configuration which will pass through all requests that you havent manually intercepted.
