### ISSUE TITLE
node-http example (server, not client)

### ISSUE THREAD

**Issue by devdoshi** [Netflix/pollyjs#261]
## Description

This is a feature/documentation request. 

My goal is to have a proxy server (node vanilla http or express) which will persist HAR files for any request that goes through it. It seems like in Polly, it's expected to be run on the client that is sending requests. In my scenario, I don't control the client but I do control the server the client is sending requests to over http. So, I want to be able to start a node http server, transparently pass through requests to the proxy target and responses to the client, and have Polly (running on the same server) persist HAR files for these request/response pairs. 

I'm glad to implement this and contribute it back but I'm looking for high-level guidance on if it makes sense to do this with Polly and, if so, how it should be implemented. It seems like I should be able to make an adapter that maps the parsed data from node http.IncomingMessage for the request and http.ServerResponse for the response onto Polly's format and use the fs persister and it should "just work" but I'm not clear on how much from the node-http client example is necessary and how it's different since the flow is a little inverted.

Thoughts?

**Comment by jasonmit** [comment]
Is this a node service that you want to capture all requests from but you cannot modify the source?

**Comment by devdoshi** [comment]
I am working on an open-source developer tool (see https://github.com/opticdev/optic). Part of what we do is stand up a proxy between you (or any client) and an HTTP API server (written in anything) and observe the network traffic in between. For this I want a transparent proxy server that captures requests in a standard format like HAR. But, I want it to be written for node.js so I can keep my stack in javascript and have more control over the execution. Polly is the only thing I've found for node.js that seems to be close to what I want.

**Comment by devdoshi** [comment]
@jasonmit I hope I have answered your question -- please let me know if I can provide any more info. Thanks!

**Comment by jasonmit** [comment]
@devdoshi understood.  This isn't something that Polly supports out of the box.

By the sounds of it, I believe this can be built on top of Polly rather than within.  It would be a matter of setting up an HTTP proxy that your clients would need to be configured to pass-through.  Within the proxy service you would need to instantiate/configure Polly where I'd imagine "everything would just work"™

**Comment by devdoshi** [comment]
Thanks! I'll take a crack at it when I get some time.

**Comment by jasonmit** [comment]
Closing since this isn't something we'll likely support.
