### ISSUE TITLE
Non-deterministic recordings files

### ISSUE THREAD

**Issue by brandon-leapyear** [Netflix/pollyjs#269]
## Description

I'm not sure how to minimally reproduce this, but using `persister-fs`, I'm getting non-deterministic orderings of requests. Context: I'm working on making our polly recordings idempotent; e.g. scrubbing timestamps and auth tokens. I have everything idempotent now, but some recordings (not all) keep changing the order of requests; e.g.
```
[
  <recording for /auth/login>,
  <recording for /users>,
  <recording for /users/4>,
]
```
will get reordered as
```
[
  <recording for /users/4>,
  <recording for /auth/login>,
  <recording for /users>,
]
```

It seems like `Persister` uses `stringify` from `fast-json-stable-stringify`, which should produce a deterministic JSON blob, but `Persister-FS` re-parses the JSON string as JSON, which makes the JSON blob non-deterministic again:

https://github.com/Netflix/pollyjs/blob/8f86fb372b6ac3e6efa36a9dee07d81d8e112847/packages/@pollyjs/persister-fs/src/index.js#L31

I also don't see a unit test for deterministic recordings?

https://github.com/Netflix/pollyjs/blob/master/packages/@pollyjs/persister-fs/tests/unit/persister-test.js

### Shareable Source

Haven't found a minimal repro yet

### Error Message & Stack Trace

See description

### Config

Copy the config used to setup the Polly instance:

```js
const { setupPolly } = require('setup-polly-jest')
setupPolly({
  adapters: ['node-http'],
  persister: 'fs',
  logging: false,
  recordFailedRequests: true,
  recordIfMissing: true,
  mode: recordMode,
  matchRequestsBy: {
    headers: {
      exclude: ['Authorization'],
    },
  },
})
```

### Dependencies

Copy the @pollyjs dependencies from `package.json`:

```json
{
    "@pollyjs/adapter-fetch": "^2.6.3",
    "@pollyjs/adapter-node-http": "^2.6.3",
    "@pollyjs/core": "^2.6.3",
    "@pollyjs/persister-fs": "^2.6.3",
    "@pollyjs/persister-rest": "^2.6.3",
}
```

## Environment

* Mac OS (darwin 18.7.0)
* Yarn: 1.17.3
* Node: v10.16.2

**Comment by brandon-leapyear** [comment]
I wrote the following class as a workaround; it seems to do the job:
```js
import FSPersisterOld from '@pollyjs/persister-fs'
import fs from 'fs'
import stringify from 'json-stable-stringify'

class FSPersister extends FSPersisterOld {
  static get name() {
    return 'fs'
  }

  saveRecording(recordingId, data) {
    fs.writeFileSync(this.api.filenameFor(recordingId), stringify(data, { space: 2 }))
  }
}

module.exports = FSPersister
```

**Comment by offirgolan** [comment]
@brandon-leapyear thanks for opening up this issue! Looking more into it, I think you're right but the root cause is here:

https://github.com/Netflix/pollyjs/blob/8f86fb372b6ac3e6efa36a9dee07d81d8e112847/packages/%40pollyjs/node-server/src/api.js#L29-L31

Where `fs.outputJsonSync` does a JSON.stringify. Converting it to the following should do it:

```
import stringify from 'json-stable-stringify'

fs.outputFileSync(this.filenameFor(recording), stringify(data, { space: 2 }));
```

**Comment by brandon-leapyear** [comment]
hm so it looks like this doesn't really help. Looking at `json-stable-stringify`, it only makes objects deterministic, but it doesn't do anything to the order of the array. It must be that PollyJS adds recording entries in a non-deterministic order?

**Comment by offirgolan** [comment]
@brandon-leapye thinking more about this, the final HAR output doesn't need to be deterministic as the ordering comes from the stored `_order` attribute on each request. When adding new entries to the HAR, they are deduped and sorted by their `startedDateTime`. 

What is the order of your network requests? Is it just the ordering that changes in the final output for you or is it something else?

**Comment by brandon-leapyear** [comment]
My goal is to make the final HAR output deterministic, so that git diffs between recordings don't change. Ideally, if someone makes a change (e.g. changes a POST payload or adds an API call) the diff in the HAR output should only be that single change.

> When adding new entries to the HAR, they are deduped and sorted by their `startedDateTime`.

That's interesting. Is that specified by the HAR standard or is that in polly? I don't see that happening in polly code. To make the HAR output deterministic, I set `startedDateTime` to 0 everywhere

**Comment by brandon-leapyear** [comment]
ok i got it working with this
```js
sessionStore = {
  requestCounter: 0,
}
...
server.any().on('beforePersist', (req, recording) => {
  ...
  recording.startedDateTime = new Date(sessionStore.requestCounter).toISOString()
  sessionStore.requestCounter += 1
})
```
thanks for the help!

**Comment by offirgolan** [comment]
From the HAR 1.2 spec:

> Sorting entries by startedDateTime (starting from the oldest) is preferred way how to export data since it can make importing faster.

See [here](http://www.softwareishard.com/blog/har-12-spec/#entries)

The sorting and deduping is done here:
https://github.com/Netflix/pollyjs/blob/8f86fb372b6ac3e6efa36a9dee07d81d8e112847/packages/%40pollyjs/persister/src/har/log.js#L31-L45

Just as a note, Polly does depend on `startedDateTime` for features such as timing and expiration. Instead, maybe we can support a persister config option to disable sorting the entries.

**Comment by brandon-leapyear** [comment]
I don't have an opinion about the option to disable sorting the entries. It makes sense that the entries are sorted by `startedDateTime`; maybe some option to make it easier to mock out? I can't imagine that my team is the only team that wants auditable diffs in polly recordings.

> Polly does depend on startedDateTime for features such as timing and expiration.

What features does Polly have regarding timing and expiration? Are they applicable to `persister-fs`? Not sure we need those features in our team

**Comment by pushred** [comment]
✋ also interested in auditable diffs.

@brandon-leapyear did your workaround introduce any negative side effects over time?

@offirgolan Are there any plans for features in this area?

https://github.com/Netflix/pollyjs/issues/244 sounds like it but it predated this issue. I'm essentially looking for something equivalent to Jest snapshots and the HAR files are super close to that. But the sorting is definitely getting in the way.

Current behavior _does_ make sense in that while recording the ordering may be dependent on response time of the service being recorded, depending on implementation. But it's a level of detail that doesn't matter much for purposes of tests, IMO.

**Comment by brandon-leapyear** [comment]
@pushred nope! our workaround has been working seamlessly for us (there are other idempotency problems, but this particular spot hasn't given us any trouble)
