### ISSUE TITLE
Feature Request: allow adapter disconnect/connect within request handler

### ISSUE THREAD

**Issue by brandon-leapyear** [Netflix/pollyjs#271]
## Description

In our tests, we submit a task to the server and need to poll the server until the task is marked "done". However, it would be nice to only get the final "done" request in the Polly recording, i.e. the Polly recording should read as if the task was finished immediately. I initially tried to implement this by doing

```js
server.get(...).on('request', async (req) => {
  if (recordMode === 'replay') {
    return
  }

  // needed so that axios.get doesn't trigger this mocked route again
  polly.disconnectFrom('node-http')

  while (true) {
    const { data } = await axios.get(req.url, ...)

    if (data.status === 'In Progress') {
      await server.timeout(500)
    } else {
      polly.connectTo('node-http')
      return
    }
  }
```

But when running this, I get

```
        TypeError: this.NativeClientRequest is not a constructor
        at HttpAdapter.responsePromise [as passthroughRequest] (/Users/bchinn/leapyear/lyalpha/ui/node_modules/@pollyjs/adapter-node-http/src/index.js:168:11)
        at HttpAdapter.onPassthrough (/Users/bchinn/leapyear/lyalpha/ui/node_modules/@pollyjs/adapter/dist/cjs/pollyjs-adapter.js:1346:33)
        at HttpAdapter.onRecord (/Users/bchinn/leapyear/lyalpha/ui/node_modules/@pollyjs/adapter/dist/cjs/pollyjs-adapter.js:1318:16)
        at HttpAdapter.record (/Users/bchinn/leapyear/lyalpha/ui/node_modules/@pollyjs/adapter/dist/cjs/pollyjs-adapter.js:1228:17)
        at HttpAdapter.<anonymous> (/Users/bchinn/leapyear/lyalpha/ui/node_modules/@pollyjs/adapter/dist/cjs/pollyjs-adapter.js:1196:19)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

which I think is because the request is handled in an initialized adapter, but calling disconnectFrom/connectTo in polly creates a new adapter, setting the current adapter's `NativeClientRequest` to `null`.

I'm getting around this with

```js
const adapter = polly.adapters.get('node-http')
while (true) {
  const { body } = await adapter.passthroughRequest(req)
  const data = JSON.parse(body)
  ...
}
```

which seems to work. However, this uses Polly internals (getting the adapter in the Polly instance and using an internal function), and it would be nice to have a first-class way of doing this.

### Config

Copy the config used to setup the Polly instance:

```js
new Polly('Recording Name', {
  // config...
});
```

### Dependencies

Copy the @pollyjs dependencies from `package.json`:

```json
{
  "@pollyjs/core": "latest",
  "@pollyjs/adapter-x": "latest",
  "@pollyjs/persister-x": "latest"
}
```

## Relevant Links

- If your project is public, link to the repo so we can investigate directly.
- **BONUS POINTS:** Create a [minimal reproduction](http://stackoverflow.com/help/mcve) and upload it to GitHub. This will get you the fastest support.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js and npm/yarn. If applicable, include the browser and the corresponding version.

Run the following to get it quickly:

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
npm --version
yarn --version
```

**Comment by offirgolan** [comment]
What if you did something like this instead (I haven't tested this out so not sure if its gonna actually work):

```js
const polly = new Polly('Task is Done', {});
const { mode, server } = polly;
const url = 'http://foo.bar';

if (mode === 'record') {
  server
    .get(url)
    // The amount of tries to get the response we wont could differ so we don't
    // want to match these requests by their order
    .configure({ matchRequestsBy: { order: false } })
    // Force all requests for this url to go to the server
    .passthrough();

  while (true) {
    const { data } = await axios.get(url);

    if (data.status === 'Done') {
      // Turn off the passthrough and let polly take over the recording
      server.get(url).passthrough(false);
      break;
    } else {
      await server.timeout(500);
    }
  }
}

// By this point the server should have the Done task or polly already has the
// correct recorded response.
const { data } = await axios.get(url);

expect(data.status).to.equal('Done');
```

**Comment by brandon-leapyear** [comment]
Sure, that could work, but it seems like that would be stuff to run at the point in the test when you do the action-that-needs-to-be-waited-on. I'm using the setup-polly-jest package and doing all of this configuration in the jest setup file (in beforeEach), so I don't (easily) have access to the polly/server instance in the test itself

**Comment by jasonmit** [comment]
> I don't (easily) have access to the polly/server instance in the test itself

I'm not terribly familiar with the lib but the docs suggest the polly instance hangs off the context object returned by setupPolly.

```js
let context = setupPolly({
  /* default configuration options */
});

// `context.polly`, `context.polly.server` should hold the references you need
```

**Comment by brandon-leapyear** [comment]
Right, but I run setupPolly in a setup script (jest lets you specify an independent file to run when jest boots up), so the context object is not importable or otherwise accessible to the test files

**Comment by offirgolan** [comment]
You can attach the polly context to jest's global object during your setup (see [globalSetup](https://jestjs.io/docs/en/configuration.html#globalsetup-string)).

```js
// setup.js
module.exports = async () => {
  // ...
  // Set reference to the polly context in order to access the polly instance during test runs
  global.__POLLY__ = setupPolly({
    /* default configuration options */
  });

  // `context.polly`, `context.polly.server` should hold the references you need;
};
```

**Comment by brandon-leapyear** [comment]
> Note: Any global variables that are defined through globalSetup can only be read in globalTeardown. You cannot retrieve globals defined here in your test suites.

So no, I can't use globalSetup to use the polly context in tests. But yes, I could just make a normal global variable that holds the polly context.

However, I do like keeping all the polly stuff in one setup file instead of having polly logic live in multiple places. The solution above with using polly.adapters works for us, and I think our solution is clearer in its purpose than the code snippet you provided. It's fine if this doesn't warrant a first-class feature in polly, since it can be worked around.

**Comment by offirgolan** [comment]
Following up on this, you should be able to do something like this to avoid using private APIs:

```js
server.get(...).on('request', async (req) => {
  if (recordMode === 'replay') {
    return
  }

  const prevMode = polly.mode;
  polly.mode = 'passthrough';

  while (true) {
    const { data } = await axios.get(req.url, ...)

    if (data.status === 'In Progress') {
      await server.timeout(500)
    } else {
      polly.mode = prevMode;
      return
    }
  }
```

I don't believe we will support disconnecting and reconnecting from an adapter mid request as that could get a bit complicated without much benefit.

Feel free to reopen this issue or create a new one if you're still continuing to face this issue.
