### ISSUE TITLE
matchRequestsBy functions should have the entire request context at their disposal

### ISSUE THREAD

**Issue by yaronassa** [Netflix/pollyjs#274]
## Description

I use many `matchRequestsBy` custom functions to unify different requests across test domains, users, tokens and proxies. Specifically with url segments functions (but also with other functions), I often find myself needing the entire context of the request in order to effectively unify the relevant request field.

For example, we have a jump-host proxy for testing from outside our VPM, that requires prefixing the URL `pathname` with some fragment specifying the target environment. However, to determine if I should actually remove that fragment from the `pathname` in order to unify the request ID, I need to have a look at the `hostname` of the request (and vice-versa, and unifying the `hostname` requires me to have the `pathname` data to understand where the jump host leads me).

It would be immensely useful if each `matchRequestsBy` function would receive two parameters - the relevant value to be mutated (e.g. the `pathname`) and an optional request object in its entirety, containing all the properties and values relevant for the matching mechanism.
Using the two-parameters approach wouldn't even break the existing API (current functions will still adhere the function signature and work as designed).

Thanks for a great and useful tool!

**Comment by offirgolan** [comment]
Makes sense to me. Should be a very simple add.
