### ISSUE TITLE
How are requests, internal & remote calls stubbed?

### ISSUE THREAD

**Issue by mrpotatoes** [Netflix/pollyjs#275]
## Description
We are trying to get Polly to use a HAR recording it has previously saved. The code below will illustrate my latest attempt after a day of working with the library. We have cloned this repo and have installed the `./examples/puppeteer` example and ran it then began to modify it's source code.

What I was expecting to be able to do was that it would download the network archive (HAR) and save it and then any incoming requests would be intercepted and that archive's data would be used instead. The `dummy-app` is really simple as it just makes requests to https://jsonplaceholder.typicode.com and those are the specific calls I was hoping to intercept.

That is where my issues stem. As I learned `PollyJS` doesn't automatically stub/intercept these calls so I needed to do them myself. I have reached an impasse as I don't know where the CORs issue is coming from or if I can avoid it all together.

### Shareable Source

```js
(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();
  await page.setRequestInterception(true);

  const { server } = polly;
  server.any().on('request', (req, res) => {
    // None of these work.
    // req.headers['no-cors'] = false
    // req.headers['no-cors'] = true // At this point I'm just trying anything.
    // req.headers['Access-Control-Allow-Origin'] = 'jsonplaceholder.typicode.com'
    // req.headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept'
  });

  server.host('http://localhost:3000', () => {
    server.get('/favicon.ico').passthrough();
    server.get('/sockjs-node/*').intercept((_, res) => res.sendStatus(200));
  });

  server.get('https://jsonplaceholder.typicode.com/*').intercept((req, res) => {
    const rawHar = fs.readFileSync('./recordings/puppeteer_2155046665/recording.har');
    const data = JSON.parse(rawHar);    
    res.status(200).json(rawHar)
  });

  await page.goto('http://localhost:3000', { waitUntil: 'networkidle0' });
})();

```

### Error Message & Stack Trace
(newlines added)
```
Access to fetch at 'https://jsonplaceholder.typicode.com/posts?_end=10&_order=ASC&_sort=title&_start=0' 
from origin 'http://localhost:3000' has been blocked by CORS policy:
 No 'Access-Control-Allow-Origin' header is present on the requested resource. 
If an opaque response serves your needs, set the request's mode to 'no-cors' to 
fetch the resource with CORS disabled.
```

### Config

Copy the config used to setup the Polly instance:

```js
new Polly('puppeteer', {
    adapters: ['puppeteer'],
    adapterOptions: {
      puppeteer: {
        page,
        requestResourceTypes: ['xhr', 'fetch']
      }
    },
    persister: 'fs',
    persisterOptions: {
      fs: {
        recordingsDir: path.join(__dirname, 'recordings')
      }
    }
  });
```

## Full source code but collapsed
<details>
  <summary>Click to expand!</summary>
  
```js
/* eslint-disable */
console.clear()
const path = require('path');
const { bgGreen } = require('chalk');

const puppeteer = require('puppeteer');
const { Polly } = require('@pollyjs/core');
const PuppeteerAdapter = require('@pollyjs/adapter-puppeteer');
const FSPersister = require('@pollyjs/persister-fs');
const fs = require('fs');

console.log(bgGreen('I MADE IT INTO HERE'))
Polly.register(PuppeteerAdapter);
Polly.register(FSPersister);

(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();

  await page.setRequestInterception(true);

  const polly = new Polly('puppeteer', {
    adapters: ['puppeteer'],
    adapterOptions: {
      puppeteer: {
        page,
        requestResourceTypes: ['xhr', 'fetch']
      }
    },
    persister: 'fs',
    persisterOptions: {
      fs: {
        recordingsDir: path.join(__dirname, 'recordings')
      }
    }
  });

  const { server } = polly;
  server.any().on('request', (req, res) => {
    // None of these work.
    // req.headers['no-cors'] = false
    // req.headers['no-cors'] = true // At this point I'm just trying anything.
    // req.headers['Access-Control-Allow-Origin'] = 'jsonplaceholder.typicode.com'
    // req.headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept'
  });

  server.host('http://localhost:3000', () => {
    server.get('/favicon.ico').passthrough();
    server.get('/sockjs-node/*').intercept((_, res) => res.sendStatus(200));
  });

  server.get('https://jsonplaceholder.typicode.com/*').intercept((req, res) => {
    const rawHar = fs.readFileSync('./recordings/puppeteer_2155046665/recording.har');
    const data = JSON.parse(rawHar);
    
    res.status(200).json(rawHar)
  });

  await page.goto('http://localhost:3000', { waitUntil: 'networkidle0' });

  // Commented out so that I can use the browser.
  // await polly.flush();
  // await polly.stop();
  // await browser.close();
})();

```
</details>

### Dependencies
```json
{
  "@pollyjs/adapter-puppeteer": "*",
  "@pollyjs/core": "*",
  "@pollyjs/persister-fs": "*",
  "puppeteer": "*",
  "start-server-and-test": "*"
}
```

## Environment
Tell us which operating system you are using, as well as which versions of Node.js and npm/yarn. If applicable, include the browser and the corresponding version.

Run the following to get it quickly:

| Software   |      Version |
|----------|:-------------:|
| `node` | 8.15.1 |
| `OS` |  16.7.0   |
| `npm` | 6.4.1 |
| `yarn` | 1.1.0 |

**Comment by jasonmit** [comment]
There's a lot here to unpack.

> The dummy-app is really simple as it just makes requests to https://jsonplaceholder.typicode.com and those are the specific calls I was hoping to intercept.

Were you hoping to record these requests and replay them back?  If so, Polly should be able to do this for you without explicitly recording a HAR file yourself and attempting to use that in place.

What's going on here appears to be [CORs isn't something that jsonplaceholder implements](https://github.com/typicode/jsonplaceholder/issues/4).  Basically your client is asking for permission to hit jsonplaceholder.typicode.com and it's not responding with the correct header set.

To disable same-origin policy within the chrome instance that puppeteer is spinning up you can pass the disable-web-security flag like:

```js
const browser = await puppeteer.launch({
  args: [
    '--disable-web-security',
  ],
  headless: false
});
```

**Comment by mrpotatoes** [comment]
Thank you for the help. Somewhere along the lines I made some mistakes, which I cannot divulge because I don't know where I went awry, but your help helped me fix my issue. it is working as it should so thank you!
