### ISSUE TITLE
Strange behaviour matching request modified in beforePersist

### ISSUE THREAD

**Issue by tamlyn** [Netflix/pollyjs#279]
## Description

I *think* this is a bug but there's always a chance it's a feature and I haven't understood something.

I'm testing an authentication flow and I don't want the real auth tokens to be committed to the repo. I've set up a `beforePersist` middleware to replace `real-token` with `dummy-token` in the POST bodies. When recording I make the requests with `real-token`. Then when running my tests against the recordings I make the requests with `dummy-token`. I would expect this to work because the `real-token` was changed to `dummy-token` when saving the HAR. But it doesn't: the request doesn't match.

The really strange thing is that if I run the test against the recordings but using the original `real-token` that I used when making the recordings it passes, even though that token doesn't appear in the HAR file. **How does Polly remember the original token even when I've removed it from the HAR?**

I've created a minimal test case here https://github.com/tamlyn/polly-test-case to illustrate the problem.

```
Node.js v12.13.1
darwin 17.7.0
npm 6.11.3
yarn 1.19.2
```

**Comment by offirgolan** [comment]
@tamlyn even though you're storing the `dummy-token` in the HAR file, you're still making the request with the `real-token`. Polly calculates the request's id based on the request you made (not whats stored in the HAR), so you would need to tell Polly to ignore the token altogether. You can do so via [matchRequestsBy](https://netflix.github.io/pollyjs/#/configuration?id=matchrequestsby).

**Comment by tamlyn** [comment]
Ah! So the `_id` is a hash of the request? I thought it was random. Is that documented anywhere? Is the request object as stored in the HAR used for anything?

**Comment by jasonmit** [comment]
> So the `_id` is a hash of the request

Correct

> Is that documented anywhere?

https://netflix.github.io/pollyjs/#/configuration?id=matchrequestsby

> Is the request object as stored in the HAR used for anything?

For completeness with the HAR spec (importing into a HAR tool to inspect for example).  In the future, we may leverage it more.
