### ISSUE TITLE
feature: IE11 support

### ISSUE THREAD

**Issue by piotrpalek** [Netflix/pollyjs#28]
Hey, I've been trying out pollyjs in an Ember.js app, and noticed that the app won't work at all because the imported pollyjs files include statements like arrow functions which don't work with IE.

The issue seems to be that the Polly.js addon uses `app.import` to include the libraries, but afaik `app.import` doesn't run the code through webpack, so it doesn't transform it into viable ES5 code. It just includes the code verbatim.

edit: btw sidenote, shouldn't pollyJS be included only when running in the test environment by default?

**Comment by jasonmit** [comment]
Currently not a browser we target.

> edit: btw sidenote, shouldn't pollyJS be included only when running in the test environment by default?

Dev and testing.  Prod it should not be included.

**Comment by jasonmit** [comment]
@piotrpalek we're going to update Polly to support down to IE11.  Likely will happen in the next release.

**Comment by piotrpalek** [comment]
@jasonmit cool, I've currently sidestepped the problem by only including it when needed (testing basically) but :+1:

**Comment by Ekman** [comment]
@jasonmit any status updates on this?

**Comment by jasonmit** [comment]
@Ekman no update, I haven't revisited after fixing Edge.  We also need to setup a Windows CI environment.

**Comment by offirgolan** [comment]
Closing this issue. Feel free to reopen if IE11 support is still needed.
