### ISSUE TITLE
Docs: missing logo image in documentation

### ISSUE THREAD

**Issue by barakplasma** [Netflix/pollyjs#281]
## Description

Missing the Polly logo in the documentation

![Screen Shot 2019-12-17 at 16 57 14](https://user-images.githubusercontent.com/62937/71006709-74acac00-20ee-11ea-8920-8c0cd2696b33.png)
### Shareable Source

```js
<a class="app-name-link" data-nosearch="" href="/pollyjs/">&lt;img src="assets/images/logo.png" alt="Polly.JS Logo" class="sidebar-logo"&gt;</a>
```

## Relevant Links

- https://netflix.github.io/pollyjs/#/README

## Environment

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36

**Comment by jasonmit** [comment]
Assigning to @offirgolan since I don't have access to do deployments (I don't think I do at least...).
