### ISSUE TITLE
The big picture

### ISSUE THREAD

**Issue by ashishsinha1** [Netflix/pollyjs#282]
I have been struggling to understand the big picture. I read everything and tried few of those examples but still unable to connect the dots. So first I need to be sure that my current understanding is right: Recording (and replaying) happens at the client and not at the server (server being jsonplaceholder.typicode.com in given examples). **Is that the right understanding?** And that would also implicitly mean that all that code is written to run on the client.

**Comment by jasonmit** [comment]
> Recording (and replaying) happens at the client and not at the server (server being jsonplaceholder.typicode.com in given examples)

Polly sits in between your application and the requests your application makes.  It does this by intercepting calls to `globalThis.fetch` and `globalThis.XMLHttpRequest` for Polly's browser implementation.  For the node implementation, we internally use [`nock`](https://github.com/nock/nock) to deal with intercepting network interactions in Node.

Polly has its own persistence "server" which the mock clients interact with when recording and replaying.  Polly is typically only used for writing tests which you don't want to hit an actual API and local development (stubbing future API endpoints, avoiding expensive API calls, and/or offline development).

**Comment by ashishsinha1** [comment]
Thanks jasonmit. So if I have a nodejs express server with a GET route ready to serve requests to any client, can I add pollyjs code there **(only)** to record the incoming requests and outgoing responses? Or will I need to run some pollyjs code on the client as well?

**Comment by ashishsinha1** [comment]
> > Recording (and replaying) happens at the client and not at the server (server being jsonplaceholder.typicode.com in given examples)
> 
> Polly sits in between your application and the requests your application makes. It does this by intercepting calls to `globalThis.fetch` and `globalThis.XMLHttpRequest` for Polly's browser implementation. For the node implementation, we internally use [`nock`](https://github.com/nock/nock) to deal with intercepting network interactions in Node.
> 
> Polly has its own persistence "server" which the mock clients interact with when recording and replaying. Polly is typically only used for writing tests which you don't want to hit an actual API and local development (stubbing future API endpoints, avoiding expensive API calls, and/or offline development).

Thanks jasonmit. So if I have a nodejs express server with a GET route ready to serve requests to any client, can I add pollyjs code there **(only)** to record the incoming requests and outgoing responses? Or will I need to run some pollyjs code on the client as well?

**Comment by jasonmit** [comment]
> can I add pollyjs code there (only) to record the incoming requests and outgoing responses

I believe so.  Hard to say for certain without understanding the complete use-case.
