### ISSUE TITLE
Should "_order" still increment after polly.pause?

### ISSUE THREAD

**Issue by brandon-leapyear** [Netflix/pollyjs#285]
##  Description

Question: I have a code snippet that does roughly:

```
polly.pause()
// keep making HTTP request until response satisfies a condition
polly.play()
// make same HTTP request
```

I would expect the recording to only contain the last request (after `.play()`) and have the `_order` attribute still be 0, as if the requests between pause and play didn't happen. Instead, I see the recording not having the extra requests (as expected), but `_order` becomes something like 7. What's the correct semantics here?

### Config

```js
{
  adapters: ['node-http'],
  persister: 'fs',
  logging: false,
  recordFailedRequests: true,
  recordIfMissing: true,
  mode: __RECORD_MODE__,
  matchRequestsBy: {
    headers: {
      exclude: ['Authorization'],
    },
  },
}
```

### Dependencies

Copy the @pollyjs dependencies from `package.json`:

```json
{
  "@pollyjs/adapter-fetch": "^3.0.0",
  "@pollyjs/adapter-node-http": "^3.0.0",
  "@pollyjs/core": "^3.0.0",
  "@pollyjs/persister-fs": "^3.0.0",
  "@pollyjs/persister-rest": "^3.0.0",
}
```

## Environment

```
darwin 18.7.0
NPM 6.9.0
yarn 1.17.3
```

**Comment by jasonmit** [comment]
> I see the recording not having the extra requests (as expected), but _order becomes something like 7

I'd expect the order to be 0 as well.  This sounds like a bug and will need to be investigated.

**Comment by offirgolan** [comment]
Unfortunately the order must be deterministic since there are many other factors that could change the state of the request at any time. This would also become pretty complicated once parallel requests are being made, each with their own interception logic that could potentially force the request to pass-through. 

Instead, I would disconnect and reconnect polly from the specified adapter while you're waiting for a certain condition to become true so the requests don't even get picked up by the polly instance:

```js
const res = await fetch('/api/foo');

if (!res.ok) {
  poll.disconnectFrom('node-http');

  // do some logic until res.ok === true

  polly.connectTo('node-http');
}

const res2 = await fetch('/api/foo');

expect(res2.ok).toBeTrue();
```

**Comment by brandon-leapyear** [comment]
> Unfortunately, the order must be deterministic

I'm not sure what you mean. As I understand it, "_order" is only a Polly concept — I don't see any mention of it in the HAR spec. That is to say, I thought "_order" is only something Polly adds to the recording so that recordings with the same payload can be replayed in the same order.

If that's the case, I don't see why requests with "_order" 1-6 need to be accounted for in the recording. The recording, when replayed, isn't going to need to know that requests 1-6 happened but weren't recorded.

**Comment by offirgolan** [comment]
> If that's the case, I don't see why requests with "_order" 1-6 need to be accounted for in the recording

I totally agree with you on this. After some offline discussion with @jasonmit, we  think the best solution is to disconnect from all the adapters when `polly.pause()` is called and then reconnect to them when `polly.play()` is called. This will ensure that no unwanted requests get picked up by the polly instance.
