### ISSUE TITLE
Failed to construct 'Request': Please use the 'new' operator, this DOM object constructor cannot be called as a function

### ISSUE THREAD

**Issue by jasonmit** [Netflix/pollyjs#286]
Error:
`Failed to construct 'Request': Please use the 'new' operator, this DOM object constructor cannot be called as a function.`

Offending line:
`_this2 = possibleConstructorReturn(this, getPrototypeOf$2(ExtendedRequest).call(this, url, options));`

Reproduction (thanks to @dheeraj-jn for putting this together):
https://codesandbox.io/s/fragrant-pine-cwnox

This looks to be caused by the way babel is calling super on `ExtendedRequest`.

**Comment by offirgolan** [comment]
Resolved with `v3.0.1`.

**Comment by jasonmit** [comment]
Thanks @offirgolan
