### ISSUE TITLE
Allow for one Polly recording that can be reused across multiple tests

### ISSUE THREAD

**Issue by jaboulos** [Netflix/pollyjs#288]
I'd like to know if it's possible to create 1 Polly recording that can be reused across multiple tests. Right now each test creates it's own har file which is expected but we'd like to know if Polly allows or has options to record all tests into just 1 file.

**Comment by offirgolan** [comment]
You can change the recording name via `polly.recordingName = 'Whatever you want'`. You can also change it on a per route basis via the [recordingName()](https://netflix.github.io/pollyjs/#/server/route-handler?id=recordingname) server method

**Comment by jasonmit** [comment]
@jaboulos feel free to open another issue if this isn't what you had in mind.
