### ISSUE TITLE
How can i use polly on a simple test project?

### ISSUE THREAD

**Issue by marchiore** [Netflix/pollyjs#29]
Hi!

I'm found PollyJS on github trending repos, and i'm curious about how it works and how it can help me on my projects. So i've create a simple node app like:

```
const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World\n');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```

i've already run:

```
npm install @pollyjs/cli -g
npm install @pollyjs/core -D
```

But i'm a little bit lost on where should i have to code the sample:

```
import { Polly } from '@pollyjs/core';

describe('Netflix Homepage', function() {
  it('should be able to sign in', async function() {
    /*
      Create a new polly instance.

      By default, Polly will connect to both fetch and XHR browser APIs and
      will record any requests that it hasn't yet seen while replaying ones it
      has already recorded.
    */
    const polly = new Polly('Sign In');

    /* start: pseudo test code */
    await visit('/login');
    await fillIn('email', 'polly@netflix.com');
    await fillIn('password', '@pollyjs');
    await submit();
    /* end: pseudo test code */

    expect(location.pathname).to.equal('/browse');

    /*
      Calling `stop` will persist requests as well as disconnect from any
      connected browser APIs (e.g. fetch or XHR).
    */
    await polly.stop();
  });
});
```

Thanks in advance!

**Comment by jasonmit** [comment]
> But i'm a little bit lost on where should i have to code the sample

Polly hooks into test framework.  The first step is determining which test framework you want to use and how that hooks up to your workflow.  That's one layer up from Polly.  Depending on your project and comfort level, that may vary but here are two recommendations: https://mochajs.org/ and http://qunitjs.com/

Once you have that setup, continue with:
https://netflix.github.io/pollyjs/#/test-helpers/mocha or https://netflix.github.io/pollyjs/#/test-helpers/qunit

**Comment by marchiore** [comment]
Thanks for quick answer!

I 'll take a look on it.
