### ISSUE TITLE
jest-puppeteer example doesn't work as expected

### ISSUE THREAD

**Issue by wallynm** [Netflix/pollyjs#290]
## Description

Bug - The examples folder `jest-puppeteer` doesn't work, i imagine that is a topic of version because all package are configured to install last version "*".
Installed all packages then run `yarn test`

The console doesn't print that the test failed or not, another thing i did for test was delete the recording folder and it doesn't recorded a new one.

I've tried those packages into my local application and they didn't work as well, when trying puppeteer alone, including the examples folder everything works as expected.

**Comment by jasonmit** [comment]
```js
const browser = await puppeteer.launch();
const page = await this.browser.newPage();

await page.setRequestInterception(true);

polly.configure({
  adapters: ['puppeteer'],
  adapterOptions: {
    puppeteer: { page }
  }
});

await page.goto('http://netflix.com');
```

Is this the example you're referring to?  Have you made any other changes to that sample that you ran?

**Comment by jasonmit** [comment]
Able to reproduce, unfortunately on really terrible internet so will need to come back tomorrow to fix.

**Comment by jasonmit** [comment]
@wallynm issue should be resolved now, thanks for reporting.
