### ISSUE TITLE
@pollyjs/ember stores recordings in [projectRoot]node_modules/@pollyjs/ember/recordings

### ISSUE THREAD

**Issue by nfc036** [Netflix/pollyjs#297]
`@pollyjs/ember@4.0.0` is storing the recordings in `[projectRoot]/node_modules/@pollyjs/ember/recordings`.
Also, configuration options in config/polly.js are ignored.

It seems to me, that this.root in https://github.com/Netflix/pollyjs/blob/6423839d9aeb9b0318ae69251d8bafcd28933408/packages/%40pollyjs/ember/index.js#L78 and https://github.com/Netflix/pollyjs/blob/6423839d9aeb9b0318ae69251d8bafcd28933408/packages/%40pollyjs/ember/index.js#L86-L89 is pointing to the root of the addon, not to the root of the project using @pollyjs/ember. When I change `this.root` to `this.project.root` everything is working as expected.

I'm using ember-cli@3.15.1.

**Comment by offirgolan** [comment]
Fix released in `v4.0.1`.
