### ISSUE TITLE
Can it record *incoming* requests?

### ISSUE THREAD

**Issue by goldbergyoni** [Netflix/pollyjs#307]
This is a question I couldn't figure out while reading the docs.

I noted it has great capabilities in recording outgoing requests, but can this lib also handle incoming API requests (e.g. Expess API server)? My intent is to record my production requests and then replay those over staging

**Comment by jasonmit** [comment]
I'm not really sure what you mean.  Do you want something that records incoming requests and on replay simulate them incoming again?  If so, no Polly does not support this use case.

**Comment by goldbergyoni** [comment]
> on replay simulate them incoming again?

Not exactly. What I want is classic traffic shadowing - record express server API receiving requests, simply record the incoming HTTP traffic. Then replay the same traffic against other API. This is typically being used to record the incoming production traffic and replay against the staging to ensure it can handle the same requests

**Comment by jasonmit** [comment]
No Polly isn't suited for replaying incoming traffic.  Good question though, I'm going to close since it feels beyond the scope of this project right now.
