### ISSUE TITLE
feature: playwright adapter

### ISSUE THREAD

**Issue by PeterNgTr** [Netflix/pollyjs#308]
## Description

Microsoft just releases a new cool lib called Playwright (https://github.com/microsoft/playwright/tree/v0.10.0) and the team behind is the one who are building the Puppeteer. May we consider support this at some point?

**Comment by jasonmit** [comment]
We would definitely consider supporting playwright.

**Comment by henzlmarek** [comment]
Hello Team!

Any updates on this? Would really appreciate playwright support.

Thank you.

Kind Regards,
Marek Henzl

**Comment by redabacha** [comment]
hi all,

i also ran into this issue and took it upon myself to write an polly.js adapter for playwright. here's the repo: [https://github.com/redabacha/polly-adapter-playwright](https://github.com/redabacha/polly-adapter-playwright). it's published on npm with the name `polly-adapter-playwright`. i hope you find it useful.

regards,
reda

**Comment by offirgolan** [comment]
@redabacha that's awesome! Thank you for taking the time to write this. I will add a section for it in the docs 😄
