### ISSUE TITLE
issue with `name` property when creating a custom adapter in TS 

### ISSUE THREAD

**Issue by TychosDrunkElk** [Netflix/pollyjs#309]
## Description

When creating a custom adapter using typescript, the name property conflicts with the `Function.name` constructor. not sure how to get around this, would it be possible to rename the property to `adapterName` or something similar? 

### Shareable Source

```js
class NewAdapter extends Adapter {
  // ...
  static get name() {
    return 'new-adapter';
  }
// ...
}
```

### Error Message & Stack Trace

```
Static property 'name' conflicts with built-in property 'Function.name' of constructor function 'NewAdapter'.
```

### Dependencies

Copy the @pollyjs dependencies from `package.json`:

```json
{
  "@pollyjs/adapter": "^4.0.2"
}
```

## Relevant Links

https://github.com/microsoft/TypeScript/issues/442

## Environment

Node.js v12.6.0
darwin 18.7.0
yarn 1.19.1
npm 6.9.0

**Comment by jasonmit** [comment]
I'm open to deprecating and renaming.  Can be done in a backwards compatible way so we don't need to release another major for this.  Any interest in taking it up?

**Comment by TychosDrunkElk** [comment]
@jasonmit awesome, can definitely pick this up :) thanks!
