### ISSUE TITLE
Http Responses are sometimes not persisted due to synchronization issue

### ISSUE THREAD

**Issue by nbfr** [Netflix/pollyjs#323]
## Description

I'm using Polly to record and replay data during testing and development. 
Each response is persisted immediately to the Polly backend:

```js
server.any().on('response', () => polly.persister.persist());
```

However sometimes REST responses are not persisted at all, if there is more than one REST response returned at the same time.

The reason being that 'recordRequest' in RESTPersister is executed while 'persist' in RESTPersister has not completed yet. 'recordRequest' will add an element to the 'pending' map. At the end of the 'persist' method this map is cleared. Therefore it is possible that the 'pending' map is cleared although not all requests have been persisted.

### Config

```js
      Polly.register(XHRAdapter);
      Polly.register(RESTPersister);

      const polly = new Polly('mock', {
        adapters: ['xhr'],
        persister: 'rest',
        recordIfMissing: true,
        persisterOptions: {
            keepUnusedRequests: true
       }
      });

      const { server } = polly;

      server.any().on('response', () => polly.persister.persist());
```

### Dependencies

```json
{
    "@pollyjs/core": "4.0.4",
    "@pollyjs/adapter-xhr": "4.0.4",
    "@pollyjs/node-server": "4.0.2",
    "@pollyjs/persister-rest": "4.0.4",
}
```

## Environment

Node.JS v10.16.3
win32 10.0.1832
npm 6.9.0

**Comment by offirgolan** [comment]
What is your use case for persisting each response one by one instead of calling `polly.stop()` at the end?

**Comment by jasonmit** [comment]
Closing, appears to be stale.  If not, respond and we'll reopen!
