### ISSUE TITLE
Preflight request doesn't pass access control check when using @pollyjs/node-server

### ISSUE THREAD

**Issue by WillyLi** [Netflix/pollyjs#326]
## Description
Hi Pollyjs team,
We are using `@pollyjs/node-server` as our API server in our development environment. 
In some requests, we fetch API with credentials.
```js
axios.get(`${API_HOST}/api`, { data: true, withCredentials: true })
```

### Shareable Source
Here is the demo sandbox online.
https://codesandbox.io/s/pollyjsnode-server-cors-issue-demo-02eof?file=/src/demo.html

### Error Message & Stack Trace
> Access to XMLHttpRequest at 'http://localhost:4000/api' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.```

### Config

Copy the config used to setup the Polly instance:

```js
const { Server } = require("@pollyjs/node-server");

const server = new Server({
  port: 4000
});
server.app.get("/api", (req, res) => {
  res.header("Access-Control-Allow-Origin", "http://localhost:3000");
  res.send(200);
});
server.listen().on("error", () => {
  console.log("error");
  /* Add http server error logic */
});

```

### Dependencies
Copy the @pollyjs dependencies from `package.json`:

```json
{
    "@pollyjs/node-server": "4.0.2",
    "concurrently": "5.1.0",
    "express": "4.17.1"
  }
```

### Suggestion
The root cause is that CORS middleware is using the default configuration.
If we can add orgin configuration [here](https://github.com/Netflix/pollyjs/blob/master/packages/%40pollyjs/node-server/src/server.js#L15), the problem would be fixed.

**Comment by jasonmit** [comment]
Seems like a reasonable ask.  Seems we need to wire up the ability to pass in config options to the `Server` constructor that make its way to the cors middleware.

Let me know if you want to take this up
