### ISSUE TITLE
Cannot read property 'timestamp' of undefined

### ISSUE THREAD

**Issue by 404157386** [Netflix/pollyjs#33]
I add this code for my project
but hit error...

[https://netflix.github.io/pollyjs/#/server/overview](https://netflix.github.io/pollyjs/#/server/overview)

```
import {Polly} from "@pollyjs/core"; 

const polly = new Polly('<Recording Name>');
const { server } = polly;

// Events & Middleware
server
  .any()
  .on('request', (req, res) => {
    req.headers['X-Auth-Token'] = 'abc123';
  });

// Intercept requests
server.get('/session').intercept((req, res) => {
  res.status(200).json({ user: { email: 'test@netflix.com' } });
});

// Passthrough requests
server.get('/coverage').passthrough();

```

> Uncaught (in promise) TypeError: Cannot read property 'timestamp' of undefined
>     at n.value (pollyjs-core.js?2fca:1)
>     at eval (pollyjs-core.js?2fca:1)
>     at w (pollyjs-core.js?2fca:1)
>     at Generator.eval [as _invoke] (pollyjs-core.js?2fca:1)
>     at Generator.l.(:8088/anonymous function) [as next] (webpack-internal:///./node_modules/@pollyjs/core/dist/umd/pollyjs-core.js:1:12578)
>     at e (pollyjs-core.js?2fca:1)
>     at eval (pollyjs-core.js?2fca:1)
> value @ pollyjs-core.js?2fca:1
> (anonymous) @ pollyjs-core.js?2fca:1
> w @ pollyjs-core.js?2fca:1
> (anonymous) @ pollyjs-core.js?2fca:1
> l.(anonymous function) @ pollyjs-core.js?2fca:1
> e @ pollyjs-core.js?2fca:1
> (anonymous) @ pollyjs-core.js?2fca:1

**Comment by PdcGhost8** [comment]
new to this. Think Import Polly may not need {}

**Comment by Joshcranford17** [comment]
I'm working on it everyone. For the perfect Profile it takes lots of patience and time

**Comment by offirgolan** [comment]
@404157386 I was hoping to get some more info so I can debug this.

1. What's your environment (OS, browser, etc)
2. Can you provide the full test code?
3. Its difficult to see from the stack where this is happening, if you can provide the source of where the exception was thrown, that would be super helpful.

**Comment by 404157386** [comment]
@offirgolan 
This is a demo for this issue:
https://github.com/404157386/pollyjs-issue-33

`npm i` and `npm run dev` at the demo path

os: windows 10
npm version: 4.2.0
node version:  v7.10.1
broweser: Google Chrome 67.0.3396.87

This issue happens when http request or HMR reload.

**Comment by offirgolan** [comment]
@404157386 you are missing the step to register the Polly API express middleware.

```diff
# build/dev.js

const Webpack = require("webpack");
const WebpackDevServer = require("webpack-dev-server");
const loadDevConfig = require("./webpack.dev.conf");
+ const { registerExpressAPI } = require("@pollyjs/node-server");
const mock = require("../mock");
const options = {
  contentBase: "./dist",
  hot: true,
  host: "localhost"
};

loadDevConfig.then(res => {
  const webpackConfig = res;
  WebpackDevServer.addDevServerEntrypoints(webpackConfig, options);
  const compiler = Webpack(webpackConfig);
  const devServerOptions = Object.assign({}, webpackConfig.devServer, {
    inline: true,
    stats: {
      colors: true
    },
    before: function(app) {
+      registerExpressAPI(app);
      mock(app);
    }
  });
  const server = new WebpackDevServer(compiler, devServerOptions);

  server.listen(devServerOptions.port, devServerOptions.host, () => {});
});
```

See [here](https://netflix.github.io/pollyjs/#/node-server/express-integrations) for more details.

**Comment by offirgolan** [comment]
Also, make sure you call `await polly.stop()` so your API calls get persisted to disk.

**Comment by 404157386** [comment]
Thank you for help!

**Comment by jimmielemontgomery** [comment]
@offirgolan and @404157386 where does the `await polly.stop()` go ([mentioned above](https://github.com/Netflix/pollyjs/issues/33#issuecomment-400420567)) and how does it work? In reading through the quickstart I can't quite figure this out and I'm reading the API+config now. Thanks very much.
