### ISSUE TITLE
Redesigning "Polly.JS" Logo

### ISSUE THREAD

**Issue by rlathgml1004** [Netflix/pollyjs#330]
## Description

Redesigned "Polly.JS" Logo to reinforce symbol and meaning.

Motivation
: if it's able to guess what "polly js project" it is, it helps to enhance contribution rate. and the project will develop faster

### Shareable Source

[original logo]
![image](https://user-images.githubusercontent.com/64514522/81781634-68a90700-9533-11ea-8d65-c676eb880991.png)
[Redesigned logo] for white mode
![image](https://user-images.githubusercontent.com/64514522/81781655-73639c00-9533-11ea-9dc3-f4a48cce4193.png)
[Redesigned logo] for dark mode
![image](https://user-images.githubusercontent.com/64514522/81781818-c1789f80-9533-11ea-995e-0281af17f6dd.png)

**Comment by jasonmit** [comment]
We're happy with the logo as-is but thank you for your contribution.
