### ISSUE TITLE
Obscurity meaning in readme.md file

### ISSUE THREAD

**Issue by rlathgml1004** [Netflix/pollyjs#338]
## Description

I found an obscurity meaning in the process of translating files.
confirm it please.

### Shareable Source
In Readme file,
![image](https://user-images.githubusercontent.com/64514522/82991423-9e241900-a038-11ea-837a-a5c155caf8fb.png)

>>  Pretender supports XHR and Fetch stubbing and is a great lightweight alternative to Polly and also to you if your project does not require persisting capabilities or Node adapters. 

I thought you want to give a message to us that Polly is helpful to project with certain feature.
so  i added a sentence "and also to you"

**Comment by offirgolan** [comment]
Thank you for the suggestion @rlathgml1004 but the current written statement is fine as is.
