### ISSUE TITLE
I translate your Readme.md file! (Korean.ver)

### ISSUE THREAD

**Issue by rlathgml1004** [Netflix/pollyjs#339]
## Description
I translate your Readme.md file.
follow this Link and confirm it please.
thank you.
https://github.com/Netflix/pollyjs/compare/Netflix:master...rlathgml1004:master

**Comment by jasonmit** [comment]
@rlathgml1004 we're unable to officially support Korean officially since we do not speak Korean nor have a translation service setup to maintain changes to the docs going forward.

**Comment by rlathgml1004** [comment]
thak you for confirming my contriburiton.
-----Original Message-----
