### ISSUE TITLE
Mocking server's downstream requests during parallel functional tests

### ISSUE THREAD

**Issue by kweiberth** [Netflix/pollyjs#340]
## Description

Hello, I have a use case I'd like to share and hopefully get some insight into best practices. 

I'm running functional tests via Jest, i.e. spinning up my server, make requests to the server, assert the data. 

I'd like to record and replay mocks from the server process, so I'm spinning up the Polly instance on the server. I'm basically sending the test suite name with each request, and in this way I can assign a recordingName to Polly for each test:

```js
// src/index.ts

let polly;

app.use((req, res, next) => {
  const testName = req.headers['jest-functional-test-name'];
  const mode = req.headers['jest-functional-test-mocks-mode'] || 'replay';

  if (!polly && testName && mode !== 'passthrough') {
    polly = new Polly(testName, { ...pollyConfig, mode });
  }

  next();
});

app.post('/stop-polly', async (req, res) => {
  await polly.flush();
  await polly.stop();
  polly = null;
  return res.status(200).send();
});

```

This works if I run my test files in sequence. However, Jest, by default, runs test files in parallel, and it would be nice to leverage faster test runs (especially when running tests in record mode). 

Unfortunately, I'm having trouble recording and replaying mocks for tests that are running simultaneously and hitting the server at the same time. This is what I tried:

```js
// src/index.ts

const polly = new Polly('initialRecordingName', pollyConfig);

app.use((req, res, next) => {
  const testName = req.headers['jest-functional-test-name'];
  const mode = req.headers['jest-functional-test-mocks-mode'] || 'replay';

  if (mode === 'passthrough') {
    polly.passthrough();
  } else if (mode === 'record') {
    polly.record();
  } else if (mode === 'replay') {
    polly.replay();
  }

  if (testName) {
    polly.server
      .any()
      .filter((req) => {
        return req.headers['jest-functional-test-name'] === testName;
      })
      .recordingName(testName);
  }

  next();
});
```

Basically, I'm passing through the 'jest-functional-test-name' header to all downstream requests from my server, which allows me to use the `recordingName()` functionality along with filter to specify recordingName for each request based on the test from which it originates. 

This seems to work well for recording. However, replaying gets messed up, and I think it's bc of `order`. Let's say we run 2 tests, each of which request our server, which then for each requests makes to 2 requests to downstream services. The `order` value for these two requests should be 0 and 1 in each recording file, but unfortunately they end up being something like 0 and 2 in one file and 1 and 3 in the other file, bc I thnk order is being calculated "globally" as opposed to a single recordingName. Then when we replay, the test fails bc it can't find the correct record for the specific order. 

Does that make sense? It's a little hard for me to figure out exactly what's going on, but I've basically narrowed it down to an issue with order. 

I'm wondering if anyone has any thoughts/suggestions for this use case? I tried finding examples of this, but couldn't find anything.

### Dependencies

```json
{
  "@pollyjs/adapter-node-http": "^4.2.1",
  "@pollyjs/core": "^4.2.1",
  "@pollyjs/node-server": "^4.3.0",
  "@pollyjs/persister-fs": "^4.2.1",
}
```

## Environment

Node.js v10.19.0
darwin 18.7.0
npm 6.14.5

**Comment by offirgolan** [comment]
@kweiberth thanks for the detailed issue. 

> I thnk order is being calculated "globally" as opposed to a single recordingName. Then when we replay, the test fails bc it can't find the correct record for the specific order.

Correct, order is calculated based on all requests that the polly instance has captured.

> It's a little hard for me to figure out exactly what's going on, but I've basically narrowed it down to an issue with order.

If you turn off matching requests by order, does it solve your problem?

**Comment by kweiberth** [comment]
I didn't try it right away bc I figured then my tests wouldn't receive the proper data. In other words, if it doesn't match by order, will it always just return the first one?

I'll try it out though and get back to you.

**Comment by kweiberth** [comment]
@offirgolan this doesn't seem to be working. Once I turn off matching requests by order, then it looks like it's not saving multiple responses, which is necessary for our tests.

I think what you mentioned about making ordering dependent on recording name (or at least providing an option for it?) makes a lot of sense, and it seems like it would help us mock our server's downstream services during parallel functional tests. 

Let me know if you'd like any more information or debugging from me
