### ISSUE TITLE
[adapter-puppeteer] package is broken with Puppeteer 4 - removed prependListener and removeListener

### ISSUE THREAD

**Issue by Georgegriff** [Netflix/pollyjs#345]
## Description

Please read their release notes below before reading:

Puppeteer 4.0 removed its association with Node EventEmitter which this package relies upon https://github.com/puppeteer/puppeteer/releases/tag/v4.0.0

### Shareable Source
adapter-puppeteer relies on the following:prependListener which has been removed in Puppeteer.

It also relies on removeListener which has also been removed.
https://github.com/Netflix/pollyjs/blob/1223ba0dad16bf504074510ac060e7394a4cbac9/packages/%40pollyjs/adapter-puppeteer/src/index.js#L50
https://github.com/Netflix/pollyjs/blob/1223ba0dad16bf504074510ac060e7394a4cbac9/packages/%40pollyjs/adapter-puppeteer/src/index.js#L143

### Error Message & Stack Trace

```
COPY THE ERROR MESSAGE, INCLUDING STACK TRACE HERE
```

### Config

Copy the config used to setup the Polly instance:

```js
new Polly('Recording Name', {
  // config...
});
```

### Dependencies

Copy the @pollyjs dependencies from `package.json`:

```json
{
    "@pollyjs/adapter-puppeteer": "^4.0.4",
    "@pollyjs/core": "^4.0.4",
}
```

## Relevant Links

https://github.com/Netflix/pollyjs/blob/1223ba0dad16bf504074510ac060e7394a4cbac9/packages/%40pollyjs/adapter-puppeteer/src/index.js#L50
https://github.com/Netflix/pollyjs/blob/1223ba0dad16bf504074510ac060e7394a4cbac9/packages/%40pollyjs/adapter-puppeteer/src/index.js#L143

## Environment

Tell us which operating system you are using, as well as which versions of Node.js and npm/yarn. If applicable, include the browser and the corresponding version.

Run the following to get it quickly:

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
npm --version
yarn --version
```

**Comment by arnaugm** [comment]
Hi! I'm interested in providing a fix for this issue, any guidance?
