### ISSUE TITLE
beforePersist event payload (recording) is missing queryString values.

### ISSUE THREAD

**Issue by moltar** [Netflix/pollyjs#347]
## Description

`beforePersist` event payload (recording) is missing `queryString` values.

This is potentially a **security issue**.

I am relying on the recording payload to sanitize it from secrets, before storing the recordings. But a secret (API key) had leaked out in the query string in the CI environment.

### Shareable Source

```js
// Avoid posting hundreds of lines of source code.
// Edit to just the relevant portions.
```

### Error Message & Stack Trace

N/A

### Config

```
Polly.register(NodeHttpAdapter)
Polly.register(FSPersister)
```

Dump recording payload values:

```
  polly.server
    .any()
    .on('beforePersist', (request, recording) => {
      console.log(JSON.stringify(recording, undefined, 2))
    })
```

I am seeing:

```
"queryString": [],
```

Inspect the recording stored on disk:

I'm seeing:

```
          "queryString": [
            {
              "name": "foo",
              "value": "foobarbaz"
            }
          ],
```

### Dependencies

Copy the @pollyjs dependencies from `package.json`:

```json
{
    "@pollyjs/adapter-node-http": "5.0.0",
    "@pollyjs/core": "5.0.0",
    "@pollyjs/persister-fs": "5.0.0",
}
```

## Relevant Links

N/A

## Environment

```
Node.js v12.16.0
darwin 19.4.0
npm: 6.14.5
```

**Comment by offirgolan** [comment]
Apologies for the delay on this @moltar. I'll investigate this issue this week to see whats going on.

**Comment by offirgolan** [comment]
Quick follow up, I tried reproducing this within our tests on both Node and the browser and I was able to see the `queryString` values. Can you provide a reproduction that I can mess around with?

**Comment by moltar** [comment]
I am so sorry. You are right! It was totally a bug in my code that I overlooked. I am sorry for wasting your time, @offirgolan.

**Comment by offirgolan** [comment]
No worries!
