### ISSUE TITLE
[feature request] Simple way of hiding confidential values in the recordings

### ISSUE THREAD

**Issue by Tuuleh** [Netflix/pollyjs#352]
It would be nice to have a configuration option for an easy way to hide confidential values in the recordings. If this is something you don't want to add, it would be very useful to have a section in the documentation that would demonstrate how to do it with the `beforePersist` hook - right now I don't see anything in the official docs about this and combined information from a few different GitHub issues and blog posts to see how to do it.

**Comment by jasonmit** [comment]
The `beforePersist` and `beforeReplay` API docs kind of elude to it in the example:

```js
server.any().on('beforePersist', (req, recording) => {
  recording.request = encrypt(recording.request);
  recording.response = encrypt(recording.response);
});
```

```js
server.any().on('beforeReplay', (req, recording) => {
  recording.request = decrypt(recording.request);
  recording.response = decrypt(recording.response);
});
```

Perhaps this example could be made more prominent under the Examples section.
