### ISSUE TITLE
PollyJS recording API data but still fetching new data from server and replaces the old one it recorded

### ISSUE THREAD

**Issue by vyshnavrajs2019** [Netflix/pollyjs#357]
I am working on an app where I am writing the integration test. I used Pollyjs to mock server response. But yesterday when I ran my tests some of my tests did fail because the data that I was expecting from pollyjs changed. 

`this.polly.configure({ recordIfMissing: true, logging: true });`
I have used the above configuration within the test hook (beforeEach).

I don't understand what is happening but the data that pollyjs returns are changing whenever the server data changes.

**Comment by jasonmit** [comment]
Issue is not clear enough, can you add more details?

**Comment by offirgolan** [comment]
@vyshnavrajs2019 if the recordings aren't being replayed, its most likely that you have some sort of header value that is dynamic to every test execution. I would take a look at the [`matchRequestsBy`](https://netflix.github.io/pollyjs/#/configuration?id=matchrequestsby) config option and try to exclude anything that could be changing.

**Comment by offirgolan** [comment]
Closing this issue due to no response. @vyshnavrajs2019 feel free to reopen if you still need help with this issue.
