### ISSUE TITLE
Extracted function for generating id for an entry

### ISSUE THREAD

**Issue by EsterDanielYtterbrink** [Netflix/pollyjs#362]
Hi, I want to make a pr, but saw that you want me to create an issue first. Hope that I am doing it correctly.
I would love to contribute. 

## Description

I am writing.a persister that anonymise the data before persisting it. https://github.com/Praqma/filter-fs-persister 
The reason for this is that we use polly.js togehter with an api that contains personal information, and do not want that stored in more places than we have to.

Now I would like to add the option to use test environment once the request is recorded, replacing sensitive data in the request header and in the recording. If I filter out the data before persisting, the id for the entity will be wrong, and will not be found the next time the test is run. So I need to change the id as well, and that code is in the private inners of polly.js, that I do not want my external library to mess with even if I could access it. (Copy the code is a temporary solution.)

So I would like to refactor and extract the function that calculates the entity id and make it available outside the -private/request.js. Then I could safely depend on it in my persister.

An alternative would be to create a new adapter as well, but that would limit the use of my persister. 

### Code I would like to extract parts of

```js
  async _identify() {
    const polly = this[POLLY];
    const { _requests: requests } = polly;
    const { matchRequestsBy } = this.config;

    this.identifiers = {};

    // Iterate through each normalizer
    keys(NormalizeRequest).forEach(key => {
      if (this[key] && matchRequestsBy[key]) {
        this.identifiers[key] = NormalizeRequest[key](
          this[key],
          matchRequestsBy[key],
          this
        );
      }
    });

    // Emit the `identify` event which adapters can use to serialize the request body
    await this[EVENT_EMITTER].emit('identify', this);

    // Freeze the identifiers so they can no longer be modified
    freeze(this.identifiers);

    // Guid is a string representation of the identifiers
    this.id = md5(stringify(this.identifiers));

    // Order is calculated on other requests with the same id and recording id
    // Only requests before this current one are taken into account.
    this.order =
      matchRequestsBy.order && !this.shouldPassthrough && !this.shouldIntercept
        ? requests
            .slice(0, requests.indexOf(this))
            .filter(r => r.id === this.id && r.recordingId === this.recordingId)
            .length
        : 0;
  }

```

**Comment by jasonmit** [comment]
Have you investigated using the event [`beforepersist`](https://netflix.github.io/pollyjs/#/server/events-and-middleware?id=beforepersist) to strip out the sensitive information you're concerned about persisting?

Example:

```js
// note: you can scope this behavior via `.get()`, `server..get('/users/:id')`, `server.get('/secrets/*path')`, etc.
pollyInstance.server.any().on('beforePersist', (req, recording) => {
  recording.request.headers = recording.request.headers.filter(({ name }) => name !== 'auth-token'));
});
```

**Comment by EsterDanielYtterbrink** [comment]
I have tried that, and it does remove sensitive data from the recordings. But it still uses the old id, so I need to use the sensitive data in the requests also when not recording.

I want the tests to run also for someone who does not have access to our production environment keys.

**Comment by jasonmit** [comment]
> I want the tests to run also for someone who does not have access to our production environment keys. For that I need the id to be recalculated after the parameters for the request is changed.

I believe you want to use matchRequestsBy and exclude the headers you don't want to match on:
https://netflix.github.io/pollyjs/#/configuration?id=headers

**Comment by offirgolan** [comment]
Im gonna go ahead and close this issue. @EsterDanielYtterbrink please feel free to reopen if the above solution didnt work for you.

**Comment by ashutoshvyas45** [comment]
How does this work for body. If I have a requirement to remove some keys from body. 
As after removing the key before persisting and also from matchRequestBy the entity id is changing.
