### ISSUE TITLE
How to use a single recording across multiple test cases automatically without using recordingName

### ISSUE THREAD

**Issue by saarimz** [Netflix/pollyjs#365]
## Description

Hey y'all I have two separate test suites (that live in different files) that make a request to the same endpoint. I want to be able to use a single recording for both, without having to explicitly pass `recordingName`. Basically, I want Polly to be able to match a recording based on all the `matchRequestsBy` parameters and exclude `recordingName` when looking up a recording, similar to how [VCRpy](https://github.com/kevin1024/vcrpy) works. The use case is I have a redux-thunk action that makes a HTTP request, and then a component that dispatches the thunk action in a separate test, but both make the same underlying HTTP request, so I'd like to be able to have them share the same recording.

I've posted an example below where I try to use the same recording between test suites. Say I have `getSubscriptionAgreementWebviewUrl` recorded, when I explicitly set the `recordingName` on `loginUser` to be the name of the recording, my tests pass. However when I don't explicitly set a `recordingName` it fails as it can't find the recording.

I've looked at the docs and I'm not sure how to go about it. The only lead I had was:
- to extend FSPersister to rewrite the logic of how to save and retrieve recordings

### Shareable Source

example of two different test suites:

```
// getSubscriptionAgreementWebviewUrl.test.js
describe('getSubscriptionAgreementWebviewUrl', () => {
  only('attempts login', async () => {
    const credentials ='hello@there.com';
    await request.post(`${HOST}/verification-code`)
    .send({
      email: credentials,
      password: credentials,
    });
  })
```

```
// loginUser.test.js
describe('loginUser', () => {
  only('creates store with logged in user', async () => {
    const credentials ='hello@there.com';
    await request.post(`${HOST}/verification-code`)
    .send({
      email: credentials,
      password: credentials,
    });
  })

```

### Error Message & Stack Trace

```
PollyError: [Polly] [adapter:node-http] Recording for the following request is not found and `recordIfMissing` is `false`.
```

### Diff between the two recordings if I record both

```
--- a/recordings/DocusignScreen_734456741/renders-with-webview-after-url-is-obtained_4096335866/recording.har
+++ b/recordings/getSubscriptionAgreementWebviewUrl_1249165306/creates-store-with-logged-in-user_1971070039/recording.har
@@ -1,6 +1,6 @@
 {
   "log": {
-    "_recordingName": "loginUser/creates store with logged in user",
+    "_recordingName": "getSubscriptionAgreementWebviewUrl/attempts login",
     "creator": {
       "comment": "persister:fs",
       "name": "Polly.JS",
@@ -52,7 +52,7 @@
           "content": {
             "mimeType": "application/json",
             "size": 114,
-            "text": "{\"verification_token\":\"foo"}"
+            "text": "{\"verification_token\":\"bar\"}"
           },
           "cookies": [],
           "headers": [
@@ -66,7 +66,7 @@
             },
             {
               "name": "date",
-              "value": "Fri, 25 Sep 2020 19:45:24 GMT"
+              "value": "Fri, 25 Sep 2020 19:43:42 GMT"
             },
             {
               "name": "content-type",
@@ -107,8 +107,8 @@
           "status": 200,
           "statusText": "OK"
         },
-        "startedDateTime": "2020-09-25T19:45:24.017Z",
-        "time": 629,
+        "startedDateTime": "2020-09-25T19:43:41.388Z",
+        "time": 852,
         "timings": {
           "blocked": -1,
           "connect": -1,
@@ -116,7 +116,7 @@
           "receive": 0,
           "send": 0,
           "ssl": -1,
-          "wait": 629
+          "wait": 852
         }
       }
     ],
```

### Config

Copy the config used to setup the Polly instance:

```js
const defaultConfig = {
  adapters: ['node-http'],
  persister: 'fs',
  persisterOptions: {
    keepUnusedRequests: false,
    fs: {
      recordingsDir: getDefaultRecordingDir(),
    },
  },
  mode,
  recordIfMissing: false,
  recordFailedRequests: true,
  expiryStrategy: 'warn',
  // insulate the tests from differences in session data. we use order and
  // url to match requests to one another, which we did previously with an
  // internal fork of LinkedIn's Sepia VCR. This should be fine for deterministic
  // requests, and you can circumvent non-deterministic stuff by manipulating
  // things in the Polly Server: https://netflix.github.io/pollyjs/#/server/overview?id=overview
  matchRequestsBy: {
    headers: false,
    body: true,
    order: false,
    url: {
      protocol: true,
      username: false,
      password: false,
      hostname: true,
      port: false,
      pathname: true,
      query: true,
      hash: true,
  },
  },
};
```

### Dependencies

Copy the @pollyjs dependencies from `package.json`:

```json
	@pollyjs/adapter-node-http": "^4.0.3",
    "@pollyjs/core": "^4.0.2",
    "@pollyjs/persister-fs": "^4.0.2",
```

## Relevant Links

- If your project is public, link to the repo so we can investigate directly.
- **BONUS POINTS:** Create a [minimal reproduction](http://stackoverflow.com/help/mcve) and upload it to GitHub. This will get you the fastest support.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js and npm/yarn. If applicable, include the browser and the corresponding version.

Run the following to get it quickly:

```
npm --versionNode.js v13.6.0
darwin 18.5.0
6.13.4
```

**Comment by offirgolan** [comment]
You can do this by creating a server middleware. The function to override the recording name is currently private API but that's just because I havent really thought of a use case for it. I can make it public if this works for you:

```js
polly.server.any().on('request', (req) => {
  // make sure to replace '/' with something or polly will create subdirectories
  req._overrideRecordingName(req.url.replace('/', '-'));
});
```

**Comment by saarimz** [comment]
> You can do this by creating a server middleware. The function to override the recording name is currently private API but that's just because I havent really thought of a use case for it. I can make it public if this works for you:
> 
> ```js
> polly.server.any().on('request', (req) => {
>   // make sure to replace '/' with something or polly will create subdirectories
>   req._overrideRecordingName(req.url.replace('/', '-'));
> });
> ```

that would be amazing @offirgolan!
