### ISSUE TITLE
Regression: setting recordingName is ignored

### ISSUE THREAD

**Issue by rijnhard** [Netflix/pollyjs#366]
## Description

Affects v5 and still works on v4.3.0.
basically, no matter if you specify the recording name in v5 or not, it always generates the recording in a fully namespace directory. not according to the set recordingName.

### Shareable Source

```js
describe('.thing', function () {
    setupPolly({
        adapters        : ['node-http'],
        persister       : 'fs',
        mode            : 'replay',
        recordIfMissing : true,
        persisterOptions: {
            keepUnusedRequests: true,
            fs                : {
                recordingsDir: POLLY_RECORDINGS
            }
        },
        matchRequestsBy: {
            body   : true,
            headers: false,
            order  : false
        }
    });

  it('should successfully send', async function() {
    this.polly.server
      .post(APP_URL)
      .recordingName('200-Raw0');
  });
});
```

```json
{
  "@pollyjs/core": "^5.0.0",
  "@pollyjs/adapter-node-http": "^5.0.0",
  "@pollyjs/persister-fs": "^5.0.0"
}
```

## Environment
```
Node.js v14.12.0
linux 5.4.0-47-generic
npm 6.14.8
```

**Comment by offirgolan** [comment]
I tried to reproduce this but using `recordingName` worked as expected:

```js
const { Polly } = require('@pollyjs/core');
const NodeHttpAdapter = require('@pollyjs/adapter-node-http');
const FSPersister = require('@pollyjs/persister-fs');
const fetch = require('node-fetch');

Polly.register(NodeHttpAdapter);
Polly.register(FSPersister);

(async function () {
  const polly = new Polly('polly-recording-name-test', {
    adapters: ['node-http'],
    persister: 'fs',
    mode: 'replay',
    recordIfMissing: true,
    persisterOptions: {
      keepUnusedRequests: true,
    },
    matchRequestsBy: {
      body: true,
      headers: false,
      order: false,
    },
  });

  polly.server
    .any('https://jsonplaceholder.typicode.com/*')
    .recordingName('jsonplaceholder');

  await fetch('https://jsonplaceholder.typicode.com/todos/1');

  await polly.stop();
})();
```

Generated `recordings/jsonplaceholder_1752295936/recording.har`.

This can be an issue with your `polly.server.post` matcher or its an actual issue with `setup-polly-jest`. Does something like ```this.polly.server.post(`${APP_URL}/*`)``` work?

**Comment by rijnhard** [comment]
It was exactly that! I was matching against the wrong URL, I only figured this out after a full day and a meeting with a vendor. 
This leads me to another request, for configuration purposes there should be a way to switch polly into "debug" mode in order to see where exactly the match is failing.

For example:
`cant find a request matching the URL ${request url}`
`request for recording  ${recording name} partially matched a request but failed to match headers <print diff>`
... etc
