### ISSUE TITLE
Potential Bugs and Anti-Patterns in the Codebase

### ISSUE THREAD

**Issue by HarshCasper** [Netflix/pollyjs#374]
## Description 

I ran DeepSource Static Code Analysis upon the Project, the results for which are available [here](https://deepsource.io/gh/HarshCasper/pollyjs/). 

The Static Code Analysis Tool found potential bugs and anti-patterns in the Code, that can be detrimental at a later point of time with respect to the Project. DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. 

Some of the notable issues are: 

- Usage of undeclared variables [here](https://deepsource.io/gh/HarshCasper/pollyjs/issue/JS-0125/)
- Returning values from setters [here](https://deepsource.io/gh/HarshCasper/pollyjs/issue/JS-0037/)
- Accessed Object Properties are restricted [here](https://deepsource.io/gh/HarshCasper/pollyjs/issue/JS-0110/)
- Unnecessary `catch` clauses found [here](https://deepsource.io/gh/HarshCasper/pollyjs/issue/JS-0112/)

There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

**Comment by offirgolan** [comment]
Thanks for this, a lot of these have been resolved so Im going to go ahead and close this issue. Feel free to reopen.
