### ISSUE TITLE
ES Modules build has some error

### ISSUE THREAD

**Issue by PeterChen1997** [Netflix/pollyjs#384]
## Description

Hi bro~ I use pollyjs in my js library, i found that when i check esm build dist, the dist didn't import the node_modules' pkg, i check the build config and found the esm is build in node config, not the browser config

```js
// @pollyjs/adapter-xhr/dist/es/pollyjs-adapter-xhr.js

/**
* @pollyjs/adapter-xhr v5.1.0
*
* https://github.com/netflix/pollyjs
*
* Released under the Apache-2.0 License.
*/
import Adapter from '@pollyjs/adapter';
import { isBufferUtf8Representable } from '@pollyjs/utils';
import bufferToArrayBuffer from 'to-arraybuffer';

```

I cannot use the esm dist in browser, is some problem in my using?

**Comment by offirgolan** [comment]
If you're trying to use this lib directly in the browser, you should be importing the umd build ([see here](https://github.com/Netflix/pollyjs/blob/master/packages/%40pollyjs/core/package.json#L7))

**Comment by PeterChen1997** [comment]
> If you're trying to use this lib directly in the browser, you should be importing the umd build ([see here](https://github.com/Netflix/pollyjs/blob/master/packages/%40pollyjs/core/package.json#L7))

thx bro
