### ISSUE TITLE
req.setHeader is not a function

### ISSUE THREAD

**Issue by arackaf** [Netflix/pollyjs#446]
## Description

I know the details are light here, but I wanted to open this issue in the off chance anyone might know what's going on, or even to provide an outlet for others who are having the same problem to chime in, and who knows, maybe even share a solution.

When trying to upgrade Jest from 24, to 26 or 27, we see some Polly tests failing, in that the request object that winds up in Polly is undefined, leading to a `req.setHeader is not a function` error. 

The stack trace is below.

Reproducing this is brutally hard. When we attempt to just re-run the failed tests, they all pass. We're thinking maybe there's some bizarre async race condition somewhere.

![image](https://user-images.githubusercontent.com/11261266/150379188-369882c8-a87a-49f4-97bc-4507d8b872e8.png)

### Shareable Source

I wish we had one.

### Error Message & Stack Trace

See the screenshot above.

### Config

```js
import * as path from 'path';
import * as fs from 'fs';
import { Polly } from '@pollyjs/core';
import NodeHttpAdapter from '@pollyjs/adapter-node-http';
import { ZipFSPersister, ZipFSPersisterOptions } from './ZipFSPersister';

// @ts-ignore
const testPath: string = global.jasmine.testPath;
const dirname = path.dirname(testPath);
const basename = path.basename(testPath);
const isCI = !!process.env.CI;

export const polly = new Polly(basename, {
  mode: 'replay',
  adapters: [NodeHttpAdapter],
  persister: ZipFSPersister,
  persisterOptions: {
    keepUnusedRequests: false,
    ZipFSPersister: {
      recordingsDir: `${dirname}/__recordings__`,
      preventPersist: isCI, // prevent persisting in CI
    } as ZipFSPersisterOptions,
  },
  recordIfMissing: false,
  recordFailedRequests: true,
  matchRequestsBy: {
    order: false,
    headers: {
      exclude: ['user-agent'],
    },
  },
});

function recordingExists() {
  return (
    polly.persister instanceof ZipFSPersister &&
    fs.existsSync(polly.persister.getFileName(polly.recordingId))
  );
}

// record if not CI and no recording
if (!isCI && !recordingExists()) {
  polly.record();
}

afterAll(async () => {
  // wait for existing requests to resolve
  // https://netflix.github.io/pollyjs/#/api?id=flush
  await polly.flush();
  // synchronously disconnect for all connected adapters
  // https://netflix.github.io/pollyjs/#/api?id=pause
  polly.pause();
  // persist recordings and disconnect all plugins
  // https://netflix.github.io/pollyjs/#/api?id=stop-1
  await polly.stop();
});
```

## Environment

Node 16

**Comment by arackaf** [comment]
@offirgolan I appreciate that - and I hope you didn't spend much time trying. I figured you wouldn't be able to. This appears related to some crazy stuff we have in a fairly large monorepo. I figured I'd open the case in the off chance someone might know something. Feel free to close

**Comment by offirgolan** [comment]
Haha all good, I'll close for now. Feel free to reopen if you can reproduce.
