### ISSUE TITLE
Add ability to configure window in fetch adapter.

### ISSUE THREAD

**Issue by marcuslindfeldt** [Netflix/pollyjs#56]
In E2E frameworks like [cypress](https://www.cypress.io/) `fetch` is attached to an injected window object like this:

```js
cy.visit('my/pathname/', {
  onBeforeLoad: win => { ... }
})
```

Currently the fetch adapter expects `fetch` to be attached to `self` but in this case it's not so it would be nice if I could supply the window object to the fetch adapter or Polly constructor. E.g.
```js
cy.visit('my/pathname/', {
  onBeforeLoad: win => {
    const polly = new Polly('my-polly-recording', {
      adapters: [['fetch', FetchAdapter.create({ window: win })]]
    });
  }
})
```

**Comment by jasonmit** [comment]
https://github.com/Netflix/pollyjs/pull/54 may partially resolve this in that Polly is no longer fixed on `self` and will `global` becomes a pointer to the result of:

```js
var _global = typeof global !== "undefined" ? global :
            typeof self !== "undefined" ? self :
            typeof window !== "undefined" ? window : {} 
```

If not, this is a reasonable ask and something we can support.

**Comment by jasonmit** [comment]
#60 resolves this.  Will be in the next release.

**Comment by jasonmit** [comment]
Reopening since it doesn't completely resolve this yet.

**Comment by PinkyJie** [comment]
Hi @marcuslindfeldt , just noticed you have tried to use Pollyjs inside Cypress, did you get some progress? I did some experiment last week trying to use Pollyjs in Cypress to record HTTP requests. With the latest Pollyjs, `fetch` can be injected successfully, but `XMLHttpRequest` can't. Any clue on this?

Here is my implementation.
https://github.com/PinkyJie/cypress-pollyjs-plugin/blob/master/example/cypress/support/polly.js

**Comment by marcuslindfeldt** [comment]
@PinkyJie I haven't tried it XMLHTTPRequest since we only use fetch in our apps. Our solution is a bit different though.
https://gist.github.com/marcuslindfeldt/4d6dcb528e6c1ab734a0f78e609eff6a

Basically we create a new mockVisit command where you can add a callback to attach your polly mock endpoints.

So in your tests you can do something like this:
```js
cy.mockVisit('/login', polly => {
  polly.server.post('/user/login').intercept((req, res) => {
    res.status(HttpStatus.OK).json({
      status: HttpStatus.OK
    });
  });
});
```
