### ISSUE TITLE
How do I use Polly.js for pure request mocking (no recording, no-replaying, etc)

### ISSUE THREAD

**Issue by NullVoxPopuli** [Netflix/pollyjs#72]
The current thing I'm trying to mock is my current-user endpoint.

I have `/api/users/current-user` and my mock for it: 
```ts
    const { server } = this.polly;

    server.get('/api/users/current-user').intercept((req, res) => {
      res.status(200);
      res.json({
        data: {
          attributes: { id: 1, auth0Id: 'my-fake-auth0Id' }
        }
      });
    });
```
This project is open source, and the above snippet can be viewed here: https://github.com/sillsdev/appbuilder-portal/blob/f76a67e1600c36fff1de8eb2ff2bbbeafc91517b/source/SIL.AppBuilder.Portal.Frontend/tests/helpers/auth.ts#L16:L24

The configuration for polly is configured as follows:
```ts
import { Polly } from '@pollyjs/core';

// inspiration from:
// https://github.com/Netflix/pollyjs/blob/master/packages/%40pollyjs/core/src/test-helpers/mocha.js
export function setupRequestInterceptor(config: any = {}) {
  beforeEach(function() {
    const name = generateRecordingName(this);
    const pollyConfig = {
      mode: 'passthrough',
      logging: true,
      recordIfMissing: false,
      matchRequestBy: {
        order: false,
        url: {
          port: false,
          hostname: false,
          protocol: false,
        }
      },
      ...config
    };

    this.polly = new Polly(name, pollyConfig);

    const { server } = this.polly;

    // by default? stub out auth0 so that auth0/lock.js doesn't
    // try to contact auth0 during testing.
    server.options('/api/*anypath').intercept((req, res) => {
      console.log('req', req);
      req.headers.Allow = 'OPTIONS, GET, HEAD, POST, PUT, PATCH, DELETE, TRACE';
    });

    server.get('https://cdn.auth0.com/*path').intercept((req, res) => {
      res.status(200);
      res.json({});
    });
  });

  afterEach(async function() {
    await this.polly.stop();
  });
}


// helpers stolen from:
// https://github.com/Netflix/pollyjs/blob/master/packages/%40pollyjs/core/src/test-helpers/lib.js
export function generateRecordingName(context) {
  // ... omitted for brevity
}
```

so, when my test makes a call to `/api/users/current-user` (as it would on a route that requires authentication), I get `NOT FOUND` errors:

![image](https://user-images.githubusercontent.com/199018/43079290-b1435d12-8e5a-11e8-9827-7b8818bdefa3.png)

![image](https://user-images.githubusercontent.com/199018/43079303-bac1cd56-8e5a-11e8-8f92-5cb18ba711ca.png)

I'm using karma + mocha for my tests, so `http://localhost:9876/debug.html` is the address where I run my tests in debug mode (which is why the full URL for the current-user route has localhost:9876).

So, am I doing anything obviously wrong?

**Comment by NullVoxPopuli** [comment]
I just noticed that @pollyjs has since hit version 1.0.0, I was on 0.2.1 -- I'll try upgrading and see what happens and update my code to match the latest docs as well.

**Comment by NullVoxPopuli** [comment]
By upgrading, and realizing I don't know how to code (as demonstrated via https://github.com/Netflix/pollyjs/issues/73) I have request stubbing working now with `1.0.0`. Thanks, Netflix :)

**Comment by NullVoxPopuli** [comment]
@offirgolan it is not.
Also, I've changed the configuration for that host to:

```ts
    server.host('https://cdn.auth0.com', () => {
      server.any().on('request', (req, res) => {
        res.status(200);
        res.json({});
      });
    });
```


Also, my organization endpoint was me being silly again.

I just needed to set my 'ORM''s fetch to the same one that polly is mocking.

I'm using Orbit.js (apollo-quality level of client for rest apis, specifically `json:api`)

This is what I had to do to get my api endpoint working:

```ts
import { Polly } from '@pollyjs/core';
import * as FetchAdapter from '@pollyjs/adapter-fetch';

import Orbit from '@orbit/data';

Polly.register(FetchAdapter);

export function setupRequestInterceptor(config: any = {}) {
  beforeEach(function() {
    // some config setup

    this.polly = new Polly(name, pollyConfig);

     // this was the key. After instantiating polly, I needed to set
     // Orbit's fetch to the window fetch, which has been taken over by polly
     // (and also happens to be why only one instance of polly can be active at a given time)
    Orbit.fetch = window.fetch.bind(window);

```

**Comment by NullVoxPopuli** [comment]
So, @offirgolan I think this issue has morphed into:

"How do I mock 3rd party domains? -- seems to not be working as demonstrated in the docs"

**Comment by offirgolan** [comment]
This snippet wont work. 

```js
server.host('https://cdn.auth0.com', () => {
      server.any().on('request', (req, res) => {
        res.status(200);
        res.json({});
      });
    });
```

But this should:

```js
server.host('https://cdn.auth0.com', () => {
      server.get('*').intercept('request', (req, res) => {
        res.status(200);
        res.json({});
      });
    });
```

> "How do I mock 3rd party domains? -- seems to not be working as demonstrated in the docs"

If the request is not being picked up by Polly means that it was made outside of Polly's control. There are a couple of ways this could happen:

- It could be that the CDN request is being made via XHR and not fetch. If so, you will have to install and connect to the XHR adapter. `polly.configure({ adapters: ['fetch', 'xhr' ] });`
- It could be that you are instantiating polly after that request has been made

**Comment by NullVoxPopuli** [comment]
hmm, it must be that auth0 is using their own method of request-making. I actually have both fetch and xhr enabled. but, like I learned with Orbit, the original fetch may have been copied.

**Comment by NullVoxPopuli** [comment]
ok, yeah. auth0 uses `superagent` for making their requests... sigh

**Comment by NullVoxPopuli** [comment]
https://github.com/auth0/auth0.js/blob/fb53e8c318416ab1b29c99907a9e3cf63fe25164/src/helper/request-builder.js

**Comment by offirgolan** [comment]
@NullVoxPopuli are you running Polly in the browser or in Node?

**Comment by NullVoxPopuli** [comment]
@offirgolan in the browser.
