### ISSUE TITLE
Host is stripped from protocol-relative urls

### ISSUE THREAD

**Issue by 44px** [Netflix/pollyjs#76]
**How to reproduce:**
1. Have app on `http://my-app.dev`
1. Make request to protocol-relative url `//api.dev/posts/1`

**Expected behavior**
Polly proxies this request to `api.dev` and writes response.

**Actual behavior**
Polly strips host from `//api.dev/posts/1` making it into `/posts/1` and then trying to send request to `http://my-app.dev/posts/1` instead of original url.

I found two places in code where url is modified. Here is one which caused desribed behavior:
https://github.com/Netflix/pollyjs/blob/73026d446cf207ab814db5fb653bdfee40cfe682/packages/%40pollyjs/core/src/-private/request.js#L53-L60

Seems like [is-absolute-url](https://www.npmjs.com/package/is-absolute-url) check here can be swapped with custom implementation supporting protocol-relative urls

**Comment by offirgolan** [comment]
@44px thanks for the detailed issue! A fix has been published with `v1.1.0` of `@pollyjs/core`.

**Comment by 44px** [comment]
@offirgolan, great, thank you for quick fix!
