### ISSUE TITLE
Origins Question, What does Polly.JS offer over VCR/etc?

### ISSUE THREAD

**Issue by lenards** [Netflix/pollyjs#77]
I was curious if there was anywhere that the origin of Polly was noted. I know that there are record/replay libraries in Ruby ([vcr](https://github.com/vcr/vcr), [betamax](https://github.com/betamaxteam/betamax)) and Python ([VCR.py](https://github.com/kevin1024/vcrpy), [cassette](https://github.com/uber/cassette)). Was the desire to have a pure Node.js implementation? Were the aspects that were not present in the existing efforts that triggered the need for Polly.JS? 

I ask with a sincere desire to understand. I am not involved, nor associated, with any such project. As a community member, it helps me discern and select among a range of sources. I don't know if it makes sense to tag the creators (Jason Mitchell & Offir Golan) or not, so I'll leave that as a mention. 

Thank you for making this available to the wider open source community.

**Comment by jasonmit** [comment]
We're aware of the Ruby/Python implementations and we use Ruby's VCR at Netflix.

This tool is geared towards use within a browser and/or Node.  None of the tools above would be helpful in those runtimes.  

There are great options out there in the JS community, and we compared all the ones we knew and were able to discover (i.e., pretender, nock).

In every case, bending the existing libraries to work for our use case would have been far more difficult than to start fresh with all these ideas in mind:

* works with fetch, xhr, puppeteer
* persists to the file system, rest server, local storage
* node & browser supported
* a client server API
* persisters and adapters are extensible

Hopefully that gives you a glimpse into the origin.  Feel free to ask more specific questions, happy to answer them the best I can.

**Comment by lenards** [comment]
Your thoughtful response definitely gives insight on the origin. I appreciate you offering it. 

Thank you.
