### ISSUE TITLE
[Question] Recommended usages

### ISSUE THREAD

**Issue by patrickberkeley** [Netflix/pollyjs#79]
Would you recommend / do you use Polly for end-to-end tests? Meaning tests that are intended to test both UI and API functionality.

If yes, do you have any patterns you follow?

If no, why not?

**Comment by jasonmit** [comment]
I could see it being used in E2E tests.

Not so much the persisting aspect, but certainly the interceptor API.  Off the top of my head, suppressing analytic calls and asserting some aspect of a request/response.

**Comment by patrickberkeley** [comment]
Okay thanks, @jasonmit.
