### ISSUE TITLE
npm run test - throws error

### ISSUE THREAD

**Issue by vittalas** [Netflix/pollyjs#83]
$ npm run test

> @ pretest /Users/svittalagupta/plugins/poly/pollyjs
> yarn server:build

yarn run v1.7.0
$ yarn build --scope=@pollyjs/node-server --scope=@pollyjs/utils
$ lerna run build --ignore=@pollyjs/ember --parallel --scope=@pollyjs/node-server --scope=@pollyjs/utils
lerna info version 2.11.0
lerna info versioning independent
lerna info scope [ '@pollyjs/node-server', '@pollyjs/utils' ]
lerna info ignore @pollyjs/ember
lerna info run in 2 package(s): npm run build
@pollyjs/node-server: $ npm-run-all clean rollup
@pollyjs/utils: $ npm-run-all clean rollup
@pollyjs/utils: /bin/sh: npm-run-all: command not found
@pollyjs/node-server: /bin/sh: npm-run-all: command not found
@pollyjs/utils: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@pollyjs/node-server: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@pollyjs/node-server: error Command failed with exit code 127.
@pollyjs/utils: error Command failed with exit code 127.
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run build
lerna ERR! /bin/sh: npm-run-all: command not found
lerna ERR! error Command failed with exit code 127.
lerna ERR! 
lerna ERR! $ npm-run-all clean rollup
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/Users/svittalagupta/plugins/poly/pollyjs/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
{ Error: Command failed: yarn run build
/bin/sh: npm-run-all: command not found
error Command failed with exit code 127.

$ npm-run-all clean rollup
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/Users/svittalagupta/plugins/poly/pollyjs/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '$ npm-run-all clean rollup\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr: '/bin/sh: npm-run-all: command not found\nerror Command failed with exit code 127.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run build',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ pretest: `yarn server:build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ pretest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/svittalagupta/.npm/_logs/2018-07-31T04_29_30_662Z-debug.log

**Comment by offirgolan** [comment]
> lerna ERR! /bin/sh: npm-run-all: command not found

This seems to be the issue. Did you run `yarn install` and `yarn bootstrap` before running the test script?

**Comment by vittalas** [comment]
phew figured that out lately, documentation could have helped. (i can contribute if required).
Also how can i run the integration tests in this folder : /Users/svittalagupta/plugins/poly/pollyjs/tests/integration/adapter-browser-tests.js

**Comment by offirgolan** [comment]
@vittalas instructions on how to get started with the repo can be found [here](https://github.com/Netflix/pollyjs/blob/master/CONTRIBUTING.md). Is there anything missing from that page that you had to figure out on your own?

> Also how can i run the integration tests in this folder

The files in there are common test cases that are used by the individual packages. Those are not meant to be run outside of those contexts.

**Comment by vittalas** [comment]
Thanks @offirgolan for a very quick response ! I am actually looking at using this for the similar use case example mentioned here : https://netflix.github.io/pollyjs/#/README?id=usage.
1. Login to my application by providing the user id and passwd,
2. intercept the calls using the adapters

Can you providing some docs around it as that woould be of great help for me to get started !

**Comment by jasonmit** [comment]
https://netflix.github.io/pollyjs/#/server/overview documents the intercepting/mocking API.

Closing since this is an education topic.  The docs will continue to improve (we've received a lot of feedback on this.)

Feel free to open issues with specific questions where the docs are lacking or contributing to improving them.

Thanks!
