### ISSUE TITLE
Examples of Polly.js with Selenum/WebDriver would be fantastic

### ISSUE THREAD

**Issue by paul-hammant** [Netflix/pollyjs#84]
Not only a Node.js+WebDriver.js example, but Java, Python, Ruby and C# ones too, with their respective Selenium/WebDriver bindings.

To make it easy for authors of these examples, tech from http://todobackend.com/ is a decent starting point, like I did for https://paulhammant.com/2017/02/05/a-16-second-java-webapp-build-including-webdriver-tests/. In that case I didn't use a mocking technology like Mountebank, I wove in my own mocks interaction into the in-JVM model, and interoperated with them directly during the UI-clicking test execution.

**Comment by jasonmit** [comment]
This is not supported so I have no examples to share.

**Comment by jasonmit** [comment]
> The technology is for Node.js builds only?

Yes and a browser build.

**Comment by paul-hammant** [comment]
OK, here's the larger field (open source): 

Mountebank (http://www.mbtest.org/) - records/playsback/mocks **arbitrary** TCP/IP conversations. Naturally stores all conversations in JSON which perfect for source control and repeatability. It is written in NodeJs but usable from any other language in record or playback form, as long as that tech can control processes.

Others:

* https://github.com/SpectoLabs/hoverfly (London startup)
* https://github.com/tomakehurst/wiremock (established, Java eco-system)
* https://github.com/epam/Wilma - from EPAM (a big FS consultancy)
* https://github.com/BaiduQA/terminator - from Baidu
* https://github.com/Nike-Inc/bokor - from a division of Nike

Commercial:

* CA Lisa - https://www.ca.com/gb/products/ca-service-virtualization.html
* Parasoft Virtualize - https://www.parasoft.com/products/virtualize

There a probably others.

**Comment by jasonmit** [comment]
Thanks for clarifying.

PollyJS sits a bit higher than recording low-level TCP/IP interactions.  It's geared more towards recording/replaying HTTP requests, which unlocks features like the [client-side "server" API](https://netflix.github.io/pollyjs/#/server/overview).

Really useful info though.  Will continue to look at these to see how we can improve interop between other langs.  PRs or suggestions welcome if you have experience in this area.

**Comment by paul-hammant** [comment]
OK, sorry for being confused about what PollyJS is. I've been table-thumping for this field of technologies (is a process, speaks HTTP* like the real thing would, is manipulable via a back door) for many years. When I first head abut PollyJS I thought it was like Mountebank, but from Netflix rather than ThoughtWorks.

* not just HTTP, of course.
