### ISSUE TITLE
[Question] Creating nearly identical records with different date headers.

### ISSUE THREAD

**Issue by typical000** [Netflix/pollyjs#86]
Hello everybody! polyJs is awesome, but I have a little question (maybe I misundersand something or how it works, or not :))
Suppose, we have following code:
`````````````````````````````````````````````js
new Polly(recordingName, {
    adapters: ['puppeteer'],
    persister: ['fs'],
    adapterOptions: {
        puppeteer: { page }
    },
    persisterOptions: {
        fs: {
            recordingsDir: 'tests/__recordings__',
        },
    },
    matchRequestsBy: {
        headers: {
            exclude: [
                'x-csrf-token',
                'user-agent',
                'date',
            ],
        },
        url: {
            port: false,
            hostname: false,
            protocol: false,
        },
        order: false,
    },
});
`````````````````````````````````````````````
And, if I run the same test in diffrent dates (for e.g. yesterday and today), I recieve in my `recording.har`
duplicated entries that are different only in few fields (note: it's response headers):
![diff](https://user-images.githubusercontent.com/2428765/43700547-b39cdf1e-995b-11e8-814a-4a2660524b97.png)

I guess that due to `date` header difference my recordings are considered different.
So, the question:
If I explictly set exclude rule for 'date' header during Polly initialization - why I doesn't work?
Or it is intended for another thing?

Thank you.

**Comment by offirgolan** [comment]
> If I explictly set exclude rule for 'date' header during Polly initialization - why I doesn't work?

The headers you've excluded are only removing them from how create the GUID for that specific request (which seems to be working according to your screenshot). The headers are not removed from the final recording. 

Is this happening when you are rerecording your tests? Or are you just rerunning the tests which causes this diff?

**Comment by typical000** [comment]
I'm sorry, it was my fault.
I have recorded first time without `date` header exlusion, and on second run I have added it.
For this reason, I think, there were duplicated recordings.
After removing previous recodings all seems to work perfectly.

So we can close this topic. Thank you!
