### ISSUE TITLE
Turning on Polly makes puppeteer do hundreds of requests

### ISSUE THREAD

**Issue by meikoudras** [Netflix/pollyjs#87]
I am using jest + puppeteer to run tests. I am trying to use polly to record and serve requests to our API  when running integration tests.

What happens when i turn on Polly to record our requests is that it starts running the same request for hundreds of times.

The packages I am using: PuppeteerAdapter, FSPersister.
When I turn off Polly the request completes successfully.

I recorded a video of the chromium's console:
https://gfycat.com/EssentialShadowyAnura

Here are the versions I am using:

```
    "@pollyjs/adapter-puppeteer": "^1.1.0",
    "@pollyjs/core": "^1.1.0",
    "@pollyjs/persister-fs": "^1.0.1",
```

and the configs:

**Server**
```
{
      recordingsDir: path.join(__dirname, 'recordings'),
      quiet: false,
      port: 3001,
      host: 'localhost'
}
```

**Polly**

```
{
      adapters: ['puppeteer'],
      adapterOptions: {
        puppeteer: { page }
      },
      persister: 'fs',
      persisterOptions: {
        host: 'http://localhost:3001'
      },
      logging: true
}
```

Is there something I am missing in the config? Or in general?

**Comment by offirgolan** [comment]
@meikoudras since you're running Polly w/ Puppeteer & the FS persister, there is no need for the node server since its only to be used with the REST adapter. You can change your config to be:

```
{
      adapters: ['puppeteer'],
      adapterOptions: {
        puppeteer: { page }
      },
      persister: 'fs',
      persisterOptions: {
        fs: { recordingsDir: path.join(__dirname, 'recordings') }
      },
      logging: true
}
```

If turning off the node server and changing the config to the one above doesnt work, let me know. If you could add more details on your environment and the requests being made, that would help debug this issue.

**Comment by meikoudras** [comment]
Thank you for your response! Unfortunately turning off the node server and updating the configuration did not work.

I made a repo where the issue is replicated (based it off an example of the jest-puppeteer repo: https://github.com/smooth-code/jest-puppeteer/tree/master/examples/create-react-app)

The repo is here:

https://github.com/meikoudras/jest-puppeteer-polly-test

Should demonstrate the issue with running: 

```
yarn && yarn test:integration
```
If there is any more info I should provide let me know and I will try to help as much as I can

**Comment by offirgolan** [comment]
Fixed with `@pollyjs/adapter-puppeteer@1.1.1`. @meikoudras thanks again for the reproduction, it was super helpful!

**Comment by meikoudras** [comment]
Thank you for the quick fix!

I have updated the repo with another issue which seems to be related to CORS as well:
https://github.com/meikoudras/jest-puppeteer-polly-test

The previous get request will work correctly but making a post request will again make the browser crash. I can make a separate issue for that as well, if that is required.

**Comment by jasonmit** [comment]
core@1.1.3 and adapter-puppeteer@1.1.3 resolves this.
